ARG GAMECI_IMAGE=unityci/editor:ubuntu-6000.0.17f1-webgl-3.1.0

FROM $GAMECI_IMAGE

ARG BLENDER_SHORT_VERSION=4.1
ARG BLENDER_FULL_VERSION=4.1.1

RUN echo "BLENDER_SHORT_VERSION: $BLENDER_SHORT_VERSION"
RUN echo "BLENDER_FULL_VERSION: $BLENDER_FULL_VERSION"

# Install wget and download Blender
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://download.blender.org/release/Blender$BLENDER_SHORT_VERSION/blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz && \
    tar -xf blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz -C /opt && \
    rm blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz
# Add Blender to the PATH
RUN alias blender='/opt/blender-$BLENDER_FULL_VERSION-linux-x64/blender'

# Add Blender to the PATH
ENV PATH="$PATH:/opt/blender-$BLENDER_FULL_VERSION-linux-x64"

RUN cp -r /opt/blender-$BLENDER_FULL_VERSION-linux-x64/* /bin/

# Verify Blender installation
RUN blender --version