ARG GAMECI_IMAGE=unityci/editor:ubuntu-6000.0.17f1-android-3.1.0
FROM $GAMECI_IMAGE

ARG BLENDER_SHORT_VERSION=3.6
ARG BLENDER_FULL_VERSION=3.6.8

RUN echo "BLENDER_SHORT_VERSION: $BLENDER_SHORT_VERSION"
RUN echo "BLENDER_FULL_VERSION: $BLENDER_FULL_VERSION"

# Install wget and download Blender
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://download.blender.org/release/Blender$BLENDER_SHORT_VERSION/blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz && \
    tar -xf blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz -C /opt && \
    rm blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz
# Add Blender to the PATH
ENV PATH="$PATH:/opt/blender-$BLENDER_FULL_VERSION-linux-x64"

# Verify Blender installation
RUN blender --version