ARG GAMECI_IMAGE=unityci/editor:ubuntu-2022.3.16f1-windows-mono-3.1.0
FROM $GAMECI_IMAGE

ARG BLENDER_SHORT_VERSION=4.1
ARG BLENDER_FULL_VERSION=4.1.1

RUN echo "BLENDER_SHORT_VERSION: $BLENDER_SHORT_VERSION"
RUN echo "BLENDER_FULL_VERSION: $BLENDER_FULL_VERSION"
RUN apt-get update && \
    apt-get install -y wget && \
    wget https://download.blender.org/release/Blender$BLENDER_SHORT_VERSION/blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz && \
    tar -xf blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz && \
    rm blender-$BLENDER_FULL_VERSION-linux-x64.tar.xz

ENV PATH="$PATH:/blender-$BLENDER_FULL_VERSION-linux-x64"