Bomberman: LoggedIn Class Reference
LoggedIn Class Reference
Private Member Functions
void Awake ()
IEnumerator CheckLoggedInPeriodically ()
void LoggedOut (string reason)
IEnumerator MoveToLoginScene ()
Detailed Description
Definition at line 7 of file LoggedInChecker.cs.
Member Function Documentation
Awake()
void LoggedIn.Awake () inline private
Definition at line 10 of file LoggedInChecker.cs.
    {
        StartCoroutine(CheckLoggedInPeriodically());
    }
References CheckLoggedInPeriodically().
CheckLoggedInPeriodically()
IEnumerator LoggedIn.CheckLoggedInPeriodically () inline private
Definition at line 15 of file LoggedInChecker.cs.
    {
        while (true)
        {
            // Send the API request
            StartCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORLOGOUT, onFailedAction: LoggedOut));
            // Wait for 60 seconds before sending the next request
            yield return new WaitForSeconds(120f);
        }
    }
References LoggedOut(), and Config.ServerConfig.PATHFORLOGOUT.
Referenced by Awake().
LoggedOut()
void LoggedIn.LoggedOut (string reason) inline private
Definition at line 27 of file LoggedInChecker.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
    }
Referenced by CheckLoggedInPeriodically().
MoveToLoginScene()
IEnumerator LoggedIn.MoveToLoginScene () inline private
Definition at line 32 of file LoggedInChecker.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
        while (true)
        {
            Debug.Log(loading.progress);
            yield return null;
        }
    }
The documentation for this class was generated from the following file:
Assets/Scripts/Client/User/LoggedInChecker.cs