Thesis: MainPage.ProfileHandler Class Reference
MainPage.ProfileHandler Class Reference
Handles the user's profile such as statistics and logout button
Public Member Functions
void Show ()
Shows the profile window
void Hide ()
Hides the profile window
void SendLogout ()
Send a login request with the login panel's fields
Private Member Functions
void LoggedOut (string result)
When the logout was a success
IEnumerator MoveToLoginScene ()
Move to the login screen after the user has logged out
Private Attributes
TMP_Text totalTaskCount
Label for how many tasks had the user completed since registering
TMP_Text goodTaskCount
Label for how many good tasks had the user completed since registering
TMP_Text badTaskCount
Label for how many bad tasks had the user completed since registering
TMP_Text totalScore
Label for how many task scores did the user accumulate since registering
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Handles the user's profile such as statistics and logout button
Definition at line 14 of file ProfileHandler.cs.
Member Function Documentation
Show()
void MainPage.ProfileHandler.Show () inline
Shows the profile window
Definition at line 43 of file ProfileHandler.cs.
         {
             this.gameObject.SetActive(true);
             this.totalTaskCount.text = (UserData.Instance.CompletedGoodTasks + UserData.Instance.CompletedBadTasks).ToString();
             this.badTaskCount.text = UserData.Instance.CompletedBadTasks.ToString();
             this.goodTaskCount.text = UserData.Instance.CompletedGoodTasks.ToString();
             this.totalScore.text = UserData.Instance.TotalScore.ToString();
         }
References User.UserData.CompletedBadTasks, User.UserData.CompletedGoodTasks, User.UserData.Instance, and User.UserData.TotalScore.
Hide()
void MainPage.ProfileHandler.Hide () inline
Hides the profile window
Definition at line 55 of file ProfileHandler.cs.
         {
             this.gameObject.SetActive(false);
         }
SendLogout()
void MainPage.ProfileHandler.SendLogout () inline
Send a login request with the login panel's fields
Definition at line 63 of file ProfileHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORLOGOUT, LoggedOut));
         }
References MainPage.ProfileHandler.LoggedOut(), Config.ServerConfig.PATHFORLOGOUT, and Utility.CoroutineRunner.RunCoroutine().
LoggedOut()
void MainPage.ProfileHandler.LoggedOut (string result) inline private
When the logout was a success
Parameters
result The server's response
Definition at line 72 of file ProfileHandler.cs.
         {
             UserData.Instance.Logout();
             CoroutineRunner.RunCoroutine(MoveToLoginScene());
         }
References User.UserData.Instance, User.UserData.Logout(), MainPage.ProfileHandler.MoveToLoginScene(), and Utility.CoroutineRunner.RunCoroutine().
Referenced by MainPage.ProfileHandler.SendLogout().
MoveToLoginScene()
IEnumerator MainPage.ProfileHandler.MoveToLoginScene () inline private
Move to the login screen after the user has logged out
Definition at line 82 of file ProfileHandler.cs.
         {
             AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
             while (!loading.isDone)
             {
                 Debug.Log(loading.progress);
                 yield return null;
             }
         }
Referenced by MainPage.ProfileHandler.LoggedOut().
Member Data Documentation
totalTaskCount
TMP_Text MainPage.ProfileHandler.totalTaskCount private
Label for how many tasks had the user completed since registering
Definition at line 20 of file ProfileHandler.cs.
goodTaskCount
TMP_Text MainPage.ProfileHandler.goodTaskCount private
Label for how many good tasks had the user completed since registering
Definition at line 26 of file ProfileHandler.cs.
badTaskCount
TMP_Text MainPage.ProfileHandler.badTaskCount private
Label for how many bad tasks had the user completed since registering
Definition at line 32 of file ProfileHandler.cs.
totalScore
TMP_Text MainPage.ProfileHandler.totalScore private
Label for how many task scores did the user accumulate since registering
Definition at line 38 of file ProfileHandler.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/ProfileHandler.cs