Thesis: Game.World.CarSpawner Class Reference
Game.World.CarSpawner Class Reference
Car spawner
Public Member Functions
void Update ()
Called every frame and increase the timers and spawn if they reached the threshold
void SpawnPolice (GameObject carPrefab)
Spawn the given cop car
void Reset ()
Reset the timers
void SpawnNpc ()
Spawn the npc car
Private Attributes
GameController gameController
Reference to the game controller
List< GameObject > CopCars
Cop car prefabs
List< GameObject > CitizenCars
Citizen car prefabs
Dictionary< int, float > spawnIntervalsTier1 = new Dictionary<int, float>() { { 0, 6 }, { 1, 5 }, { 2, 4 }, { 3, 3 }, { 4, 1 }, { 5, 1 } }
Tier one car spawn timers (regular cop car)
Dictionary< int, float > spawnIntervalsTier2 = new Dictionary<int, float>() { { 0, float.PositiveInfinity }, { 1, float.PositiveInfinity }, { 2, float.PositiveInfinity }, { 3, 8 }, { 4, 6 }, { 5, 3 } }
Tier two car spawn timers (cop van)
Dictionary< int, float > spawnIntervalsTier3 = new Dictionary<int, float>() { { 0, float.PositiveInfinity }, { 1, float.PositiveInfinity }, { 2, float.PositiveInfinity }, { 3, float.PositiveInfinity }, { 4, 10 }, { 5, 5 } }
Tier three car spawn timers (tank)
float tier1SpawnerTimer = 0f
Tier one cop car timer
float tier2SpawnerTimer = 0f
Tier two cop car timer
float tier3SpawnerTimer = 0f
Tier three cop car timer
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Car spawner
Definition at line 12 of file CarSpawner.cs.
Member Function Documentation
Update()
void Game.World.CarSpawner.Update () inline
Called every frame and increase the timers and spawn if they reached the threshold
Definition at line 65 of file CarSpawner.cs.
             {
                 //Make it only run during running game
                 if (!gameController.Running)
                 {
                     return;
                 }
                 //Increase the timers
                 tier1SpawnerTimer += Time.deltaTime;
                 tier2SpawnerTimer += Time.deltaTime;
                 tier3SpawnerTimer += Time.deltaTime;
                 //After threshold is reached spawn the car
                 if (tier1SpawnerTimer > spawnIntervalsTier1[gameController.Difficulty])
                 {
                     SpawnPolice(CopCars[0]);
                     tier1SpawnerTimer = 0f;
                 }
                 if (tier2SpawnerTimer > spawnIntervalsTier2[gameController.Difficulty])
                 {
                     SpawnPolice(CopCars[1]);
                     tier2SpawnerTimer = 0f;
                 }
                 if (tier3SpawnerTimer > spawnIntervalsTier3[gameController.Difficulty])
                 {
                     SpawnPolice(CopCars[2]);
                     tier3SpawnerTimer = 0f;
                 }
             }
References Game.World.CarSpawner.CopCars, Game.GameController.Difficulty, Game.World.CarSpawner.gameController, Game.GameController.Running, Game.World.CarSpawner.spawnIntervalsTier1, Game.World.CarSpawner.spawnIntervalsTier2, Game.World.CarSpawner.spawnIntervalsTier3, Game.World.CarSpawner.SpawnPolice(), Game.World.CarSpawner.tier1SpawnerTimer, Game.World.CarSpawner.tier2SpawnerTimer, and Game.World.CarSpawner.tier3SpawnerTimer.
SpawnPolice()
void Game.World.CarSpawner.SpawnPolice (GameObject carPrefab) inline
Spawn the given cop car
Parameters
carPrefab Cop car to spawn
Definition at line 102 of file CarSpawner.cs.
             {
                 Chunk playerChunk = gameController.World.GetChunk(gameController.PlayerPos);
                 CopCar copCar = Instantiate(carPrefab, playerChunk.gameObject.transform, true).GetComponent<CopCar>();
                 copCar.Init(gameController);
                 Vector3 roadPos = playerChunk.GetARandomRoad();
                 copCar.transform.transform.localPosition = new Vector3(roadPos.x * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL, playerChunk.gameObject.transform.position.y + 2, roadPos.z * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL);
             }
References Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_SCALE, Game.World.CarSpawner.gameController, Game.World.Chunk.GetARandomRoad(), Game.Car.Init(), Game.GameController.PlayerPos, and Game.GameController.World.
Referenced by Game.World.CarSpawner.Update().
Reset()
void Game.World.CarSpawner.Reset () inline
Reset the timers
Definition at line 114 of file CarSpawner.cs.
             {
                 tier1SpawnerTimer = 0f;
                 tier2SpawnerTimer = 0f;
                 tier3SpawnerTimer = 0f;
             }
References Game.World.CarSpawner.tier1SpawnerTimer, Game.World.CarSpawner.tier2SpawnerTimer, and Game.World.CarSpawner.tier3SpawnerTimer.
Referenced by Game.GameController.NewGame().
SpawnNpc()
void Game.World.CarSpawner.SpawnNpc () inline
Spawn the npc car
Definition at line 124 of file CarSpawner.cs.
             {
             }
Member Data Documentation
gameController
GameController Game.World.CarSpawner.gameController private
Reference to the game controller
Definition at line 18 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.SpawnPolice(), and Game.World.CarSpawner.Update().
CopCars
List<GameObject> Game.World.CarSpawner.CopCars private
Cop car prefabs
Definition at line 24 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Update().
CitizenCars
List<GameObject> Game.World.CarSpawner.CitizenCars private
Citizen car prefabs
Definition at line 30 of file CarSpawner.cs.
spawnIntervalsTier1
Dictionary<int, float> Game.World.CarSpawner.spawnIntervalsTier1 = new Dictionary<int, float>() { { 0, 6 }, { 1, 5 }, { 2, 4 }, { 3, 3 }, { 4, 1 }, { 5, 1 } } private
Tier one car spawn timers (regular cop car)
Definition at line 35 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Update().
spawnIntervalsTier2
Dictionary<int, float> Game.World.CarSpawner.spawnIntervalsTier2 = new Dictionary<int, float>() { { 0, float.PositiveInfinity }, { 1, float.PositiveInfinity }, { 2, float.PositiveInfinity }, { 3, 8 }, { 4, 6 }, { 5, 3 } } private
Tier two car spawn timers (cop van)
Definition at line 40 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Update().
spawnIntervalsTier3
Dictionary<int, float> Game.World.CarSpawner.spawnIntervalsTier3 = new Dictionary<int, float>() { { 0, float.PositiveInfinity }, { 1, float.PositiveInfinity }, { 2, float.PositiveInfinity }, { 3, float.PositiveInfinity }, { 4, 10 }, { 5, 5 } } private
Tier three car spawn timers (tank)
Definition at line 45 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Update().
tier1SpawnerTimer
float Game.World.CarSpawner.tier1SpawnerTimer = 0f private
Tier one cop car timer
Definition at line 50 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Reset(), and Game.World.CarSpawner.Update().
tier2SpawnerTimer
float Game.World.CarSpawner.tier2SpawnerTimer = 0f private
Tier two cop car timer
Definition at line 55 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Reset(), and Game.World.CarSpawner.Update().
tier3SpawnerTimer
float Game.World.CarSpawner.tier3SpawnerTimer = 0f private
Tier three cop car timer
Definition at line 60 of file CarSpawner.cs.
Referenced by Game.World.CarSpawner.Reset(), and Game.World.CarSpawner.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World/CarSpawner.cs