Bomberman: UnityStandardAssets.CrossPlatformInput.ButtonHandler Class Reference
UnityStandardAssets.CrossPlatformInput.ButtonHandler Class Reference
Public Member Functions
void SetDownState ()
void SetUpState ()
void SetAxisPositiveState ()
void SetAxisNeutralState ()
void SetAxisNegativeState ()
void Update ()
Public Attributes
string Name
Private Member Functions
void OnEnable ()
Detailed Description
Definition at line 6 of file ButtonHandler.cs.
Member Function Documentation
OnEnable()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.OnEnable () inline private
Definition at line 11 of file ButtonHandler.cs.
         {
         }
SetDownState()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetDownState () inline
Definition at line 16 of file ButtonHandler.cs.
         {
             CrossPlatformInputManager.SetButtonDown(Name);
         }
References UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonDown().
SetUpState()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetUpState () inline
Definition at line 22 of file ButtonHandler.cs.
         {
             CrossPlatformInputManager.SetButtonUp(Name);
         }
References UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonUp().
SetAxisPositiveState()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisPositiveState () inline
Definition at line 28 of file ButtonHandler.cs.
         {
             CrossPlatformInputManager.SetAxisPositive(Name);
         }
References UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisPositive().
SetAxisNeutralState()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNeutralState () inline
Definition at line 34 of file ButtonHandler.cs.
         {
             CrossPlatformInputManager.SetAxisZero(Name);
         }
References UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisZero().
SetAxisNegativeState()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNegativeState () inline
Definition at line 40 of file ButtonHandler.cs.
         {
             CrossPlatformInputManager.SetAxisNegative(Name);
         }
References UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisNegative().
Update()
void UnityStandardAssets.CrossPlatformInput.ButtonHandler.Update () inline
Definition at line 45 of file ButtonHandler.cs.
         {
         }
Member Data Documentation
Name
string UnityStandardAssets.CrossPlatformInput.ButtonHandler.Name
Definition at line 9 of file ButtonHandler.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNegativeState(), UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNeutralState(), UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisPositiveState(), UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetDownState(), and UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetUpState().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/ButtonHandler.cs