Thesis: MainPage.TaskDisplayHandler Class Reference
MainPage.TaskDisplayHandler Class Reference
Task prefab display handler
Public Member Functions
void Update ()
Called every frame if it has been completed update the remaining time
void InitValues (PlayerTask playerTask, TaskOpenPanelController taskOpenPanelController, MainWindowController uIController)
Init it with the task to display and references to the controls
void CompleteTask ()
Complete the task and send this to the server
void OpenEditor ()
Open the task editor
void UpdateLabels ()
Update the task's labels
Properties
PlayerTask CurrentTask [get, private set]
The task which is being displayed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void TaskCompleted (Thesis_backend.Data_Structures.PlayerTask result)
When the complete acknowledge were recieved from the server update the display
void CompleteStateChange (bool state)
When the complete state is changed update the display to match it
void UpdateTimeRemaining ()
Update the time remaining until the task can be completed again
bool CalculateIfCompleteable ()
Calculate if the task can be completed again
Private Attributes
TMP_Text taskNameLabel
The displayed task's name
TMP_Text taskIntervalsLabel
The displayed task's interval
TMP_Text remainingTimeLabel
The displayed task's remaining time until it can be completed again
Button completeButton
Complete button for the displayed task
MainWindowController mainWindowController
Reference to the main window controller
TaskOpenPanelController taskOpenPanelController
Reference to the task edit/create panel
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Task prefab display handler
Definition at line 15 of file TaskDisplayHandler.cs.
Member Function Documentation
Update()
void MainPage.TaskDisplayHandler.Update () inline
Called every frame if it has been completed update the remaining time
Definition at line 59 of file TaskDisplayHandler.cs.
         {
             if (CurrentTask.Completed)
             {
                 UpdateTimeRemaining();
             }
         }
References MainPage.TaskDisplayHandler.CurrentTask, and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
InitValues()
void MainPage.TaskDisplayHandler.InitValues (PlayerTask playerTask, TaskOpenPanelController taskOpenPanelController, MainWindowController uIController) inline
Init it with the task to display and references to the controls
Parameters
playerTask The task to display
taskOpenPanelController Reference to the task panel
uIController Reference to the
Definition at line 73 of file TaskDisplayHandler.cs.
         {
             this.CurrentTask = playerTask;
             if (!CalculateIfCompleteable())
             {
                 CompleteStateChange(true);
             }
             this.taskOpenPanelController = taskOpenPanelController;
             this.mainWindowController = uIController;
             UpdateLabels();
         }
References MainPage.TaskDisplayHandler.CalculateIfCompleteable(), MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.CurrentTask, MainPage.TaskDisplayHandler.taskOpenPanelController, and MainPage.TaskDisplayHandler.UpdateLabels().
Referenced by MainPage.MainWindowController.CreateTask().
CompleteTask()
void MainPage.TaskDisplayHandler.CompleteTask () inline
Complete the task and send this to the server
Definition at line 89 of file TaskDisplayHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKCOMPLETE(CurrentTask.ID), onComplete: TaskCompleted, onFailedAction: mainWindowController.ShowTaskFail));
         }
References MainPage.TaskDisplayHandler.CurrentTask, MainPage.TaskDisplayHandler.mainWindowController, Config.ServerConfig.PATHFORTASKCOMPLETE(), Utility.CoroutineRunner.RunCoroutine(), MainPage.MainWindowController.ShowTaskFail(), and MainPage.TaskDisplayHandler.TaskCompleted().
OpenEditor()
void MainPage.TaskDisplayHandler.OpenEditor () inline
Open the task editor
Definition at line 97 of file TaskDisplayHandler.cs.
         {
             taskOpenPanelController.OpenUp(this.CurrentTask);
         }
References MainPage.TaskDisplayHandler.CurrentTask, MainPage.TaskOpenPanelController.OpenUp(), and MainPage.TaskDisplayHandler.taskOpenPanelController.
TaskCompleted()
void MainPage.TaskDisplayHandler.TaskCompleted (Thesis_backend.Data_Structures.PlayerTask result) inline private
When the complete acknowledge were recieved from the server update the display
Parameters
result The completed task
Definition at line 106 of file TaskDisplayHandler.cs.
         {
             CompleteStateChange(true);
             //Update the user's task score
             CoroutineRunner.RunCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>
                 (ServerConfig.PATHFORCHECKLOGGEDIN,
                 (Thesis_backend.Data_Structures.User u) => { mainWindowController.UpdateUserData(u); if (mainWindowController.TaskSortType == TaskSortType.Available) mainWindowController.SortingChanged(); },
                 onFailedAction: mainWindowController.ShowTaskFail));
         }
References MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.mainWindowController, Config.ServerConfig.PATHFORCHECKLOGGEDIN, Utility.CoroutineRunner.RunCoroutine(), and MainPage.MainWindowController.ShowTaskFail().
Referenced by MainPage.TaskDisplayHandler.CompleteTask().
UpdateLabels()
void MainPage.TaskDisplayHandler.UpdateLabels () inline
Update the task's labels
Definition at line 119 of file TaskDisplayHandler.cs.
         {
             taskNameLabel.text = CurrentTask.TaskName;
             taskIntervalsLabel.text = ((TaskIntervals)CurrentTask.PeriodRate).ToString();
             UpdateTimeRemaining();
         }
References MainPage.TaskDisplayHandler.CurrentTask, MainPage.TaskDisplayHandler.taskIntervalsLabel, MainPage.TaskDisplayHandler.taskNameLabel, and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
Referenced by MainPage.TaskDisplayHandler.InitValues().
CompleteStateChange()
void MainPage.TaskDisplayHandler.CompleteStateChange (bool state) inline private
When the complete state is changed update the display to match it
Parameters
state true-task is being completed, false - task is now available again
Definition at line 130 of file TaskDisplayHandler.cs.
         {
             remainingTimeLabel.gameObject.SetActive(state);
             if (state)
             {
                 this.CurrentTask.Complete();
                 completeButton.gameObject.SetActive(false);
                 UpdateTimeRemaining();
             }
             else
             {
                 if (mainWindowController.TaskSortType == TaskSortType.Available)
                 {
                     mainWindowController.SortingChanged();
                 }
                 this.CurrentTask.ResetComplete();
                 completeButton.gameObject.SetActive(true);
                 return;
             }
         }
References MainPage.TaskDisplayHandler.CurrentTask, MainPage.TaskDisplayHandler.mainWindowController, MainPage.TaskDisplayHandler.remainingTimeLabel, MainPage.MainWindowController.SortingChanged(), MainPage.MainWindowController.TaskSortType, and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
Referenced by MainPage.TaskDisplayHandler.InitValues(), MainPage.TaskDisplayHandler.TaskCompleted(), and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
UpdateTimeRemaining()
void MainPage.TaskDisplayHandler.UpdateTimeRemaining () inline private
Update the time remaining until the task can be completed again
Definition at line 154 of file TaskDisplayHandler.cs.
         {
             //Check if this is needed even
             if (CurrentTask.Completed)
             {
                 //Calculate how much time till it can be completed again
                 TimeSpan difference = TimeSpan.FromMinutes(CurrentTask.PeriodRate) - (DateTime.UtcNow - CurrentTask.LastCompleted);
                 //If it can be completed again update the layout
                 if (difference.TotalMinutes <= 0)
                 {
                     CompleteStateChange(false);
                     return;
                 }
                 string formatted = "";
                 //If it is less then a day away hide the day part
                 if ((int)difference.TotalDays > 0)
                 {
                     formatted = string.Format("{0} days {1:D2}:{2:D2}:{3:D2}", (int)difference.TotalDays, difference.Hours, difference.Minutes, difference.Seconds);
                 }
                 else
                 {
                     formatted = string.Format("{0:D2}:{1:D2}:{2:D2}", difference.Hours, difference.Minutes, difference.Seconds);
                 }
                 remainingTimeLabel.text = formatted;
             }
         }
References MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.CurrentTask, and MainPage.TaskDisplayHandler.remainingTimeLabel.
Referenced by MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.Update(), and MainPage.TaskDisplayHandler.UpdateLabels().
CalculateIfCompleteable()
bool MainPage.TaskDisplayHandler.CalculateIfCompleteable () inline private
Calculate if the task can be completed again
Returns
true-can be completed, false-can't be completed
Definition at line 186 of file TaskDisplayHandler.cs.
         {
             TimeSpan difference = TimeSpan.FromMinutes(CurrentTask.PeriodRate) - (DateTime.UtcNow - CurrentTask.LastCompleted);
             return difference.TotalMinutes <= 0;
         }
References MainPage.TaskDisplayHandler.CurrentTask.
Referenced by MainPage.TaskDisplayHandler.InitValues().
Member Data Documentation
taskNameLabel
TMP_Text MainPage.TaskDisplayHandler.taskNameLabel private
The displayed task's name
Definition at line 21 of file TaskDisplayHandler.cs.
Referenced by MainPage.TaskDisplayHandler.UpdateLabels().
taskIntervalsLabel
TMP_Text MainPage.TaskDisplayHandler.taskIntervalsLabel private
The displayed task's interval
Definition at line 27 of file TaskDisplayHandler.cs.
Referenced by MainPage.TaskDisplayHandler.UpdateLabels().
remainingTimeLabel
TMP_Text MainPage.TaskDisplayHandler.remainingTimeLabel private
The displayed task's remaining time until it can be completed again
Definition at line 33 of file TaskDisplayHandler.cs.
Referenced by MainPage.TaskDisplayHandler.CompleteStateChange(), and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
completeButton
Button MainPage.TaskDisplayHandler.completeButton private
Complete button for the displayed task
Definition at line 39 of file TaskDisplayHandler.cs.
mainWindowController
MainWindowController MainPage.TaskDisplayHandler.mainWindowController private
Reference to the main window controller
Definition at line 44 of file TaskDisplayHandler.cs.
Referenced by MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.CompleteTask(), and MainPage.TaskDisplayHandler.TaskCompleted().
taskOpenPanelController
TaskOpenPanelController MainPage.TaskDisplayHandler.taskOpenPanelController private
Reference to the task edit/create panel
Definition at line 49 of file TaskDisplayHandler.cs.
Referenced by MainPage.TaskDisplayHandler.InitValues(), and MainPage.TaskDisplayHandler.OpenEditor().
Property Documentation
CurrentTask
PlayerTask MainPage.TaskDisplayHandler.CurrentTask get private set
The task which is being displayed
Definition at line 54 of file TaskDisplayHandler.cs.
 { get; private set; }
Referenced by MainPage.TaskDisplayHandler.CalculateIfCompleteable(), MainPage.TaskDisplayHandler.CompleteStateChange(), MainPage.TaskDisplayHandler.CompleteTask(), MainPage.TaskDisplayHandler.InitValues(), MainPage.TaskDisplayHandler.OpenEditor(), MainPage.TaskDisplayHandler.Update(), MainPage.TaskDisplayHandler.UpdateLabels(), and MainPage.TaskDisplayHandler.UpdateTimeRemaining().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/DisplayElements/TaskDisplayHandler.cs