Thesis: Game.World.RoadGenerator Class Reference
Game.World.RoadGenerator Class Reference
Generates a new road structure.
Public Member Functions
RoadGenerator (int size, List< EdgeRoadContainer > startPositions, Chunk[,] nearbyChunks)
Creates the road matrix.
Properties
int NumberOfEdgeRoads [get]
How many roads must the outside should have.
bool[,] RoadMatrix [get, private set]
The matrix which stores where the roads are.
List< EdgeRoadContainer > EdgeRoads [get, private set]
How many roads are currently on the edge.
Private Member Functions
void CreateRoad (Vector2Int roadPos, Vector2Int roadDir, int forwardCounter=0)
Creates the roads recursively.
bool GoinTowardsEdge (Vector2Int position, Vector2Int dir)
Check if the road is going towards the edge.
bool CheckForward (Vector2Int position, Vector2Int dir, int counter)
Checks if the road moving in that direction will run into an another road.
Private Attributes
int size
Size of the matrix.
int numberOfPlacedRoads = 0
The number of roads which was placed.
Chunk[,] nearbyChunks
The nearby chunks for checking the roads forward.
bool[,] lockRoad
Load the road and nearby cells, so we don't have to roads parallel next to each other.
Detailed Description
Generates a new road structure.
Definition at line 11 of file RoadGenerator.cs.
Constructor & Destructor Documentation
RoadGenerator()
Game.World.RoadGenerator.RoadGenerator (int size, List< EdgeRoadContainer > startPositions, Chunk nearbyChunks[,]) inline
Creates the road matrix.
Parameters
numberOfEdgeRoads How many roads should be on the matrix edges
size How large is the chunk is to generate the road for
startPositions The positions to start the generation from
Definition at line 54 of file RoadGenerator.cs.
            {
                this.nearbyChunks = nearbyChunks;
                this.RoadMatrix = new bool[size, size];
                this.EdgeRoads = new List<EdgeRoadContainer>();
                this.size = size;
                this.lockRoad = new bool[size, size];
                if (startPositions.Count == 0)
                {
                    startPositions.Add(new EdgeRoadContainer(new Vector2Int(GameConfig.CHUNK_SIZE / 2, 0), 0, new Vector2Int(0, 1)));
                    this.RoadMatrix[0, GameConfig.CHUNK_SIZE / 2] = true;
                    EdgeRoads.Add(new EdgeRoadContainer(new Vector2Int(GameConfig.CHUNK_SIZE / 2, 0), 1, new Vector2Int(0, -1)));
                    numberOfPlacedRoads++;
                }
                foreach (var generateStartPos in startPositions)
                {
                    Vector2Int startPos = generateStartPos.EdgeRoad + generateStartPos.Direction;
                    Vector2Int newStart = new Vector2Int((startPos.x + size) % size, (startPos.y + size) % size);
                    RoadMatrix[newStart.y, newStart.x] = true;
                    numberOfPlacedRoads++;
                    EdgeRoads.Add(new EdgeRoadContainer(newStart, 1, generateStartPos.Direction));
                    CreateRoad(new Vector2Int(newStart.x + generateStartPos.Direction.x, newStart.y + generateStartPos.Direction.y), generateStartPos.Direction, 0);
                }
            }
References Game.GameConfig.CHUNK_SIZE, Game.World.RoadGenerator.CreateRoad(), Game.World.RoadGenerator.EdgeRoads, Game.World.RoadGenerator.nearbyChunks, Game.World.RoadGenerator.numberOfPlacedRoads, Game.World.RoadGenerator.RoadMatrix, and Game.World.RoadGenerator.size.
Member Function Documentation
CreateRoad()
void Game.World.RoadGenerator.CreateRoad (Vector2Int roadPos, Vector2Int roadDir, int forwardCounter = 0) inline private
Creates the roads recursively.
Parameters
roadPos The road's current position
roadDir Where should the road's direction cuntinue to
forwardCounter How long did the road go straight for
Definition at line 86 of file RoadGenerator.cs.
            {
                if (RoadMatrix[roadPos.y, roadPos.x])
                {
                    return;
                }
                this.RoadMatrix[roadPos.y, roadPos.x] = true;
                numberOfPlacedRoads++;
                if (roadPos.x == 0 || roadPos.x == size - 1 || roadPos.y == 0 || roadPos.y == size - 1)
                {
                    this.EdgeRoads.Add(new EdgeRoadContainer(roadPos, forwardCounter, roadDir));
                    return;
                }
                //Make sure that the chunk doesn't get flooded
                if (false && Random.Range(0.8f, 1f) < numberOfPlacedRoads / (size * size))
                {
                    return;
                }
                // || Mathf.Pow(forwardCounter - 1, 5) / 2 > Random.Range(0f, 1f)
                //Should the road change direction
                if ((forwardCounter > 2 && !lockRoad[roadPos.y, roadPos.x]) && !CheckForward(roadPos + roadDir, roadDir, 0) && !GoinTowardsEdge(roadPos, roadDir))
                {
                    int interSectionCount = Random.Range(3, 4);
                    List<Vector2Int> possibleDirs = new List<Vector2Int>();
                    //The possible directions
                    possibleDirs.Add(new Vector2Int(roadPos.x - 1, roadPos.y));
                    possibleDirs.Add(new Vector2Int(roadPos.x + 1, roadPos.y));
                    possibleDirs.Add(new Vector2Int(roadPos.x, roadPos.y - 1));
                    possibleDirs.Add(new Vector2Int(roadPos.x, roadPos.y + 1));
                    for (int i = 0; i < interSectionCount && possibleDirs.Count != 0; i++)
                    {
                        int index = Random.Range(0, possibleDirs.Count);
                        if (!CheckForward(possibleDirs[index], possibleDirs[index] - roadPos, 0) && !GoinTowardsEdge(roadPos, roadDir))
{
                            CreateRoad(possibleDirs[index], possibleDirs[index] - roadPos, 0);
                        }
                        possibleDirs.RemoveAt(index);
                    }
                }
                else
                {
                    lockRoad[roadPos.y, roadPos.x] = true;
                    if (roadDir.x == 0)
                    {
                        if (roadDir.x - 1 >= 0)
{
                            lockRoad[roadPos.y, roadPos.x - 1] = true;
                        }
                        if (roadDir.x + 1 < GameConfig.CHUNK_SIZE)
{
                            lockRoad[roadPos.y, roadPos.x + 1] = true;
                        }
                    }
                    else
                    {
                        if (roadDir.y - 1 >= 0)
{
                            lockRoad[roadPos.y - 1, roadPos.x] = true;
                        }
                        if (roadDir.y + 1 < GameConfig.CHUNK_SIZE)
{
                            lockRoad[roadPos.y + 1, roadPos.x] = true;
                        }
                    }
                    //Make the road move forward
                    CreateRoad(roadPos + roadDir, roadDir, forwardCounter + 1);
                }
            }
References Game.World.RoadGenerator.CheckForward(), Game.GameConfig.CHUNK_SIZE, Game.World.RoadGenerator.CreateRoad(), Game.World.RoadGenerator.EdgeRoads, Game.World.RoadGenerator.GoinTowardsEdge(), Game.World.RoadGenerator.lockRoad, Game.World.RoadGenerator.numberOfPlacedRoads, Game.World.RoadGenerator.RoadMatrix, and Game.World.RoadGenerator.size.
Referenced by Game.World.RoadGenerator.CreateRoad(), and Game.World.RoadGenerator.RoadGenerator().
GoinTowardsEdge()
bool Game.World.RoadGenerator.GoinTowardsEdge (Vector2Int position, Vector2Int dir) inline private
Check if the road is going towards the edge.
Parameters
position The staring position
dir Move direction
Returns
true-going towards the edge, false-still inside
Definition at line 168 of file RoadGenerator.cs.
            {
                int newXCoord = position.x + dir.x * 5;
                int newYCoord = position.y + dir.y * 5;
                return newXCoord < 0 || newYCoord < 0 || newXCoord >= GameConfig.CHUNK_SIZE || newYCoord >= GameConfig.CHUNK_SIZE;
            }
References Game.GameConfig.CHUNK_SIZE.
Referenced by Game.World.RoadGenerator.CreateRoad().
CheckForward()
bool Game.World.RoadGenerator.CheckForward (Vector2Int position, Vector2Int dir, int counter) inline private
Checks if the road moving in that direction will run into an another road.
Parameters
position The position of the road which is being checked
dir The direction where the checking should be
counter How long the checking has processed
Returns
true-if it ran into a road, false if it didn't run into a road
Definition at line 183 of file RoadGenerator.cs.
            {
                if (position.x < 0)
                {
                    if (nearbyChunks[1, 0] is null)
                    {
                        return false;
                    }
                    if (nearbyChunks[1, 0].Roads[position.y, position.x + GameConfig.CHUNK_SIZE])
                    {
                        return true;
                    }
                }
                else if (position.y < 0)
                {
                    if (nearbyChunks[0, 1] is null)
                    {
                        return false;
                    }
                    if (nearbyChunks[0, 1].Roads[position.y + GameConfig.CHUNK_SIZE, position.x])
                    {
                        return true;
                    }
                }
                else if (position.x >= size)
                {
                    if (nearbyChunks[1, 2] is null)
                    {
                        return false;
                    }
                    if (nearbyChunks[1, 2].Roads[position.y, position.x - GameConfig.CHUNK_SIZE])
                    {
                        return true;
                    }
                }
                else if (position.y >= size)
                {
                    if (nearbyChunks[2, 1] is null)
                    {
                        return false;
                    }
                    if (nearbyChunks[2, 1].Roads[position.y - GameConfig.CHUNK_SIZE, position.x])
                    {
                        return true;
                    }
                }
                else if (RoadMatrix[position.y, position.x])
                {
                    return true;
                }
                if (counter < 5)
                {
                    return CheckForward(position + dir, dir, counter + 1);
                }
                else
                {
                    return false;
                }
            }
References Game.World.RoadGenerator.CheckForward(), Game.GameConfig.CHUNK_SIZE, Game.World.RoadGenerator.nearbyChunks, Game.World.RoadGenerator.RoadMatrix, and Game.World.RoadGenerator.size.
Referenced by Game.World.RoadGenerator.CheckForward(), and Game.World.RoadGenerator.CreateRoad().
Member Data Documentation
size
int Game.World.RoadGenerator.size private
Size of the matrix.
Definition at line 26 of file RoadGenerator.cs.
Referenced by Game.World.RoadGenerator.CheckForward(), Game.World.RoadGenerator.CreateRoad(), and Game.World.RoadGenerator.RoadGenerator().
numberOfPlacedRoads
int Game.World.RoadGenerator.numberOfPlacedRoads = 0 private
The number of roads which was placed.
Definition at line 36 of file RoadGenerator.cs.
Referenced by Game.World.RoadGenerator.CreateRoad(), and Game.World.RoadGenerator.RoadGenerator().
nearbyChunks
Chunk [,] Game.World.RoadGenerator.nearbyChunks private
The nearby chunks for checking the roads forward.
Definition at line 41 of file RoadGenerator.cs.
Referenced by Game.World.RoadGenerator.CheckForward(), and Game.World.RoadGenerator.RoadGenerator().
lockRoad
bool [,] Game.World.RoadGenerator.lockRoad private
Load the road and nearby cells, so we don't have to roads parallel next to each other.
Definition at line 46 of file RoadGenerator.cs.
Referenced by Game.World.RoadGenerator.CreateRoad().
Property Documentation
NumberOfEdgeRoads
int Game.World.RoadGenerator.NumberOfEdgeRoads get
How many roads must the outside should have.
Definition at line 16 of file RoadGenerator.cs.
{ get => EdgeRoads.Count; }
RoadMatrix
bool [,] Game.World.RoadGenerator.RoadMatrix get private set
The matrix which stores where the roads are.
Definition at line 21 of file RoadGenerator.cs.
{ get; private set; }
Referenced by Game.World.RoadGenerator.CheckForward(), Game.World.RoadGenerator.CreateRoad(), Game.World.Chunk.CreateTiles(), Game.World.Chunk.DetermineRoadType(), Game.World.Chunk.DetermineTileType(), Game.World.Chunk.GenerateCellMatrix(), and Game.World.RoadGenerator.RoadGenerator().
EdgeRoads
List<EdgeRoadContainer> Game.World.RoadGenerator.EdgeRoads get private set
How many roads are currently on the edge.
Definition at line 31 of file RoadGenerator.cs.
{ get; private set; }
Referenced by Game.World.RoadGenerator.CreateRoad(), and Game.World.RoadGenerator.RoadGenerator().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World/RoadGenerator.cs