Bomberman: UserController Class Reference
UserController Class Reference
Public Member Functions
void SendLogin ()
Send a login request with the login panel's fields
void SendRegister ()
Send a register request with the register panel's fields
bool IsValidEmail (string emailaddress)
Check if the email is valid
void MoveToRegisterWindow ()
Change panels
void MoveToLoginWindow ()
Change panels
Public Attributes
GameObject LoginPanel
The login controls
GameObject RegisterPanel
The register controls
ModalWindow ModalWindow
Private Member Functions
void Start ()
void CheckLoggedIn ()
Send a request to check if the user has logged in already
void LoggedIn (Thesis_backend.Data_Structures.User result)
When the login request's was responded log the user in
void Registered (Thesis_backend.Data_Structures.User loggedInUser)
When the login request's was responded register the user and log him in
IEnumerator MoveToMainScence ()
Move from the user creation and login scene
Detailed Description
Definition at line 11 of file UserController.cs.
Member Function Documentation
Start()
void UserController.Start () inline private
Definition at line 29 of file UserController.cs.
     {
         //Cap the fps to 60
         Application.targetFrameRate = 60;
         QualitySettings.vSyncCount = 0;
         //So the user doesn't need to log in if not necessary
         CheckLoggedIn();
     }
References CheckLoggedIn().
CheckLoggedIn()
void UserController.CheckLoggedIn () inline private
Send a request to check if the user has logged in already
Definition at line 42 of file UserController.cs.
     {
         if (UserData.Instance.LoggedIn)
         {
             MoveToMainScence();
             return;
         }
         WWWForm form = new WWWForm();
         StartCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORCHECKLOGGEDIN, LoggedIn));
     }
References User.UserData.Instance, LoggedIn(), User.UserData.LoggedIn, MoveToMainScence(), and Config.ServerConfig.PATHFORCHECKLOGGEDIN.
Referenced by Start().
SendLogin()
void UserController.SendLogin () inline
Send a login request with the login panel's fields
Definition at line 57 of file UserController.cs.
     {
         TMPro.TMP_InputField[] fields = LoginPanel.GetComponentsInChildren<TMPro.TMP_InputField>();
         UserLoginRequest userLoginRequest = new UserLoginRequest()
         {
             UserIdentification = fields[0].text,
             Password = fields[1].text,
         };
         StartCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORLOGIN, userLoginRequest, LoggedIn));
     }
References LoggedIn(), LoginPanel, and Config.ServerConfig.PATHFORLOGIN.
LoggedIn()
void UserController.LoggedIn (Thesis_backend.Data_Structures.User result) inline private
When the login request's was responded log the user in
Parameters
result The server's response
Definition at line 74 of file UserController.cs.
     {
         UserData.Instance.Init(result);
         StartCoroutine(MoveToMainScence());
     }
References User.UserData.Init(), User.UserData.Instance, and MoveToMainScence().
Referenced by CheckLoggedIn(), and SendLogin().
SendRegister()
void UserController.SendRegister () inline
Send a register request with the register panel's fields
Definition at line 83 of file UserController.cs.
     {
         TMPro.TMP_InputField[] fields = RegisterPanel.GetComponentsInChildren<TMPro.TMP_InputField>();
         if (!IsValidEmail(fields[0].text))
         {
             ModalWindow.Show("Register error", "This is not a valid email!");
             return;
         }
         if (fields[2].text != fields[3].text)
         {
             ModalWindow.Show("Register error", "Passwords does not match!");
             return;
         }
         UserRequest userRequest = new UserRequest()
         {
             UserName = fields[1].text,
             Email = fields[0].text,
             Password = fields[2].text,
         };
         StartCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORREGISTER, userRequest, Registered));
     }
References Thesis_backend.Data_Structures.Email, IsValidEmail(), Config.ServerConfig.PATHFORREGISTER, Registered(), RegisterPanel, and ModalWindow.Show().
Registered()
void UserController.Registered (Thesis_backend.Data_Structures.User loggedInUser) inline private
When the login request's was responded register the user and log him in
Parameters
result The server's response
Definition at line 112 of file UserController.cs.
     {
         UserData.Instance.Init(loggedInUser);
         StartCoroutine(MoveToMainScence());
     }
References User.UserData.Init(), User.UserData.Instance, and MoveToMainScence().
Referenced by SendRegister().
MoveToMainScence()
IEnumerator UserController.MoveToMainScence () inline private
Move from the user creation and login scene
Definition at line 121 of file UserController.cs.
     {
         AsyncOperation loading = SceneManager.LoadSceneAsync("MainMobileFrame", LoadSceneMode.Single);
         while (!loading.isDone)
         {
             yield return null;
         }
     }
Referenced by CheckLoggedIn(), LoggedIn(), and Registered().
IsValidEmail()
bool UserController.IsValidEmail (string emailaddress) inline
Check if the email is valid
Parameters
emailaddress The email to validate
Returns
true-correct false-sus
Definition at line 136 of file UserController.cs.
     {
         try
         {
             MailAddress m = new MailAddress(emailaddress);
             return true;
         }
         catch (FormatException)
         {
             return false;
         }
     }
Referenced by SendRegister().
MoveToRegisterWindow()
void UserController.MoveToRegisterWindow () inline
Change panels
Definition at line 153 of file UserController.cs.
     {
         RegisterPanel.SetActive(true);
         LoginPanel.SetActive(false);
     }
References LoginPanel, and RegisterPanel.
MoveToLoginWindow()
void UserController.MoveToLoginWindow () inline
Change panels
Definition at line 162 of file UserController.cs.
     {
         RegisterPanel.SetActive(false);
         LoginPanel.SetActive(true);
     }
References LoginPanel, and RegisterPanel.
Member Data Documentation
LoginPanel
GameObject UserController.LoginPanel
The login controls
Definition at line 17 of file UserController.cs.
Referenced by MoveToLoginWindow(), MoveToRegisterWindow(), and SendLogin().
RegisterPanel
GameObject UserController.RegisterPanel
The register controls
Definition at line 23 of file UserController.cs.
Referenced by MoveToLoginWindow(), MoveToRegisterWindow(), and SendRegister().
ModalWindow
ModalWindow UserController.ModalWindow
Definition at line 26 of file UserController.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Client/User/UserController.cs