Thesis: Game.PlayerCar Class Reference
Game.PlayerCar Class Reference
Classes
class PoliceContainer
Public Member Functions
void PickedUpCoin ()
void ApplyTurbo ()
void ApplyImmunity ()
void CancelTurbo ()
void CancelImmunity ()
Public Member Functions inherited from Game.Car
void Kill ()
void Init (GameController gameController)
Public Attributes
int SkinId = 1
Public Attributes inherited from Game.Car
EventHandler DestroyedEvent
Protected Member Functions
new void Awake ()
override async void ChunkChanged (Chunk newChunk)
override void Update ()
override void OnCollisionEnter (Collision collision)
Protected Member Functions inherited from Game.Car
bool ChangeChunkIfNeeded ()
void Awake ()
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties
bool Immune = false [get, private set]
bool Turbo = false [get, private set]
Properties inherited from Game.Car
float Health [get, protected set]
float MAX_HEALTH [get, private set]
bool Alive [get]
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void FixedUpdate ()
void OnCollisionExit (Collision collision)
Private Attributes
float coinMultiplier = 1
Keyboard keyboard
int probeSize = 1
List< PoliceContainer > policeContacts = new List<PoliceContainer>()
float turboTimer = 0f
float immuneTimer = 0f
Additional Inherited Members
Protected Attributes inherited from Game.Car
GameController gameController
CarController carController
Chunk lastChunk
Dictionary< EffectType, EffectScript > effects = new Dictionary<EffectType, EffectScript>()
Detailed Description
Definition at line 12 of file PlayerCar.cs.
Member Function Documentation
Awake()
new void Game.PlayerCar.Awake () inline protected
Definition at line 44 of file PlayerCar.cs.
         {
             base.Awake();
         }
PickedUpCoin()
void Game.PlayerCar.PickedUpCoin () inline
Definition at line 49 of file PlayerCar.cs.
         {
             this.gameController.IncreaseCoinCount(1 * coinMultiplier);
         }
References Game.Car.gameController, and Game.GameController.IncreaseCoinCount().
ChunkChanged()
override async void Game.PlayerCar.ChunkChanged (Chunk newChunk) inline protected virtual
Reimplemented from Game.Car.
Definition at line 54 of file PlayerCar.cs.
         {
             await gameController.LoadAndDespawnChunks(newChunk.Row, newChunk.Col);
         }
References Game.World.Chunk.Col, Game.Car.gameController, Game.GameController.LoadAndDespawnChunks(), and Game.World.Chunk.Row.
ApplyTurbo()
void Game.PlayerCar.ApplyTurbo () inline
Definition at line 59 of file PlayerCar.cs.
         {
             if (effects.ContainsKey(EffectType.Turbo))
             {
                 effects[EffectType.Turbo].gameObject.SetActive(true);
             }
             this.turboTimer = 0f;
             this.Turbo = true;
         }
References Game.Car.effects, and Game.PlayerCar.Turbo.
Referenced by Game.UI.GameUI.BuyTurbo().
ApplyImmunity()
void Game.PlayerCar.ApplyImmunity () inline
Definition at line 69 of file PlayerCar.cs.
         {
             if (effects.ContainsKey(EffectType.Shield))
             {
                 effects[EffectType.Shield].gameObject.SetActive(true);
             }
             this.immuneTimer = 0f;
             this.Immune = true;
         }
References Game.Car.effects, and Game.PlayerCar.Immune.
Referenced by Game.UI.GameUI.BuyImmunity().
CancelTurbo()
void Game.PlayerCar.CancelTurbo () inline
Definition at line 79 of file PlayerCar.cs.
         {
             Turbo = false;
             if (effects.ContainsKey(EffectType.Turbo))
             {
                 effects[EffectType.Turbo].gameObject.SetActive(false);
             }
         }
References Game.Car.effects, and Game.PlayerCar.Turbo.
Referenced by Game.UI.GameUI.BuyTurbo().
CancelImmunity()
void Game.PlayerCar.CancelImmunity () inline
Definition at line 88 of file PlayerCar.cs.
         {
             Immune = false;
             if (effects.ContainsKey(EffectType.Shield))
             {
                 effects[EffectType.Shield].gameObject.SetActive(false);
             }
         }
References Game.Car.effects, and Game.PlayerCar.Immune.
Referenced by Game.UI.GameUI.BuyImmunity().
Update()
override void Game.PlayerCar.Update () inline protected virtual
Reimplemented from Game.Car.
Definition at line 97 of file PlayerCar.cs.
         {
             if (!gameController.Running)
             {
                 return;
             }
             if (Turbo)
             {
                 turboTimer += Time.deltaTime;
                 if (turboTimer > GameConfig.TURBO_DURATION)
                 {
                     Turbo = false;
                     if (effects.ContainsKey(EffectType.Turbo))
                     {
                         effects[EffectType.Turbo].gameObject.SetActive(false);
                     }
                 }
             }
             if (Immune)
             {
                 immuneTimer += Time.deltaTime;
                 if (immuneTimer > GameConfig.TURBO_DURATION)
                 {
                     Immune = false;
                     if (effects.ContainsKey(EffectType.Shield))
                     {
                         effects[EffectType.Shield].gameObject.SetActive(false);
                     }
                 }
             }
             base.Update();
             for (int i = 0; i < policeContacts.Count; i++)
             {
                 policeContacts[i].TimeReamaining -= Time.deltaTime;
                 if (policeContacts[i].TimeReamaining <= 0f)
                 {
                     this.DestroyedEvent?.Invoke(this, EventArgs.Empty);
                 }
             }
             //If the car fell of the world trigger game over
             if (this.gameObject.transform.position.y < -5f)
             {
                 this.DestroyedEvent?.Invoke(this, EventArgs.Empty);
             }
         }
References Game.Car.DestroyedEvent, Game.Car.effects, Game.Car.gameController, Game.PlayerCar.Immune, Game.PlayerCar.immuneTimer, Game.PlayerCar.policeContacts, Game.GameController.Running, Game.PlayerCar.Turbo, Game.GameConfig.TURBO_DURATION, and Game.PlayerCar.turboTimer.
FixedUpdate()
void Game.PlayerCar.FixedUpdate () inline private
Definition at line 147 of file PlayerCar.cs.
         {
             //For the  testing unload doesn't cause error
             try
             {
                 if (!Alive)
                 {
                     carController.Move(0f, 0f, 0f, 0f);
                     return;
                 }
                 float turning = 0;
                 float accel = 0;
                 this.keyboard = Keyboard.current;
                 // pass the input to the car
                 if (this.keyboard is not null)
                 {
                     InputSystem.Update();
                     if (this.keyboard.aKey.isPressed || this.keyboard.leftArrowKey.isPressed)
                     {
                         turning = -1;
                     }
                     else if (this.keyboard.dKey.isPressed || this.keyboard.rightArrowKey.isPressed)
                     {
                         turning = 1;
                     }
                     //turning = Input.GetAxis("Horizontal");
                     if (this.keyboard.wKey.isPressed || this.keyboard.upArrowKey.isPressed)
                     {
                         accel = 1;
                     }
                     else if (this.keyboard.sKey.isPressed || this.keyboard.downArrowKey.isPressed)
                     {
                         accel = -1;
                     }
                 }
                 //float accel = Input.GetAxis("Vertical");
                 bool reverse = false;
                 //  if (Input.touchSupported)
                 // {
                 if (Input.touchCount > 0)
                 {
                     for (int i = 0; i < Input.touchCount; i++)
                     {
                         Touch touch = Input.GetTouch(i);
                         if (touch.phase == UnityEngine.TouchPhase.Began || touch.phase == UnityEngine.TouchPhase.Stationary)
{
                             if (turning != 0)
{
                                 reverse = true;
                             }
                             //Check if the touch is on the right or left side of the screen
                             if (touch.position.x > Screen.width / 2)
{
                                 turning = 1;
                             }
                             else if (touch.position.x < Screen.width / 2)
{
                                 turning = -1;
                             }
                         }
                     }
                 }
                 if (accel == 0)
                     accel = Input.touchCount > 1 ? -1 : 1;
                 carController.Move(reverse ? 0 : turning, (Turbo ? accel * 4 : accel), 0f, 0f);
             }
             catch (System.NullReferenceException)
             {
                 Debug.LogWarning("Player car null reference exception");
                 return;
             }
             catch (MissingReferenceException)
             {
                 Debug.LogWarning("Player car missing reference");
                 return;
             }
         }
References Game.Car.Alive, Game.Car.carController, Game.CarController.Move(), and Game.PlayerCar.Turbo.
OnCollisionEnter()
override void Game.PlayerCar.OnCollisionEnter (Collision collision) inline protected virtual
Reimplemented from Game.Car.
Definition at line 232 of file PlayerCar.cs.
         {
             if (!Immune)
             {
                 base.OnCollisionEnter(collision);
             }
             if (collision.gameObject.tag == "Police")
             {
                 policeContacts.Add(new PoliceContainer(collision.gameObject));
             }
         }
References Game.PlayerCar.Immune, and Game.PlayerCar.policeContacts.
OnCollisionExit()
void Game.PlayerCar.OnCollisionExit (Collision collision) inline private
Definition at line 244 of file PlayerCar.cs.
         {
             if (collision.gameObject.tag == "Police")
             {
                 policeContacts.RemoveAll(x => x.PoliceCar == collision.gameObject);
                 // Debug.Log("Removed" + collision.gameObject);
             }
         }
References Game.PlayerCar.policeContacts.
Member Data Documentation
coinMultiplier
float Game.PlayerCar.coinMultiplier = 1 private
Definition at line 15 of file PlayerCar.cs.
SkinId
int Game.PlayerCar.SkinId = 1
Definition at line 18 of file PlayerCar.cs.
Referenced by Game.GameController.PlayerSkinsLoaded().
keyboard
Keyboard Game.PlayerCar.keyboard private
Definition at line 20 of file PlayerCar.cs.
probeSize
int Game.PlayerCar.probeSize = 1 private
Definition at line 34 of file PlayerCar.cs.
policeContacts
List<PoliceContainer> Game.PlayerCar.policeContacts = new List<PoliceContainer>() private
Definition at line 36 of file PlayerCar.cs.
Referenced by Game.PlayerCar.OnCollisionEnter(), Game.PlayerCar.OnCollisionExit(), and Game.PlayerCar.Update().
turboTimer
float Game.PlayerCar.turboTimer = 0f private
Definition at line 41 of file PlayerCar.cs.
Referenced by Game.PlayerCar.Update().
immuneTimer
float Game.PlayerCar.immuneTimer = 0f private
Definition at line 42 of file PlayerCar.cs.
Referenced by Game.PlayerCar.Update().
Property Documentation
Immune
bool Game.PlayerCar.Immune = false get private set
Definition at line 38 of file PlayerCar.cs.
 { get; private set; } = false;
Referenced by Game.PlayerCar.ApplyImmunity(), Game.PlayerCar.CancelImmunity(), Game.PlayerCar.OnCollisionEnter(), Game.PlayerCar.Update(), and Game.UI.GameUI.Update().
Turbo
bool Game.PlayerCar.Turbo = false get private set
Definition at line 39 of file PlayerCar.cs.
 { get; private set; } = false;
Referenced by Game.PlayerCar.ApplyTurbo(), Game.PlayerCar.CancelTurbo(), Game.PlayerCar.FixedUpdate(), Game.PlayerCar.Update(), and Game.UI.GameUI.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CarScripts/PlayerCar.cs