Bomberman: PlayerTask Class Reference
PlayerTask Class Reference
Public Member Functions
void Update ()
void InitValues (TaskContainer taskContainer, TaskOpenPanelController taskOpenPanelController)
void CompleteTask ()
void OpenEditor ()
void UpdateLabels ()
Properties
TaskContainer TaskContainer [get, private set]
Private Member Functions
void TaskCompleted (Thesis_backend.Data_Structures.PlayerTask result)
void CompleteStateChange (bool state)
void UpdateTimeRemaining ()
bool CalculateIfCompleteable ()
Private Attributes
TMP_Text TaskNameLabel
TMP_Text TaskIntervalsLabel
TMP_Text RemainingTimeLabel
Button CompleteButton
TaskOpenPanelController taskOpenPanelController
Static Private Attributes
static Color AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f)
static Color DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f)
Detailed Description
Definition at line 12 of file PlayerTask.cs.
Member Function Documentation
Update()
void PlayerTask.Update () inline
Definition at line 33 of file PlayerTask.cs.
     {
         if (TaskContainer.Completed)
         {
             UpdateTimeRemaining();
         }
     }
References TaskContainer.Completed, and UpdateTimeRemaining().
InitValues()
void PlayerTask.InitValues (TaskContainer taskContainer, TaskOpenPanelController taskOpenPanelController) inline
Definition at line 41 of file PlayerTask.cs.
     {
         this.TaskContainer = taskContainer;
         if (!CalculateIfCompleteable())
         {
             CompleteStateChange(true);
         }
         this.taskOpenPanelController = taskOpenPanelController;
         UpdateLabels();
     }
References CalculateIfCompleteable(), CompleteStateChange(), taskOpenPanelController, and UpdateLabels().
Referenced by UIController.CreateTask().
CompleteTask()
void PlayerTask.CompleteTask () inline
Definition at line 54 of file PlayerTask.cs.
     {
         if (!TaskContainer.Completed)
         {
             WWWForm form = new WWWForm();
             StartCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKCOMPLETE(TaskContainer.Id), onComplete: TaskCompleted));
         }
     }
References TaskContainer.Completed, TaskContainer.Id, Config.ServerConfig.PATHFORTASKCOMPLETE(), and TaskCompleted().
OpenEditor()
void PlayerTask.OpenEditor () inline
Definition at line 64 of file PlayerTask.cs.
     {
         taskOpenPanelController.OpenUp(this.TaskContainer);
     }
References TaskOpenPanelController.OpenUp(), and taskOpenPanelController.
TaskCompleted()
void PlayerTask.TaskCompleted (Thesis_backend.Data_Structures.PlayerTask result) inline private
Definition at line 69 of file PlayerTask.cs.
     {
         CompleteStateChange(true);
     }
References CompleteStateChange().
Referenced by CompleteTask().
UpdateLabels()
void PlayerTask.UpdateLabels () inline
Definition at line 74 of file PlayerTask.cs.
     {
         TaskNameLabel.text = TaskContainer.TaskName;
         TaskIntervalsLabel.text = TaskContainer.TaskInterval.ToString();
         UpdateTimeRemaining();
     }
References TaskContainer.TaskInterval, TaskIntervalsLabel, TaskContainer.TaskName, TaskNameLabel, and UpdateTimeRemaining().
Referenced by InitValues().
CompleteStateChange()
void PlayerTask.CompleteStateChange (bool state) inline private
Definition at line 81 of file PlayerTask.cs.
     {
         RemainingTimeLabel.gameObject.SetActive(state);
         if (state)
         {
             this.TaskContainer.Complete();
             CompleteButton.GetComponent<Image>().color = DISABLED_FOR_COMPLETE_COLOR;
             UpdateTimeRemaining();
         }
         else
         {
             this.TaskContainer.ResetComplete();
             CompleteButton.GetComponent<Image>().color = AVAILIBLE_FOR_COMPLETE_COLOR;
             return;
         }
     }
References AVAILIBLE_FOR_COMPLETE_COLOR, TaskContainer.Complete(), CompleteButton, DISABLED_FOR_COMPLETE_COLOR, RemainingTimeLabel, TaskContainer.ResetComplete(), and UpdateTimeRemaining().
Referenced by InitValues(), TaskCompleted(), and UpdateTimeRemaining().
UpdateTimeRemaining()
void PlayerTask.UpdateTimeRemaining () inline private
Definition at line 98 of file PlayerTask.cs.
     {
         if (TaskContainer.Completed)
         {
             TimeSpan difference = TimeSpan.FromMinutes((int)TaskContainer.TaskInterval) - (DateTime.Now - TaskContainer.LastCompleted);
             if (difference.TotalMinutes <= 0)
             {
                 CompleteStateChange(false);
                 return;
             }
             string formatted = string.Format("{0} days {1:D2}:{2:D2}:{3:D2}",
             (int)difference.TotalDays, difference.Hours, difference.Minutes, difference.Seconds);
             RemainingTimeLabel.text = formatted;
         }
     }
References TaskContainer.Completed, CompleteStateChange(), TaskContainer.LastCompleted, RemainingTimeLabel, and TaskContainer.TaskInterval.
Referenced by CompleteStateChange(), Update(), and UpdateLabels().
CalculateIfCompleteable()
bool PlayerTask.CalculateIfCompleteable () inline private
Definition at line 117 of file PlayerTask.cs.
     {
         TimeSpan difference = TimeSpan.FromMinutes((int)TaskContainer.TaskInterval) - (DateTime.Now - TaskContainer.LastCompleted);
         return difference.TotalMinutes <= 0;
     }
References TaskContainer.LastCompleted, and TaskContainer.TaskInterval.
Referenced by InitValues().
Member Data Documentation
AVAILIBLE_FOR_COMPLETE_COLOR
Color PlayerTask.AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f) static private
Definition at line 14 of file PlayerTask.cs.
Referenced by CompleteStateChange().
DISABLED_FOR_COMPLETE_COLOR
Color PlayerTask.DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f) static private
Definition at line 15 of file PlayerTask.cs.
Referenced by CompleteStateChange().
TaskNameLabel
TMP_Text PlayerTask.TaskNameLabel private
Definition at line 18 of file PlayerTask.cs.
Referenced by UpdateLabels().
TaskIntervalsLabel
TMP_Text PlayerTask.TaskIntervalsLabel private
Definition at line 21 of file PlayerTask.cs.
Referenced by UpdateLabels().
RemainingTimeLabel
TMP_Text PlayerTask.RemainingTimeLabel private
Definition at line 24 of file PlayerTask.cs.
Referenced by CompleteStateChange(), and UpdateTimeRemaining().
CompleteButton
Button PlayerTask.CompleteButton private
Definition at line 27 of file PlayerTask.cs.
Referenced by CompleteStateChange().
taskOpenPanelController
TaskOpenPanelController PlayerTask.taskOpenPanelController private
Definition at line 29 of file PlayerTask.cs.
Referenced by InitValues(), and OpenEditor().
Property Documentation
TaskContainer
TaskContainer PlayerTask.TaskContainer get private set
Definition at line 31 of file PlayerTask.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
Assets/Scripts/Client/DataTypes/PlayerTask.cs