Bomberman: LoggedInChecker Class Reference
LoggedInChecker Class Reference
Private Member Functions
void Awake ()
IEnumerator CheckLoggedInPeriodically ()
void LoggedOut (string reason)
IEnumerator MoveToLoginScene ()
void LoggedIn (Thesis_backend.Data_Structures.User result)
When the login request's was responded log the user in.
Detailed Description
Definition at line 9 of file LoggedInChecker.cs.
Member Function Documentation
Awake()
void LoggedInChecker.Awake () inline private
Definition at line 12 of file LoggedInChecker.cs.
    {
        StartCoroutine(CheckLoggedInPeriodically());
    }
References CheckLoggedInPeriodically().
CheckLoggedInPeriodically()
IEnumerator LoggedInChecker.CheckLoggedInPeriodically () inline private
Definition at line 17 of file LoggedInChecker.cs.
    {
        while (true)
        {
            // Send the API request
            yield return CoroutineRunner.RunCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORCHECKLOGGEDIN, LoggedIn, onFailedAction: LoggedOut));
            // Wait for 60 seconds before sending the next request
            yield return new WaitForSeconds(60f);
        }
    }
References LoggedIn(), LoggedOut(), Config.ServerConfig.PATHFORCHECKLOGGEDIN, and CoroutineRunner.RunCoroutine().
Referenced by Awake().
LoggedOut()
void LoggedInChecker.LoggedOut (string reason) inline private
Definition at line 29 of file LoggedInChecker.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
    }
Referenced by CheckLoggedInPeriodically().
MoveToLoginScene()
IEnumerator LoggedInChecker.MoveToLoginScene () inline private
Definition at line 34 of file LoggedInChecker.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
        while (true)
        {
            Debug.Log(loading.progress);
            yield return null;
        }
    }
LoggedIn()
void LoggedInChecker.LoggedIn (Thesis_backend::Data_Structures::User result) inline private
When the login request's was responded log the user in.
Parameters
result The server's response
Definition at line 50 of file LoggedInChecker.cs.
    {
        UserData.Instance.Init(result);
    }
References User.UserData.Init(), and User.UserData.Instance.
Referenced by CheckLoggedInPeriodically().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/User/LoggedInChecker.cs