Thesis: MainPage.MainWindowController Class Reference
MainPage.MainWindowController Class Reference
Handles the main window's controls
Public Member Functions
void UpdateUserData (Thesis_backend.Data_Structures.User user)
Update the user with the updated value
void RemoveTask (long taskId)
Remove the task with the given id
void UpdateTaskLabel (long taskId)
Update the task prebab's label
void SortingChanged ()
Refreshes the tasks with the proper sorting order
void LoadGoodTasks (bool updateDisplay=true)
Load the good tasks
void LoadBadHabits (bool updateDisplay=true)
Load the good habits
GameObject CreateTask (PlayerTask taskContainer)
Creates a new task prefab to display
void ShowTaskFail (string content)
Show the task request fail in the modal window
void LoadGameScene ()
Loads the game scene
Properties
Dictionary< long, TaskDisplayHandler > Tasks = new Dictionary<long, TaskDisplayHandler>() [get, private set]
Currently loaded tasks
TaskSortType TaskSortType [get]
Currently what are the task being sorted by
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
async void Start ()
Start is called before the first frame update
void LoadTasks ()
Load the tasks from the server
void ShowRequestFail (string content)
Show the server request fail in the modal window
void CreateTaskPrefabs (List< Thesis_backend.Data_Structures.PlayerTask > requestResult)
Create the task prefabs
Private Attributes
TMP_Text usernameText
Text to display the username of the currently logged in user
TMP_Text currentTaskScoreText
Text to display the current task score of the player
GameObject taskParent
Container to load the tasks into
GameObject taskPrefab
Task prefab to load for each task
TaskOpenPanelController taskOpenPanelController
Task open panel for task edit and new task creation
ModalWindow modalWindow
Modal window for api fail feedback
TMP_Dropdown taskSortDropdown
Task sort type dropdown
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Handles the main window's controls
Definition at line 18 of file MainWindowController.cs.
Member Function Documentation
Start()
async void MainPage.MainWindowController.Start () inline private
Start is called before the first frame update
Definition at line 75 of file MainWindowController.cs.
         {
             //Wait for the user to be logged in
             while (!UserData.Instance.LoggedIn)
             {
                 await Task.Delay(100);
             }
             usernameText.text = UserData.Instance.Username;
             currentTaskScoreText.text = UserData.Instance.CurrentTaskScore.ToString();
             LoadTasks();
         }
References User.UserData.CurrentTaskScore, MainPage.MainWindowController.currentTaskScoreText, User.UserData.Instance, MainPage.MainWindowController.LoadTasks(), User.UserData.LoggedIn, User.UserData.Username, and MainPage.MainWindowController.usernameText.
UpdateUserData()
void MainPage.MainWindowController.UpdateUserData (Thesis_backend.Data_Structures.User user) inline
Update the user with the updated value
Parameters
user User data recieved from the server
Definition at line 91 of file MainWindowController.cs.
         {
             UserData.Instance.Init(user);
             currentTaskScoreText.text = UserData.Instance.CurrentTaskScore.ToString();
         }
References User.UserData.CurrentTaskScore, MainPage.MainWindowController.currentTaskScoreText, User.UserData.Init(), and User.UserData.Instance.
RemoveTask()
void MainPage.MainWindowController.RemoveTask (long taskId) inline
Remove the task with the given id
Parameters
taskId Task id to remove
Definition at line 101 of file MainWindowController.cs.
         {
             //Making sure that there is such task id
             if (Tasks.ContainsKey(taskId))
             {
                 TaskDisplayHandler TaskToRemove = Tasks[taskId];
                 Tasks.Remove(taskId);
                 Destroy(TaskToRemove.gameObject);
             }
         }
References MainPage.MainWindowController.Tasks.
Referenced by MainPage.TaskOpenPanelController.DeletedTask().
UpdateTaskLabel()
void MainPage.MainWindowController.UpdateTaskLabel (long taskId) inline
Update the task prebab's label
Parameters
taskId The id of the task to change
Definition at line 116 of file MainWindowController.cs.
         {
             //Making sure that there is such task id
             if (Tasks.ContainsKey(taskId))
             {
                 Tasks[taskId].UpdateLabels();
             }
         }
References MainPage.MainWindowController.Tasks.
Referenced by MainPage.TaskOpenPanelController.SavedTask().
SortingChanged()
void MainPage.MainWindowController.SortingChanged () inline
Refreshes the tasks with the proper sorting order
Definition at line 128 of file MainWindowController.cs.
         {
             //Create a temporary dictionary which will store the sorted values
             Dictionary<long, TaskDisplayHandler> newTasks = new Dictionary<long, TaskDisplayHandler>();
             //Reorder the tasks with the appropriate sorting predicate
             switch ((TaskSortType)taskSortDropdown.value)
             {
                 case TaskSortType.Added:
                     foreach (var item in Tasks.OrderBy(x => x.Key))
                     {
                         newTasks.Add(item.Key, item.Value);
                     }
                     break;
                 case TaskSortType.Name:
                     foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.TaskName))
                     {
                         newTasks.Add(item.Key, item.Value);
                     }
                     break;
                 case TaskSortType.Type:
                     foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.PeriodRate))
                     {
                         newTasks.Add(item.Key, item.Value);
                     }
                     break;
                 case TaskSortType.Available:
                     foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.Completed))
                     {
                         newTasks.Add(item.Key, item.Value);
                     }
                     break;
                 default:
                     Debug.LogError("No such sorting way is configured");
                     break;
             }
             //Override the previous order
             Tasks = newTasks;
             //Reload the tasks
             if (taskOpenPanelController.CurrentTask.TaskType)
             {
                 LoadBadHabits();
             }
             else
             {
                 LoadGoodTasks();
             }
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.MainWindowController.LoadBadHabits(), MainPage.MainWindowController.LoadGoodTasks(), MainPage.MainWindowController.taskOpenPanelController, MainPage.MainWindowController.Tasks, and MainPage.MainWindowController.taskSortDropdown.
Referenced by MainPage.TaskDisplayHandler.CompleteStateChange(), and MainPage.TaskOpenPanelController.SavedTask().
LoadGoodTasks()
void MainPage.MainWindowController.LoadGoodTasks (bool updateDisplay = true) inline
Load the good tasks
Parameters
updateDisplay Should it also update the display (make the open panel display good task)
Definition at line 184 of file MainWindowController.cs.
         {
             //Protect from errors during testing
             try
             {
                 //Iterate the tasks
                 foreach (var task in Tasks)
                 {
                     //Enable the good tasks and disable the bad ones
                     if (!task.Value.CurrentTask.TaskType)
                     {
                         task.Value.gameObject.SetActive(true);
                         task.Value.gameObject.transform.SetAsLastSibling();
                     }
                     else
                     {
                         task.Value.gameObject.SetActive(false);
                     }
                 }
                 taskParent.GetComponentInChildren<TMP_Text>().text = "Good tasks";
                 if (updateDisplay)
                     taskOpenPanelController.MakeItGoodTask();
             }
             catch (MissingReferenceException)
             {
             }
         }
References MainPage.TaskOpenPanelController.MakeItGoodTask(), MainPage.MainWindowController.taskOpenPanelController, MainPage.MainWindowController.taskParent, and MainPage.MainWindowController.Tasks.
Referenced by MainPage.TaskOpenPanelController.Cancel(), MainPage.MainWindowController.CreateTaskPrefabs(), MainPage.TaskOpenPanelController.MakeItGoodTask(), and MainPage.MainWindowController.SortingChanged().
LoadBadHabits()
void MainPage.MainWindowController.LoadBadHabits (bool updateDisplay = true) inline
Load the good habits
Parameters
updateDisplay Should it also update the display (make the open panel display bad habit)
Definition at line 216 of file MainWindowController.cs.
         {
             //Protect from errors during testing
             try
             {
                 //Enable the bad habits and disable the good ones
                 foreach (var task in Tasks)
                 {
                     if (task.Value.CurrentTask.TaskType)
                     {
                         task.Value.gameObject.SetActive(true);
                         task.Value.gameObject.transform.SetAsLastSibling();
                     }
                     else
                     {
                         task.Value.gameObject.SetActive(false);
                     }
                 }
                 taskParent.GetComponentInChildren<TMP_Text>().text = "Bad habits";
                 if (updateDisplay)
                     taskOpenPanelController.MakeItBadHabit();
             }
             catch (MissingReferenceException)
             {
             }
         }
References MainPage.TaskOpenPanelController.MakeItBadHabit(), MainPage.MainWindowController.taskOpenPanelController, MainPage.MainWindowController.taskParent, and MainPage.MainWindowController.Tasks.
Referenced by MainPage.TaskOpenPanelController.Cancel(), MainPage.TaskOpenPanelController.MakeItBadHabit(), and MainPage.MainWindowController.SortingChanged().
CreateTask()
GameObject MainPage.MainWindowController.CreateTask (PlayerTask taskContainer) inline
Creates a new task prefab to display
Parameters
taskContainer The task to display
Returns
The created gameobject
Definition at line 248 of file MainWindowController.cs.
         {
             //Protect from errors during testing
             try
             {
                 GameObject task = Instantiate(taskPrefab, taskParent.transform);
                 TaskDisplayHandler taskComponent = task.GetComponent<TaskDisplayHandler>();
                 taskComponent.InitValues(taskContainer, taskOpenPanelController, this);
                 Tasks.Add(taskContainer.ID, taskComponent);
                 return task;
             }
             catch (MissingReferenceException)
             {
                 Debug.LogWarning("Task create missing reference");
                 return null;
             }
         }
References MainPage.TaskDisplayHandler.InitValues(), MainPage.MainWindowController.taskOpenPanelController, MainPage.MainWindowController.taskParent, MainPage.MainWindowController.taskPrefab, and MainPage.MainWindowController.Tasks.
Referenced by MainPage.MainWindowController.CreateTaskPrefabs(), and MainPage.TaskOpenPanelController.SavedTask().
LoadTasks()
void MainPage.MainWindowController.LoadTasks () inline private
Load the tasks from the server
Definition at line 269 of file MainWindowController.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<Thesis_backend.Data_Structures.PlayerTask>>(ServerConfig.PATHFORTASKSQUERY, CreateTaskPrefabs, onFailedAction: ShowRequestFail));
         }
References MainPage.MainWindowController.CreateTaskPrefabs(), Config.ServerConfig.PATHFORTASKSQUERY, Utility.CoroutineRunner.RunCoroutine(), and MainPage.MainWindowController.ShowRequestFail().
Referenced by MainPage.MainWindowController.Start().
ShowRequestFail()
void MainPage.MainWindowController.ShowRequestFail (string content) inline private
Show the server request fail in the modal window
Parameters
content The server response
Definition at line 278 of file MainWindowController.cs.
         {
             modalWindow.Show("Request fail", content);
         }
References MainPage.MainWindowController.modalWindow, and Utility.ModalWindow.Show().
Referenced by MainPage.MainWindowController.LoadTasks().
ShowTaskFail()
void MainPage.MainWindowController.ShowTaskFail (string content) inline
Show the task request fail in the modal window
Parameters
content The server response
Definition at line 287 of file MainWindowController.cs.
         {
             modalWindow.Show("Task error", content);
         }
References MainPage.MainWindowController.modalWindow, and Utility.ModalWindow.Show().
Referenced by MainPage.TaskDisplayHandler.CompleteTask(), MainPage.TaskOpenPanelController.DeleteTask(), MainPage.TaskOpenPanelController.Save(), and MainPage.TaskDisplayHandler.TaskCompleted().
LoadGameScene()
void MainPage.MainWindowController.LoadGameScene () inline
Loads the game scene
Definition at line 295 of file MainWindowController.cs.
         {
             SceneManager.LoadScene("GameScene", LoadSceneMode.Single);
         }
CreateTaskPrefabs()
void MainPage.MainWindowController.CreateTaskPrefabs (List< Thesis_backend.Data_Structures.PlayerTask > requestResult) inline private
Create the task prefabs
Parameters
requestResult Collection of tasks from the server
Definition at line 304 of file MainWindowController.cs.
         {
             foreach (var item in requestResult)
             {
                 CreateTask(item);
             }
             LoadGoodTasks();
         }
References MainPage.MainWindowController.CreateTask(), and MainPage.MainWindowController.LoadGoodTasks().
Referenced by MainPage.MainWindowController.LoadTasks().
Member Data Documentation
usernameText
TMP_Text MainPage.MainWindowController.usernameText private
Text to display the username of the currently logged in user
Definition at line 24 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.Start().
currentTaskScoreText
TMP_Text MainPage.MainWindowController.currentTaskScoreText private
Text to display the current task score of the player
Definition at line 30 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.Start(), and MainPage.MainWindowController.UpdateUserData().
taskParent
GameObject MainPage.MainWindowController.taskParent private
Container to load the tasks into
Definition at line 36 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.CreateTask(), MainPage.MainWindowController.LoadBadHabits(), and MainPage.MainWindowController.LoadGoodTasks().
taskPrefab
GameObject MainPage.MainWindowController.taskPrefab private
Task prefab to load for each task
Definition at line 42 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.CreateTask().
taskOpenPanelController
TaskOpenPanelController MainPage.MainWindowController.taskOpenPanelController private
Task open panel for task edit and new task creation
Definition at line 48 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.CreateTask(), MainPage.MainWindowController.LoadBadHabits(), MainPage.MainWindowController.LoadGoodTasks(), and MainPage.MainWindowController.SortingChanged().
modalWindow
ModalWindow MainPage.MainWindowController.modalWindow private
Modal window for api fail feedback
Definition at line 54 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.ShowRequestFail(), and MainPage.MainWindowController.ShowTaskFail().
taskSortDropdown
TMP_Dropdown MainPage.MainWindowController.taskSortDropdown private
Task sort type dropdown
Definition at line 60 of file MainWindowController.cs.
Referenced by MainPage.MainWindowController.SortingChanged().
Property Documentation
Tasks
Dictionary<long, TaskDisplayHandler> MainPage.MainWindowController.Tasks = new Dictionary<long, TaskDisplayHandler>() get private set
Currently loaded tasks
Definition at line 65 of file MainWindowController.cs.
 { get; private set; } = new Dictionary<long, TaskDisplayHandler>();
Referenced by MainPage.MainWindowController.CreateTask(), MainPage.MainWindowController.LoadBadHabits(), MainPage.MainWindowController.LoadGoodTasks(), MainPage.MainWindowController.RemoveTask(), MainPage.MainWindowController.SortingChanged(), and MainPage.MainWindowController.UpdateTaskLabel().
TaskSortType
TaskSortType MainPage.MainWindowController.TaskSortType get
Currently what are the task being sorted by
Definition at line 70 of file MainWindowController.cs.
Referenced by MainPage.TaskDisplayHandler.CompleteStateChange().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/MainWindowController.cs