Bomberman: Task Class Reference
Task Class Reference
Public Member Functions
void Update ()
void InitValues (TaskContainer taskContainer, TaskOpenPanelController taskOpenPanelController)
void CompleteTask ()
void OpenEditor ()
void UpdateLabels ()
Properties
TaskContainer TaskContainer [get, private set]
Private Member Functions
void TaskCompleted (Dictionary< string, string > result)
void CompleteStateChange (bool state)
void UpdateTimeRemaining ()
bool CalculateIfCompleteable ()
Private Attributes
TMP_Text TaskNameLabel
TMP_Text TaskIntervalsLabel
TMP_Text RemainingTimeLabel
Button CompleteButton
TaskOpenPanelController taskOpenPanelController
Static Private Attributes
static Color AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f)
static Color DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f)
Detailed Description
Definition at line 12 of file Task.cs.
Member Function Documentation
Update()
void Task.Update () inline
Definition at line 33 of file Task.cs.
     {
         if (TaskContainer.Completed)
         {
             UpdateTimeRemaining();
         }
     }
References TaskContainer.Completed, and UpdateTimeRemaining().
InitValues()
void Task.InitValues (TaskContainer taskContainer, TaskOpenPanelController taskOpenPanelController) inline
Definition at line 41 of file Task.cs.
     {
         this.TaskContainer = taskContainer;
         if (!CalculateIfCompleteable())
         {
             CompleteStateChange(true);
         }
         this.taskOpenPanelController = taskOpenPanelController;
         UpdateLabels();
     }
References CalculateIfCompleteable(), CompleteStateChange(), taskOpenPanelController, and UpdateLabels().
Referenced by UIController.CreateTask().
CompleteTask()
void Task.CompleteTask () inline
Definition at line 54 of file Task.cs.
     {
         if (!TaskContainer.Completed)
         {
             WWWForm form = new WWWForm();
             form.AddField("id", TaskContainer.Id);
             StartCoroutine(Server.SendRequest<Dictionary<string, string>>(ServerConfig.PATHFORTASKCOMPLETE, form, TaskCompleted));
         }
     }
References TaskContainer.Completed, TaskContainer.Id, Config.ServerConfig.PATHFORTASKCOMPLETE, and TaskCompleted().
OpenEditor()
void Task.OpenEditor () inline
Definition at line 64 of file Task.cs.
     {
         taskOpenPanelController.OpenUp(this.TaskContainer);
     }
References TaskOpenPanelController.OpenUp(), and taskOpenPanelController.
TaskCompleted()
void Task.TaskCompleted (Dictionary< string, string > result) inline private
Definition at line 69 of file Task.cs.
     {
         if (result["res"] == "success")
         {
             CompleteStateChange(true);
         }
         else
         {
             Debug.Log("Can't complete task");
         }
     }
References CompleteStateChange().
Referenced by CompleteTask().
UpdateLabels()
void Task.UpdateLabels () inline
Definition at line 81 of file Task.cs.
     {
         TaskNameLabel.text = TaskContainer.TaskName;
         TaskIntervalsLabel.text = TaskContainer.TaskInterval.ToString();
         UpdateTimeRemaining();
     }
References TaskContainer.TaskInterval, TaskIntervalsLabel, TaskContainer.TaskName, TaskNameLabel, and UpdateTimeRemaining().
Referenced by InitValues().
CompleteStateChange()
void Task.CompleteStateChange (bool state) inline private
Definition at line 88 of file Task.cs.
     {
         RemainingTimeLabel.gameObject.SetActive(state);
         if (state)
         {
             this.TaskContainer.Complete();
             CompleteButton.GetComponent<Image>().color = DISABLED_FOR_COMPLETE_COLOR;
             UpdateTimeRemaining();
         }
         else
         {
             this.TaskContainer.ResetComplete();
             CompleteButton.GetComponent<Image>().color = AVAILIBLE_FOR_COMPLETE_COLOR;
             return;
         }
     }
References AVAILIBLE_FOR_COMPLETE_COLOR, TaskContainer.Complete(), CompleteButton, DISABLED_FOR_COMPLETE_COLOR, RemainingTimeLabel, TaskContainer.ResetComplete(), and UpdateTimeRemaining().
Referenced by InitValues(), TaskCompleted(), and UpdateTimeRemaining().
UpdateTimeRemaining()
void Task.UpdateTimeRemaining () inline private
Definition at line 105 of file Task.cs.
     {
         if (TaskContainer.Completed)
         {
             TimeSpan difference = TimeSpan.FromMinutes((int)TaskContainer.TaskInterval) - (DateTime.Now - TaskContainer.LastCompleted);
             if (difference.TotalMinutes <= 0)
             {
                 CompleteStateChange(false);
                 return;
             }
             string formatted = string.Format("{0} days {1:D2}:{2:D2}:{3:D2}",
             (int)difference.TotalDays, difference.Hours, difference.Minutes, difference.Seconds);
             RemainingTimeLabel.text = formatted;
         }
     }
References TaskContainer.Completed, CompleteStateChange(), TaskContainer.LastCompleted, RemainingTimeLabel, and TaskContainer.TaskInterval.
Referenced by CompleteStateChange(), Update(), and UpdateLabels().
CalculateIfCompleteable()
bool Task.CalculateIfCompleteable () inline private
Definition at line 124 of file Task.cs.
     {
         TimeSpan difference = TimeSpan.FromMinutes((int)TaskContainer.TaskInterval) - (DateTime.Now - TaskContainer.LastCompleted);
         return difference.TotalMinutes <= 0;
     }
References TaskContainer.LastCompleted, and TaskContainer.TaskInterval.
Referenced by InitValues().
Member Data Documentation
AVAILIBLE_FOR_COMPLETE_COLOR
Color Task.AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f) static private
Definition at line 14 of file Task.cs.
Referenced by CompleteStateChange().
DISABLED_FOR_COMPLETE_COLOR
Color Task.DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f) static private
Definition at line 15 of file Task.cs.
Referenced by CompleteStateChange().
TaskNameLabel
TMP_Text Task.TaskNameLabel private
Definition at line 18 of file Task.cs.
Referenced by UpdateLabels().
TaskIntervalsLabel
TMP_Text Task.TaskIntervalsLabel private
Definition at line 21 of file Task.cs.
Referenced by UpdateLabels().
RemainingTimeLabel
TMP_Text Task.RemainingTimeLabel private
Definition at line 24 of file Task.cs.
Referenced by CompleteStateChange(), and UpdateTimeRemaining().
CompleteButton
Button Task.CompleteButton private
Definition at line 27 of file Task.cs.
Referenced by CompleteStateChange().
taskOpenPanelController
TaskOpenPanelController Task.taskOpenPanelController private
Definition at line 29 of file Task.cs.
Referenced by InitValues(), and OpenEditor().
Property Documentation
TaskContainer
TaskContainer Task.TaskContainer get private set
Definition at line 31 of file Task.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
Assets/Scripts/Client/DataTypes/Task.cs