Bomberman: UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput Class Reference
UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput Class Reference
Public Member Functions
override float GetAxis (string name, bool raw)
override void SetButtonDown (string name)
override void SetButtonUp (string name)
override void SetAxisPositive (string name)
override void SetAxisNegative (string name)
override void SetAxisZero (string name)
override void SetAxis (string name, float value)
override bool GetButtonDown (string name)
override bool GetButtonUp (string name)
override bool GetButton (string name)
override Vector3 MousePosition ()
Public Member Functions inherited from UnityStandardAssets.CrossPlatformInput.VirtualInput
bool AxisExists (string name)
bool ButtonExists (string name)
void RegisterVirtualAxis (CrossPlatformInputManager.VirtualAxis axis)
void RegisterVirtualButton (CrossPlatformInputManager.VirtualButton button)
void UnRegisterVirtualAxis (string name)
void UnRegisterVirtualButton (string name)
CrossPlatformInputManager.VirtualAxis VirtualAxisReference (string name)
void SetVirtualMousePositionX (float f)
void SetVirtualMousePositionY (float f)
void SetVirtualMousePositionZ (float f)
Private Member Functions
void AddButton (string name)
void AddAxes (string name)
Additional Inherited Members
Protected Attributes inherited from UnityStandardAssets.CrossPlatformInput.VirtualInput
Dictionary< string, CrossPlatformInputManager.VirtualAxis > m_VirtualAxes
Dictionary< string, CrossPlatformInputManager.VirtualButton > m_VirtualButtons
List< string > m_AlwaysUseVirtual = new List<string>()
Properties inherited from UnityStandardAssets.CrossPlatformInput.VirtualInput
Vector3 virtualMousePosition [get, private set]
Detailed Description
Definition at line 6 of file MobileInput.cs.
Member Function Documentation
AddButton()
void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton (string name) inline private
Definition at line 8 of file MobileInput.cs.
         {
             // we have not registered this button yet so add it, happens in the constructor
             CrossPlatformInputManager.RegisterVirtualButton(new CrossPlatformInputManager.VirtualButton(name));
         }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualButton().
Referenced by UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButton(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonDown(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonUp(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonDown(), and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonUp().
AddAxes()
void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes (string name) inline private
Definition at line 15 of file MobileInput.cs.
         {
             // we have not registered this button yet so add it, happens in the constructor
             CrossPlatformInputManager.RegisterVirtualAxis(new CrossPlatformInputManager.VirtualAxis(name));
         }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis().
Referenced by UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetAxis(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxis(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisNegative(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisPositive(), and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisZero().
GetAxis()
override float UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetAxis (string name, bool raw) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 22 of file MobileInput.cs.
         {
             if (!m_VirtualAxes.ContainsKey(name))
             {
                 AddAxes(name);
             }
             return m_VirtualAxes[name].GetValue;
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
SetButtonDown()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonDown (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 32 of file MobileInput.cs.
         {
             if (!m_VirtualButtons.ContainsKey(name))
             {
                 AddButton(name);
             }
             m_VirtualButtons[name].Pressed();
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
SetButtonUp()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonUp (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 42 of file MobileInput.cs.
         {
             if (!m_VirtualButtons.ContainsKey(name))
             {
                 AddButton(name);
             }
             m_VirtualButtons[name].Released();
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
SetAxisPositive()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisPositive (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 52 of file MobileInput.cs.
         {
             if (!m_VirtualAxes.ContainsKey(name))
             {
                 AddAxes(name);
             }
             m_VirtualAxes[name].Update(1f);
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
SetAxisNegative()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisNegative (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 62 of file MobileInput.cs.
         {
             if (!m_VirtualAxes.ContainsKey(name))
             {
                 AddAxes(name);
             }
             m_VirtualAxes[name].Update(-1f);
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
SetAxisZero()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisZero (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 72 of file MobileInput.cs.
         {
             if (!m_VirtualAxes.ContainsKey(name))
             {
                 AddAxes(name);
             }
             m_VirtualAxes[name].Update(0f);
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
SetAxis()
override void UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxis (string name, float value) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 82 of file MobileInput.cs.
         {
             if (!m_VirtualAxes.ContainsKey(name))
             {
                 AddAxes(name);
             }
             m_VirtualAxes[name].Update(value);
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
GetButtonDown()
override bool UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonDown (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 92 of file MobileInput.cs.
         {
             if (m_VirtualButtons.ContainsKey(name))
             {
                 return m_VirtualButtons[name].GetButtonDown;
             }
             AddButton(name);
             return m_VirtualButtons[name].GetButtonDown;
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
GetButtonUp()
override bool UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonUp (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 104 of file MobileInput.cs.
         {
             if (m_VirtualButtons.ContainsKey(name))
             {
                 return m_VirtualButtons[name].GetButtonUp;
             }
             AddButton(name);
             return m_VirtualButtons[name].GetButtonUp;
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
GetButton()
override bool UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButton (string name) inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 116 of file MobileInput.cs.
         {
             if (m_VirtualButtons.ContainsKey(name))
             {
                 return m_VirtualButtons[name].GetButton;
             }
             AddButton(name);
             return m_VirtualButtons[name].GetButton;
         }
References UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
MousePosition()
override Vector3 UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.MousePosition () inline virtual
Implements UnityStandardAssets.CrossPlatformInput.VirtualInput.
Definition at line 128 of file MobileInput.cs.
         {
             return virtualMousePosition;
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.virtualMousePosition.
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/PlatformSpecific/MobileInput.cs