Thesis: Game.World.GameWorld Class Reference
Game.World.GameWorld Class Reference
A class for handling chunk loading and unloading.
Public Member Functions
Chunk GetChunk (Vector3 GameObjectPos)
Gets the chunk based on the absolute position which chunk it would fall into.
async Task CreateNewGame ()
Creates a new game and create the chunks.
async Task LoadChunk (int x, int z)
Loads a chunk.
void HideChunk (int col, int row)
Hide the given chunk.
Chunk GetChunkWithoutLoad (int col, int row)
Get the chunk without trying it to load.
async Task< Chunk > GetChunk (int col, int row)
Gets the chunk it will load it if it hasn't been and hide it then otherwise just return it.
Private Attributes
GameObject ChunkPrefab
Chunk prefab for the chunk creation.
Chunk[,] Chunks
The chunks of the world.
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed.
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed.
Detailed Description
A class for handling chunk loading and unloading.
Definition at line 15 of file GameWorld.cs.
Member Function Documentation
GetChunk() [1/2]
Chunk Game.World.GameWorld.GetChunk (Vector3 GameObjectPos) inline
Gets the chunk based on the absolute position which chunk it would fall into.
Parameters
GameObjectPos The postion we're looking up
Returns
The chunk or null if not found
Definition at line 33 of file GameWorld.cs.
            {
                int row = (int)(GameObjectPos.z / (GameConfig.CHUNK_SIZE * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL));
                int col = (int)(GameObjectPos.x / (GameConfig.CHUNK_SIZE * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL));
                if (row < 0 || col < 0 || row >= GameConfig.CHUNK_COUNT || col >= GameConfig.CHUNK_COUNT)
                {
                    return null;
                }
                return Chunks[row, col];
            }
References Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_COUNT, Game.GameConfig.CHUNK_SCALE, Game.GameConfig.CHUNK_SIZE, and Game.World.GameWorld.Chunks.
Referenced by Game.Car.ChangeChunkIfNeeded(), and Game.GameController.NewGame().
CreateNewGame()
async Task Game.World.GameWorld.CreateNewGame () inline
Creates a new game and create the chunks.
Definition at line 47 of file GameWorld.cs.
            {
                //Delete the previous chunks
                if (Chunks is not null)
                {
                    for (int i = 0; i < Chunks.GetLength(0); i++)
                    {
                        for (int j = 0; j < Chunks.GetLength(1); j++)
{
                            if (Chunks[i, j] != null)
{
                                Destroy(Chunks[i, j].gameObject);
                                Chunks[i, j] = null;
                            }
                        }
                    }
                }
                //Create the chunks
                Chunks = new Chunk[GameConfig.CHUNK_COUNT, GameConfig.CHUNK_COUNT];
                //Load the initial chunk
                await LoadChunk(GameConfig.CHUNK_COUNT / 2, GameConfig.CHUNK_COUNT / 2);
            }
References Game.GameConfig.CHUNK_COUNT, Game.World.GameWorld.Chunks, and Game.World.GameWorld.LoadChunk().
Referenced by Game.GameController.NewGame().
LoadChunk()
async Task Game.World.GameWorld.LoadChunk (int x, int z) inline
Loads a chunk.
Parameters
x The x index of the chunk (horizontal)
z The z index of the chunk (vertical)
Definition at line 75 of file GameWorld.cs.
            {
                if (Chunks[z, x] == null)
                {
                    //Destroyed check
                    if (Destroyed)
                    {
                        return;
                    }
                    //Instantiate the prefab
                    Chunks[z, x] = Instantiate(ChunkPrefab, this.transform, true).GetComponent<Chunk>();
                    //Get the road edges for the road generation
                    List<EdgeRoadContainer> edges = new List<EdgeRoadContainer>();
                    if (z - 1 >= 0 && Chunks[z - 1, x] != null)
                    {
                        if (Chunks[z - 1, x].EdgeRoads is null)
{
                            return;
                        }
                        edges.AddRange(Chunks[z - 1, x].EdgeRoads.Where(x => x?.EdgeRoad.y == GameConfig.CHUNK_SIZE - 1));
                    }
                    if (z + 1 < GameConfig.CHUNK_COUNT && Chunks[z + 1, x] != null)
                    {
                        if (Chunks[z + 1, x].EdgeRoads is null)
{
                            return;
                        }
                        edges.AddRange(Chunks[z + 1, x].EdgeRoads.Where(x => x?.EdgeRoad.y == 0));
                    }
                    if (x - 1 >= 0 && Chunks[z, x - 1] != null)
                    {
                        if (Chunks[z, x - 1].EdgeRoads is null)
{
                            return;
                        }
                        edges.AddRange(Chunks[z, x - 1].EdgeRoads.Where(x => x?.EdgeRoad.x == GameConfig.CHUNK_SIZE - 1));
                    }
                    if (x + 1 < GameConfig.CHUNK_COUNT && Chunks[z, x + 1] != null)
                    {
                        if (Chunks[z, x + 1].EdgeRoads is null)
{
                            return;
                        }
                        edges.AddRange(Chunks[z, x + 1].EdgeRoads.Where(x => x?.EdgeRoad.x == 0));
                    }
                    //Create the chunk
                    await Chunks[z, x].InitChunk(x, z, edges, this);
                }
                else
                {
                    //If the chunk is already loaded display it
                    Chunks[z, x].Display();
                }
            }
References Game.GameConfig.CHUNK_COUNT, Game.GameConfig.CHUNK_SIZE, Game.World.GameWorld.ChunkPrefab, Game.World.GameWorld.Chunks, Utility.ThreadSafeMonoBehaviour.Destroyed, Game.World.Chunk.Display(), and Game.World.Chunk.InitChunk().
Referenced by Game.World.GameWorld.CreateNewGame(), Game.World.GameWorld.GetChunk(), and Game.GameController.ValidateAndLoadChunk().
HideChunk()
void Game.World.GameWorld.HideChunk (int col, int row) inline
Hide the given chunk.
Parameters
col The chunk's column index
row The row chunk's index
Definition at line 136 of file GameWorld.cs.
            {
                if (Chunks[row, col] is not null)
                {
                    Chunks[row, col].HideChunk();
                }
            }
References Game.World.GameWorld.Chunks, and Game.World.Chunk.HideChunk().
Referenced by Game.GameController.DespawnFarAwayChunks(), and Game.World.GameWorld.GetChunk().
GetChunkWithoutLoad()
Chunk Game.World.GameWorld.GetChunkWithoutLoad (int col, int row) inline
Get the chunk without trying it to load.
Parameters
col The chunk's column index
row The row chunk's index
Returns
The chunk or null if it wasn't loaded yet
Definition at line 150 of file GameWorld.cs.
            {
                return Chunks[row, col];
            }
References Game.World.GameWorld.Chunks.
Referenced by Game.World.Chunk.GetNearbyChunks().
GetChunk() [2/2]
async Task< Chunk > Game.World.GameWorld.GetChunk (int col, int row) inline
Gets the chunk it will load it if it hasn't been and hide it then otherwise just return it.
Parameters
col The chunk's column index
row The row chunk's index
Returns
The chunk
Definition at line 161 of file GameWorld.cs.
            {
                if (Chunks[row, col] is null)
                {
                    await LoadChunk(col, row);
                    HideChunk(col, row);
                }
                return Chunks[row, col];
            }
References Game.World.GameWorld.Chunks, Game.World.GameWorld.HideChunk(), and Game.World.GameWorld.LoadChunk().
Member Data Documentation
ChunkPrefab
GameObject Game.World.GameWorld.ChunkPrefab private
Chunk prefab for the chunk creation.
Definition at line 21 of file GameWorld.cs.
Referenced by Game.World.GameWorld.LoadChunk().
Chunks
Chunk [,] Game.World.GameWorld.Chunks private
The chunks of the world.
Definition at line 26 of file GameWorld.cs.
Referenced by Game.World.GameWorld.CreateNewGame(), Game.World.GameWorld.GetChunk(), Game.World.GameWorld.GetChunk(), Game.World.GameWorld.GetChunkWithoutLoad(), Game.World.GameWorld.HideChunk(), and Game.World.GameWorld.LoadChunk().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World/GameWorld.cs