Bomberman: MainWindowController Class Reference
MainWindowController Class Reference
Public Member Functions
void UpdateUserData (Thesis_backend.Data_Structures.User user)
void RemoveTask (long taskId)
void UpdateTask (long taskId)
void SortingChanged ()
void LoadGoodTasks (bool updateDisplay=true)
void LoadBadHabits (bool updateDisplay=true)
GameObject CreateTask (PlayerTask taskContainer)
void ShowTaskFail (string content)
void LoadGameScene ()
Public Attributes
ModalWindow ModalWindow
Properties
Dictionary< long, TaskDisplayHandler > Tasks = new Dictionary<long, TaskDisplayHandler>() [get, private set]
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Private Member Functions
async void Start ()
void Update ()
void LoadTasks ()
void ShowRequestFail (string content)
void CreateTaskPrefabs (List< Thesis_backend.Data_Structures.PlayerTask > requestResult)
Private Attributes
TMP_Text UsernameInputText
TMP_Text CurrencyText
GameObject TaskParent
GameObject TaskPrefab
TaskOpenPanelController taskOpenPanelController
TMP_Dropdown TaskSortDropdown
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Detailed Description
Definition at line 14 of file MainWindowController.cs.
Member Function Documentation
Start()
async void MainWindowController.Start () inline private
Definition at line 40 of file MainWindowController.cs.
    {
        while (!UserData.Instance.LoggedIn)
        {
            await Task.Delay(100);
        }
        UsernameInputText.text = UserData.Instance.Username;
        CurrencyText.text = UserData.Instance.CurrentTaskScore.ToString();
        LoadTasks();
    }
References User.UserData.CurrentTaskScore, User.UserData.Instance, LoadTasks(), User.UserData.LoggedIn, and User.UserData.Username.
UpdateUserData()
void MainWindowController.UpdateUserData (Thesis_backend::Data_Structures::User user) inline
Definition at line 51 of file MainWindowController.cs.
    {
        UserData.Instance.Init(user);
        CurrencyText.text = UserData.Instance.CurrentTaskScore.ToString();
    }
References User.UserData.CurrentTaskScore, User.UserData.Init(), and User.UserData.Instance.
Update()
void MainWindowController.Update () inline private
Definition at line 58 of file MainWindowController.cs.
    {
    }
RemoveTask()
void MainWindowController.RemoveTask (long taskId) inline
Definition at line 62 of file MainWindowController.cs.
    {
        if (Tasks.ContainsKey(taskId))
        {
            TaskDisplayHandler TaskToRemove = Tasks[taskId];
            Tasks.Remove(taskId);
            Destroy(TaskToRemove.gameObject);
        }
    }
References Tasks.
Referenced by TaskOpenPanelController.DeletedTask().
UpdateTask()
void MainWindowController.UpdateTask (long taskId) inline
Definition at line 72 of file MainWindowController.cs.
    {
        if (Tasks.ContainsKey(taskId))
        {
            Tasks[taskId].UpdateLabels();
        }
    }
References Tasks.
Referenced by TaskOpenPanelController.SavedTask().
SortingChanged()
void MainWindowController.SortingChanged () inline
Definition at line 80 of file MainWindowController.cs.
    {
        Dictionary<long, TaskDisplayHandler> newTasks = new Dictionary<long, TaskDisplayHandler>();
        switch ((TaskSortType)TaskSortDropdown.value)
        {
            case TaskSortType.Added:
                foreach (var item in Tasks.OrderBy(x => x.Key))
                {
                    newTasks.Add(item.Key, item.Value);
                }
                break;
            case TaskSortType.Name:
                foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.TaskName))
                {
                    newTasks.Add(item.Key, item.Value);
                }
                break;
            case TaskSortType.Type:
                foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.PeriodRate))
                {
                    newTasks.Add(item.Key, item.Value);
                }
                break;
            case TaskSortType.Available:
                foreach (var item in Tasks.OrderBy(x => x.Value.CurrentTask.Completed))
                {
                    newTasks.Add(item.Key, item.Value);
                }
                break;
            default:
                Debug.LogError("No such sorting way is configured");
                break;
        }
        Tasks = newTasks;
        if (taskOpenPanelController.CurrentTask.TaskType)
        {
            LoadBadHabits();
        }
        else
        {
            LoadGoodTasks();
        }
    }
References TaskOpenPanelController.CurrentTask, LoadBadHabits(), LoadGoodTasks(), taskOpenPanelController, Tasks, and TaskSortDropdown.
Referenced by TaskDisplayHandler.CompleteStateChange(), and TaskOpenPanelController.SavedTask().
LoadGoodTasks()
void MainWindowController.LoadGoodTasks (bool updateDisplay = true) inline
Definition at line 130 of file MainWindowController.cs.
    {
        try
        {
            foreach (var task in Tasks)
            {
                if (!task.Value.CurrentTask.TaskType)
                {
                    task.Value.gameObject.SetActive(true);
                    task.Value.gameObject.transform.SetAsLastSibling();
                }
                else
                {
                    task.Value.gameObject.SetActive(false);
                }
            }
            TaskParent.GetComponentInChildren<TMP_Text>().text = "Good tasks";
            if (updateDisplay)
                taskOpenPanelController.MakeItGoodTask();
        }
        catch (MissingReferenceException)
        {
            return;
        }
    }
References TaskOpenPanelController.MakeItGoodTask(), taskOpenPanelController, TaskParent, and Tasks.
Referenced by TaskOpenPanelController.Cancel(), CreateTaskPrefabs(), TaskOpenPanelController.MakeItGoodTask(), and SortingChanged().
LoadBadHabits()
void MainWindowController.LoadBadHabits (bool updateDisplay = true) inline
Definition at line 156 of file MainWindowController.cs.
    {
        try
        {
            foreach (var task in Tasks)
            {
                if (task.Value.CurrentTask.TaskType)
                {
                    task.Value.gameObject.SetActive(true);
                    task.Value.gameObject.transform.SetAsLastSibling();
                }
                else
                {
                    task.Value.gameObject.SetActive(false);
                }
            }
            TaskParent.GetComponentInChildren<TMP_Text>().text = "Bad habits";
            if (updateDisplay)
                taskOpenPanelController.MakeItBadHabit();
        }
        catch (MissingReferenceException)
        {
            return;
        }
    }
References TaskOpenPanelController.MakeItBadHabit(), taskOpenPanelController, TaskParent, and Tasks.
Referenced by TaskOpenPanelController.Cancel(), TaskOpenPanelController.MakeItBadHabit(), and SortingChanged().
CreateTask()
GameObject MainWindowController.CreateTask (PlayerTask taskContainer) inline
Definition at line 182 of file MainWindowController.cs.
    {
        try
        {
            GameObject task = Instantiate(TaskPrefab, TaskParent.transform);
            TaskDisplayHandler taskComponent = task.GetComponent<TaskDisplayHandler>();
            taskComponent.InitValues(taskContainer, taskOpenPanelController, this);
            Tasks.Add(taskContainer.ID, taskComponent);
            return task;
        }
        catch (MissingReferenceException e)
        {
            return null;
        }
    }
References TaskDisplayHandler.InitValues(), taskOpenPanelController, TaskParent, TaskPrefab, and Tasks.
Referenced by CreateTaskPrefabs(), and TaskOpenPanelController.SavedTask().
LoadTasks()
void MainWindowController.LoadTasks () inline private
Definition at line 200 of file MainWindowController.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<Thesis_backend.Data_Structures.PlayerTask>>(ServerConfig.PATHFORTASKSQUERY, CreateTaskPrefabs, onFailedAction: ShowRequestFail));
    }
References CreateTaskPrefabs(), Config.ServerConfig.PATHFORTASKSQUERY, CoroutineRunner.RunCoroutine(), and ShowRequestFail().
Referenced by Start().
ShowRequestFail()
void MainWindowController.ShowRequestFail (string content) inline private
Definition at line 205 of file MainWindowController.cs.
    {
        ModalWindow.Show("Request fail", content);
    }
References ModalWindow.Show().
Referenced by LoadTasks().
ShowTaskFail()
void MainWindowController.ShowTaskFail (string content) inline
Definition at line 210 of file MainWindowController.cs.
    {
        ModalWindow.Show("Task error", content);
    }
References ModalWindow.Show().
Referenced by TaskDisplayHandler.CompleteTask(), TaskOpenPanelController.DeleteTask(), TaskOpenPanelController.Save(), and TaskDisplayHandler.TaskCompleted().
LoadGameScene()
void MainWindowController.LoadGameScene () inline
Definition at line 215 of file MainWindowController.cs.
    {
        SceneManager.LoadScene("GameScene", LoadSceneMode.Single);
    }
CreateTaskPrefabs()
void MainWindowController.CreateTaskPrefabs (List< Thesis_backend::Data_Structures::PlayerTask > requestResult) inline private
Definition at line 220 of file MainWindowController.cs.
    {
        foreach (var item in requestResult)
        {
            CreateTask(item);
        }
        LoadGoodTasks();
    }
References CreateTask(), and LoadGoodTasks().
Referenced by LoadTasks().
Member Data Documentation
UsernameInputText
TMP_Text MainWindowController.UsernameInputText private
Definition at line 17 of file MainWindowController.cs.
CurrencyText
TMP_Text MainWindowController.CurrencyText private
Definition at line 20 of file MainWindowController.cs.
TaskParent
GameObject MainWindowController.TaskParent private
Definition at line 23 of file MainWindowController.cs.
Referenced by CreateTask(), LoadBadHabits(), and LoadGoodTasks().
TaskPrefab
GameObject MainWindowController.TaskPrefab private
Definition at line 26 of file MainWindowController.cs.
Referenced by CreateTask().
taskOpenPanelController
TaskOpenPanelController MainWindowController.taskOpenPanelController private
Definition at line 29 of file MainWindowController.cs.
Referenced by CreateTask(), LoadBadHabits(), LoadGoodTasks(), and SortingChanged().
ModalWindow
ModalWindow MainWindowController.ModalWindow
Definition at line 32 of file MainWindowController.cs.
TaskSortDropdown
TMP_Dropdown MainWindowController.TaskSortDropdown private
Definition at line 35 of file MainWindowController.cs.
Referenced by SortingChanged().
Property Documentation
Tasks
Dictionary<long, TaskDisplayHandler> MainWindowController.Tasks = new Dictionary<long, TaskDisplayHandler>() get private set
Definition at line 37 of file MainWindowController.cs.
{ get; private set; } = new Dictionary<long, TaskDisplayHandler>();
Referenced by CreateTask(), LoadBadHabits(), LoadGoodTasks(), RemoveTask(), SortingChanged(), and UpdateTask().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/MainWindowController.cs