Thesis: User.LoggedInChecker Class Reference
User.LoggedInChecker Class Reference
Checks if the user has a session stored in the backend
Private Member Functions
void Awake ()
Called when the script is loaded
IEnumerator CheckLoggedInPeriodically ()
Coroutine which calls the api endpoint to check if the user is still logged in
void LoggedOut (string reason)
Handles if the user is not logged in
IEnumerator MoveToLoginScene ()
Move the user to the login screen
void LoggedIn (Thesis_backend.Data_Structures.User result)
Update the user data from the server data
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Checks if the user has a session stored in the backend
Definition at line 13 of file LoggedInChecker.cs.
Member Function Documentation
Awake()
void User.LoggedInChecker.Awake () inline private
Called when the script is loaded
Definition at line 18 of file LoggedInChecker.cs.
         {
             StartCoroutine(CheckLoggedInPeriodically());
         }
References User.LoggedInChecker.CheckLoggedInPeriodically().
CheckLoggedInPeriodically()
IEnumerator User.LoggedInChecker.CheckLoggedInPeriodically () inline private
Coroutine which calls the api endpoint to check if the user is still logged in
Definition at line 26 of file LoggedInChecker.cs.
         {
             //Run it while the gameobject is active
             while (true)
             {
                 // Send the API request
                 yield return CoroutineRunner.RunCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORCHECKLOGGEDIN, LoggedIn, onFailedAction: LoggedOut));
                 // Wait for 60 seconds before sending the next request
                 yield return new WaitForSeconds(60f);
             }
         }
References User.LoggedInChecker.LoggedIn(), User.LoggedInChecker.LoggedOut(), Config.ServerConfig.PATHFORCHECKLOGGEDIN, and Utility.CoroutineRunner.RunCoroutine().
Referenced by User.LoggedInChecker.Awake().
LoggedOut()
void User.LoggedInChecker.LoggedOut (string reason) inline private
Handles if the user is not logged in
Parameters
reason Why the api request failed
Definition at line 43 of file LoggedInChecker.cs.
         {
             UserData.Instance.Logout();
             AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
         }
References User.UserData.Instance, and User.UserData.Logout().
Referenced by User.LoggedInChecker.CheckLoggedInPeriodically().
MoveToLoginScene()
IEnumerator User.LoggedInChecker.MoveToLoginScene () inline private
Move the user to the login screen
Definition at line 52 of file LoggedInChecker.cs.
         {
             AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
             while (true)
             {
                 Debug.Log(loading.progress);
                 yield return null;
             }
         }
LoggedIn()
void User.LoggedInChecker.LoggedIn (Thesis_backend.Data_Structures.User result) inline private
Update the user data from the server data
Parameters
result The server's response
Definition at line 68 of file LoggedInChecker.cs.
         {
             if (UserData.Instance.LoggedIn)
             {
                 return;
             }
             UserData.Instance.Init(result);
         }
References User.UserData.Init(), User.UserData.Instance, and User.UserData.LoggedIn.
Referenced by User.LoggedInChecker.CheckLoggedInPeriodically().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/User/LoggedInChecker.cs