Bomberman: TaskHistoryWindowHandler Class Reference
TaskHistoryWindowHandler Class Reference
Public Member Functions
void Show ()
void Hide ()
void LoadTaskHistories ()
Private Member Functions
void ShowRequestFail (string content)
void LoadedHistories (List< TaskHistory > taskHistories)
Private Attributes
GameObject taskHistoriesParent
ModalWindow modalWindow
GameObject taskHistoryItemPrefab
Detailed Description
Definition at line 9 of file TaskHistoryWindowHandler.cs.
Member Function Documentation
Show()
void TaskHistoryWindowHandler.Show () inline
Definition at line 20 of file TaskHistoryWindowHandler.cs.
    {
        this.gameObject.SetActive(true);
        LoadTaskHistories();
    }
References LoadTaskHistories().
Hide()
void TaskHistoryWindowHandler.Hide () inline
Definition at line 26 of file TaskHistoryWindowHandler.cs.
    {
        this.gameObject.SetActive(false);
    }
LoadTaskHistories()
void TaskHistoryWindowHandler.LoadTaskHistories () inline
Definition at line 31 of file TaskHistoryWindowHandler.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<TaskHistory>>(ServerConfig.PATH_FOR_GET_TASK_HISTORIES, LoadedHistories, onFailedAction: ShowRequestFail));
    }
References LoadedHistories(), Config.ServerConfig.PATH_FOR_GET_TASK_HISTORIES, CoroutineRunner.RunCoroutine(), and ShowRequestFail().
Referenced by Show().
ShowRequestFail()
void TaskHistoryWindowHandler.ShowRequestFail (string content) inline private
Definition at line 36 of file TaskHistoryWindowHandler.cs.
    {
        modalWindow.Show("Task history error", content);
    }
References modalWindow, and ModalWindow.Show().
Referenced by LoadTaskHistories().
LoadedHistories()
void TaskHistoryWindowHandler.LoadedHistories (List< TaskHistory > taskHistories) inline private
Definition at line 41 of file TaskHistoryWindowHandler.cs.
    {
        if (taskHistoriesParent == null || this.taskHistoriesParent.transform == null)
        {
            // Exit or handle the case when the Score parent is destroyed
            Debug.LogWarning("Score parent has been destroyed or is missing.");
            return;
        }
        //Delete the previous ones
        for (int i = 0; i < this.taskHistoriesParent.transform.childCount; i++)
        {
            Destroy(this.taskHistoriesParent.transform.GetChild(i).gameObject);
        }
        this.taskHistoriesParent.transform.DetachChildren();
        foreach (var item in taskHistories)
        {
            TaskHistoryHandler leaderboardItem = Instantiate(taskHistoryItemPrefab, taskHistoriesParent.transform).GetComponent<TaskHistoryHandler>();
            leaderboardItem.Init(item);
        }
    }
References TaskHistoryHandler.Init(), taskHistoriesParent, and taskHistoryItemPrefab.
Referenced by LoadTaskHistories().
Member Data Documentation
taskHistoriesParent
GameObject TaskHistoryWindowHandler.taskHistoriesParent private
Definition at line 12 of file TaskHistoryWindowHandler.cs.
Referenced by LoadedHistories().
modalWindow
ModalWindow TaskHistoryWindowHandler.modalWindow private
Definition at line 15 of file TaskHistoryWindowHandler.cs.
Referenced by ShowRequestFail().
taskHistoryItemPrefab
GameObject TaskHistoryWindowHandler.taskHistoryItemPrefab private
Definition at line 18 of file TaskHistoryWindowHandler.cs.
Referenced by LoadedHistories().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/TaskHistoryWindowHandler.cs