Thesis: ModalWindow Class Reference
ModalWindow Class Reference
Public Member Functions
void Show ()
void Show (string title, string content, Action onOkAction=null)
void Hide ()
void ConfirmButtonClick ()
Private Attributes
TMP_Text ModalTitleText
TMP_Text ModalContentText
Action onOkAction
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Detailed Description
Definition at line 7 of file ModalWindowScript.cs.
Member Function Documentation
Show() [1/2]
void ModalWindow.Show () inline
Definition at line 17 of file ModalWindowScript.cs.
    {
        if (this.Destroyed)
        {
            return;
        }
        try
        {
            this.gameObject.SetActive(true);
        }
        catch (MissingReferenceException)
        {
            return;
        }
    }
References ThreadSafeMonoBehaviour.Destroyed.
Referenced by User.UserController.SendRegister(), Show(), User.UserController.ShowLoginError(), User.UserController.ShowRegisterError(), GameUI.ShowRequestFail(), LeaderboardWindow.ShowRequestFail(), ShopWindow.ShowRequestFail(), MainPage.MainWindowController.ShowRequestFail(), MainPage.FriendWindowHandler.ShowRequestFail(), MainPage.TaskHistoryWindowHandler.ShowRequestFail(), and MainPage.MainWindowController.ShowTaskFail().
Show() [2/2]
void ModalWindow.Show (string title, string content, Action onOkAction = null) inline
Definition at line 33 of file ModalWindowScript.cs.
    {
        if (this.Destroyed)
        {
            return;
        }
        try
        {
            this.ModalTitleText.text = title;
            this.ModalContentText.text = content;
            this.onOkAction = onOkAction;
            Show();
        }
        catch (MissingReferenceException)
        {
            return;
        }
    }
References ThreadSafeMonoBehaviour.Destroyed, onOkAction, and Show().
Hide()
void ModalWindow.Hide () inline
Definition at line 54 of file ModalWindowScript.cs.
    {
        if (this.Destroyed)
        {
            return;
        }
        this.gameObject.SetActive(false);
    }
References ThreadSafeMonoBehaviour.Destroyed.
Referenced by ConfirmButtonClick().
ConfirmButtonClick()
void ModalWindow.ConfirmButtonClick () inline
Definition at line 63 of file ModalWindowScript.cs.
    {
        if (onOkAction is not null)
        {
            onOkAction();
        }
        Hide();
    }
References Hide(), and onOkAction.
Member Data Documentation
ModalTitleText
TMP_Text ModalWindow.ModalTitleText private
Definition at line 10 of file ModalWindowScript.cs.
ModalContentText
TMP_Text ModalWindow.ModalContentText private
Definition at line 13 of file ModalWindowScript.cs.
onOkAction
Action ModalWindow.onOkAction private
Definition at line 15 of file ModalWindowScript.cs.
Referenced by ConfirmButtonClick(), and Show().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Utility/ModalWindowScript.cs