Bomberman: ShopItem Class Reference
ShopItem Class Reference
Public Member Functions
void Init (ShopWindow parentWindow, Shop item, Sprite image, bool owned)
void Buy ()
Properties
long Id [get, private set]
Private Member Functions
void Bought (Thesis_backend.Data_Structures.Game game)
Private Attributes
TMP_Text ProductName
Image ProductImage
TMP_Text Price
Button BuyButton
ShopWindow shopWindow
Detailed Description
Definition at line 10 of file ShopItem.cs.
Member Function Documentation
Init()
void ShopItem.Init (ShopWindow parentWindow, Shop item, Sprite image, bool owned) inline
Definition at line 28 of file ShopItem.cs.
     {
         this.shopWindow = parentWindow;
         this.ProductName.text = item.ProductName;
         this.ProductImage.sprite = image;
         this.Price.text = item.Cost.ToString();
         this.Id = item.ID;
         this.BuyButton.gameObject.SetActive(!owned);
     }
References Id.
Referenced by ShopWindow.LoadedShopItems().
Buy()
void ShopItem.Buy () inline
Definition at line 38 of file ShopItem.cs.
     {
         StartCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Game>(ServerConfig.PATH_FOR_BUY_CAR(Id), new WWWForm(), Bought));
     }
References Bought(), Id, and Config.ServerConfig.PATH_FOR_BUY_CAR().
Bought()
void ShopItem.Bought (Thesis_backend.Data_Structures.Game game) inline private
Definition at line 43 of file ShopItem.cs.
     {
         UserData.Instance.Game.OwnedCars = game.OwnedCars;
         UserData.Instance.Game.Currency = game.Currency;
         shopWindow.UpdateShop();
     }
References User.UserData.Game, User.UserData.Instance, shopWindow, and ShopWindow.UpdateShop().
Referenced by Buy().
Member Data Documentation
ProductName
TMP_Text ShopItem.ProductName private
Definition at line 13 of file ShopItem.cs.
ProductImage
Image ShopItem.ProductImage private
Definition at line 16 of file ShopItem.cs.
Price
TMP_Text ShopItem.Price private
Definition at line 19 of file ShopItem.cs.
BuyButton
Button ShopItem.BuyButton private
Definition at line 22 of file ShopItem.cs.
shopWindow
ShopWindow ShopItem.shopWindow private
Definition at line 24 of file ShopItem.cs.
Referenced by Bought().
Property Documentation
Id
long ShopItem.Id get private set
Definition at line 26 of file ShopItem.cs.
 { get; private set; }
Referenced by Buy(), and Init().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/ShopItem.cs