Bomberman: FriendHandler Class Reference
FriendHandler Class Reference
Public Member Functions
void Update ()
void InitValues (Friend friend)
void AcceptFriendRequest ()
void DeleteFriend ()
Properties
Friend Friend [get, private set]
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Private Member Functions
void Accepted (Thesis_backend.Data_Structures.Friend result)
void Deleted (string result)
Private Attributes
TMP_Text FriendNameLabel
TMP_Text ScoreText
TMP_Text ScoreLabelText
Button AcceptButton
TMP_Text Pendingtext
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Detailed Description
Definition at line 8 of file FriendHandler.cs.
Member Function Documentation
Update()
void FriendHandler.Update () inline
Definition at line 27 of file FriendHandler.cs.
    {
    }
InitValues()
void FriendHandler.InitValues (Friend friend) inline
Definition at line 31 of file FriendHandler.cs.
    {
        this.Friend = friend;
        this.AcceptButton.gameObject.SetActive(Friend.Pending);
        if (UserData.Instance.Id != this.Friend.Sender.ID)
        {
            FriendNameLabel.text = this.Friend.Sender.Username;
            ScoreText.text = this.Friend.Sender.TotalScore.ToString();
            if (Friend.Pending)
            {
                AcceptButton.gameObject.SetActive(true);
            }
        }
        else
        {
            FriendNameLabel.text = this.Friend.Receiver.Username;
            ScoreText.text = this.Friend.Receiver.TotalScore.ToString();
            if (friend.Pending)
            {
                AcceptButton.gameObject.SetActive(false);
                Pendingtext.gameObject.SetActive(true);
            }
        }
        this.ScoreText.gameObject.SetActive(!friend.Pending);
        this.ScoreLabelText.gameObject.SetActive(!friend.Pending);
    }
References Friend, User.UserData.Id, User.UserData.Instance, Thesis_backend.Data_Structures.Pending, and Pendingtext.
Referenced by FriendWindowHandler.DisplayFriends(), and FriendWindowHandler.SentFriendRequest().
AcceptFriendRequest()
void FriendHandler.AcceptFriendRequest () inline
Definition at line 59 of file FriendHandler.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Friend>(ServerConfig.PATH_FOR_FRIEND_ACCEPT(this.Friend.ID), onComplete: Accepted));
    }
References Accepted(), Config.ServerConfig.PATH_FOR_FRIEND_ACCEPT(), and CoroutineRunner.RunCoroutine().
DeleteFriend()
void FriendHandler.DeleteFriend () inline
Definition at line 64 of file FriendHandler.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATH_FOR_FRIEND_DELETE(this.Friend.ID), onComplete: Deleted));
    }
References Deleted(), Config.ServerConfig.PATH_FOR_FRIEND_DELETE(), and CoroutineRunner.RunCoroutine().
Accepted()
void FriendHandler.Accepted (Thesis_backend::Data_Structures::Friend result) inline private
Definition at line 69 of file FriendHandler.cs.
    {
        this.Friend.Pending = false;
        this.AcceptButton.gameObject.SetActive(false);
        this.ScoreText.gameObject.SetActive(true);
        this.ScoreLabelText.gameObject.SetActive(true);
    }
Referenced by AcceptFriendRequest().
Deleted()
void FriendHandler.Deleted (string result) inline private
Definition at line 77 of file FriendHandler.cs.
    {
        if (result == "Deleted")
        {
            Destroy(this.gameObject);
        }
    }
Referenced by DeleteFriend().
Member Data Documentation
FriendNameLabel
TMP_Text FriendHandler.FriendNameLabel private
Definition at line 11 of file FriendHandler.cs.
ScoreText
TMP_Text FriendHandler.ScoreText private
Definition at line 14 of file FriendHandler.cs.
ScoreLabelText
TMP_Text FriendHandler.ScoreLabelText private
Definition at line 17 of file FriendHandler.cs.
AcceptButton
Button FriendHandler.AcceptButton private
Definition at line 20 of file FriendHandler.cs.
Pendingtext
TMP_Text FriendHandler.Pendingtext private
Definition at line 23 of file FriendHandler.cs.
Referenced by InitValues().
Property Documentation
Friend
Friend FriendHandler.Friend get private set
Definition at line 25 of file FriendHandler.cs.
{ get; private set; }
Referenced by InitValues().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/DisplayElements/FriendHandler.cs