Bomberman: GameUI Class Reference
GameUI Class Reference
Public Member Functions
void SaveGameResult ()
void DoubleCoins ()
void BuyImmunity ()
void BuyTurbo ()
void ShowLeaderboard ()
void LeftRotateSkin ()
void RightRotateSkin ()
void Init (GameController gameController)
async void NewGame (bool save=true)
void ChangeDifficulyDisplay (int difficulty)
void ShowEndGameScreen ()
void HideGameOverScreen (bool saveGameResults=true)
void ShowShopWindow ()
void HideShopWindow ()
void BackToTasks ()
void BackToGameMenuWithoutSave ()
void BackToGameMenu ()
Properties
bool Doubled = false [get, private set]
int SelectedSkinIndex = 0 [get, private set]
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Private Member Functions
void Update ()
void SavedCoins (Thesis_backend.Data_Structures.Game game)
void BoughtImmunity (Thesis_backend.Data_Structures.User user)
void BoughtTurbo (Thesis_backend.Data_Structures.User user)
void DoubledCoins (Thesis_backend.Data_Structures.User user)
void ShowRequestFail (string content)
Private Attributes
GameObject gameOverContainer
GameObject ingameContainer
ShopWindow ShopWindow
GameObject mainMenuContainer
Image SkinDisplay
LeaderboardWindow leaderboardWindow
TMP_Text InfamyGameOverText
TMP_Text CoinGameOverText
TMP_Text InfamyInGameText
TMP_Text TaskScoreInGameText
TMP_Text CoinInGameText
StarHandler starHandler
Button DoubleCoinButon
ModalWindow ModalWindow
GameController gameController
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Detailed Description
Definition at line 10 of file GameUI.cs.
Member Function Documentation
Update()
void GameUI.Update () inline private
Definition at line 59 of file GameUI.cs.
    {
        if (gameController.Running)
        {
            this.InfamyInGameText.text = "Infamy: " + gameController.Score;
            this.CoinInGameText.text = Mathf.RoundToInt(gameController.Coins).ToString();
        }
    }
References Game.GameController.Coins, gameController, Game.GameController.Running, and Game.GameController.Score.
SaveGameResult()
void GameUI.SaveGameResult () inline
Definition at line 68 of file GameUI.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Game>(ServerConfig.PATH_FOR_SAVE_COINS, (int)(Doubled ? gameController.Coins * 2 : gameController.Coins), SavedCoins, onFailedAction: ShowRequestFail));
        CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.GameScore>(ServerConfig.PATH_FOR_STORE_GAME_SCORE, gameController.Score, onFailedAction: ShowRequestFail));
    }
References Game.GameController.Coins, Doubled, gameController, Config.ServerConfig.PATH_FOR_SAVE_COINS, Config.ServerConfig.PATH_FOR_STORE_GAME_SCORE, CoroutineRunner.RunCoroutine(), SavedCoins(), Game.GameController.Score, and ShowRequestFail().
Referenced by HideGameOverScreen().
SavedCoins()
void GameUI.SavedCoins (Thesis_backend::Data_Structures::Game game) inline private
Definition at line 74 of file GameUI.cs.
    {
        UserData.Instance.Game.Currency = game.Currency;
    }
Referenced by SaveGameResult().
DoubleCoins()
void GameUI.DoubleCoins () inline
Definition at line 79 of file GameUI.cs.
    {
        if (UserData.Instance.CurrentTaskScore >= GameConfig.DOUBLE_COIN_COST)
        {
            CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_DOUBLE_COINS, new WWWForm(), DoubledCoins, onFailedAction: ShowRequestFail));
        }
    }
References User.UserData.CurrentTaskScore, GameConfig.DOUBLE_COIN_COST, DoubledCoins(), User.UserData.Instance, Config.ServerConfig.PATH_FOR_DOUBLE_COINS, CoroutineRunner.RunCoroutine(), and ShowRequestFail().
BuyImmunity()
void GameUI.BuyImmunity () inline
Definition at line 87 of file GameUI.cs.
    {
        if (UserData.Instance.CurrentTaskScore >= GameConfig.IMMUNITY_COST)
        {
            CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_BUY_IMMUNITY, new WWWForm(), BoughtImmunity, onFailedAction: ShowRequestFail));
        }
    }
References BoughtImmunity(), User.UserData.CurrentTaskScore, GameConfig.IMMUNITY_COST, User.UserData.Instance, Config.ServerConfig.PATH_FOR_BUY_IMMUNITY, CoroutineRunner.RunCoroutine(), and ShowRequestFail().
BuyTurbo()
void GameUI.BuyTurbo () inline
Definition at line 95 of file GameUI.cs.
    {
        if (UserData.Instance.CurrentTaskScore >= GameConfig.TURBO_COST)
        {
            CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_BUY_TURBO, new WWWForm(), BoughtTurbo, onFailedAction: ShowRequestFail));
        }
    }
References BoughtTurbo(), User.UserData.CurrentTaskScore, User.UserData.Instance, Config.ServerConfig.PATH_FOR_BUY_TURBO, CoroutineRunner.RunCoroutine(), ShowRequestFail(), and GameConfig.TURBO_COST.
BoughtImmunity()
void GameUI.BoughtImmunity (Thesis_backend::Data_Structures::User user) inline private
Definition at line 103 of file GameUI.cs.
    {
        UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
        gameController.Player.ApplyImmunity();
        TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
    }
References Game.PlayerCar.ApplyImmunity(), User.UserData.CurrentTaskScore, gameController, User.UserData.Instance, Game.GameController.Player, and User.UserData.UpdateTaskScore().
Referenced by BuyImmunity().
BoughtTurbo()
void GameUI.BoughtTurbo (Thesis_backend::Data_Structures::User user) inline private
Definition at line 110 of file GameUI.cs.
    {
        UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
        gameController.Player.ApplyTurbo();
        TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
    }
References Game.PlayerCar.ApplyTurbo(), User.UserData.CurrentTaskScore, gameController, User.UserData.Instance, Game.GameController.Player, and User.UserData.UpdateTaskScore().
Referenced by BuyTurbo().
DoubledCoins()
void GameUI.DoubledCoins (Thesis_backend::Data_Structures::User user) inline private
Definition at line 117 of file GameUI.cs.
    {
        this.Doubled = true;
        this.DoubleCoinButon.interactable = false;
        CoinGameOverText.text = "Coins: " + gameController.Coins * 2;
        TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
        UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
    }
References User.UserData.CurrentTaskScore, User.UserData.Instance, and User.UserData.UpdateTaskScore().
Referenced by DoubleCoins().
ShowLeaderboard()
void GameUI.ShowLeaderboard () inline
Definition at line 126 of file GameUI.cs.
    {
        leaderboardWindow.Show();
    }
References leaderboardWindow, and LeaderboardWindow.Show().
LeftRotateSkin()
void GameUI.LeftRotateSkin () inline
Definition at line 131 of file GameUI.cs.
    {
        SelectedSkinIndex = (SelectedSkinIndex + UserData.Instance.Game.OwnedCars.Count - 1) % UserData.Instance.Game.OwnedCars.Count;
        SkinDisplay.sprite = ShopWindow.ShopItemSprites[(int)UserData.Instance.Game.OwnedCars[SelectedSkinIndex].ShopId - 1];
    }
References User.UserData.Game, User.UserData.Instance, SelectedSkinIndex, and ShopWindow.ShopItemSprites.
RightRotateSkin()
void GameUI.RightRotateSkin () inline
Definition at line 137 of file GameUI.cs.
    {
        SelectedSkinIndex = (SelectedSkinIndex + 1) % UserData.Instance.Game.OwnedCars.Count;
        SkinDisplay.sprite = ShopWindow.ShopItemSprites[(int)UserData.Instance.Game.OwnedCars[SelectedSkinIndex].ShopId - 1];
    }
References User.UserData.Game, User.UserData.Instance, SelectedSkinIndex, and ShopWindow.ShopItemSprites.
Init()
void GameUI.Init (GameController gameController) inline
Definition at line 143 of file GameUI.cs.
    {
        this.gameController = gameController;
    }
References gameController.
Referenced by Game.GameController.Awake().
NewGame()
async void GameUI.NewGame (bool save = true) inline
Definition at line 148 of file GameUI.cs.
    {
        HideGameOverScreen(save);
        ingameContainer.SetActive(true);
        mainMenuContainer.SetActive(false);
        TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
        await gameController?.NewGame();
    }
References User.UserData.CurrentTaskScore, gameController, HideGameOverScreen(), ingameContainer, User.UserData.Instance, mainMenuContainer, and Game.GameController.NewGame().
ShowRequestFail()
void GameUI.ShowRequestFail (string content) inline private
Definition at line 158 of file GameUI.cs.
    {
        ModalWindow.Show("Request fail", content);
    }
References ModalWindow.Show().
Referenced by BuyImmunity(), BuyTurbo(), DoubleCoins(), and SaveGameResult().
ChangeDifficulyDisplay()
void GameUI.ChangeDifficulyDisplay (int difficulty) inline
Definition at line 163 of file GameUI.cs.
    {
        this.starHandler.ChangeDifficulty(difficulty);
    }
References StarHandler.ChangeDifficulty().
Referenced by Game.GameController.NewGame(), and Game.GameController.Update().
ShowEndGameScreen()
void GameUI.ShowEndGameScreen () inline
Definition at line 168 of file GameUI.cs.
    {
        InfamyGameOverText.text = "Infamy: " + gameController.Score;
        CoinGameOverText.text = "Coins: " + gameController.Coins;
        ingameContainer.SetActive(false);
        gameOverContainer.SetActive(true);
        Doubled = false;
        this.DoubleCoinButon.interactable = UserData.Instance.CurrentTaskScore >= 1000;
    }
References Game.GameController.Coins, Doubled, gameController, gameOverContainer, ingameContainer, and Game.GameController.Score.
Referenced by Game.GameController.PlayerDied().
HideGameOverScreen()
void GameUI.HideGameOverScreen (bool saveGameResults = true) inline
Definition at line 178 of file GameUI.cs.
    {
        gameOverContainer.SetActive(false);
        ingameContainer.SetActive(true);
        if (saveGameResults)
        {
            SaveGameResult();
        }
    }
References gameOverContainer, ingameContainer, and SaveGameResult().
Referenced by BackToGameMenu(), BackToGameMenuWithoutSave(), BackToTasks(), and NewGame().
ShowShopWindow()
void GameUI.ShowShopWindow () inline
Definition at line 188 of file GameUI.cs.
    {
        this.ShopWindow.Show();
    }
References ShopWindow.Show().
HideShopWindow()
void GameUI.HideShopWindow () inline
Definition at line 193 of file GameUI.cs.
    {
        this.ShopWindow.Hide();
    }
References ShopWindow.Hide().
BackToTasks()
void GameUI.BackToTasks () inline
Definition at line 198 of file GameUI.cs.
    {
        HideGameOverScreen(false);
        SceneManager.LoadScene("MainScene", LoadSceneMode.Single);
    }
References HideGameOverScreen().
BackToGameMenuWithoutSave()
void GameUI.BackToGameMenuWithoutSave () inline
Definition at line 204 of file GameUI.cs.
    {
        gameController.Player.Kill();
        HideGameOverScreen(false);
        ingameContainer.SetActive(false);
        mainMenuContainer.SetActive(true);
    }
References gameController, HideGameOverScreen(), ingameContainer, Game.Car.Kill(), mainMenuContainer, and Game.GameController.Player.
BackToGameMenu()
void GameUI.BackToGameMenu () inline
Definition at line 212 of file GameUI.cs.
    {
        HideGameOverScreen();
        ingameContainer.SetActive(false);
        mainMenuContainer.SetActive(true);
    }
References HideGameOverScreen(), ingameContainer, and mainMenuContainer.
Member Data Documentation
gameOverContainer
GameObject GameUI.gameOverContainer private
Definition at line 13 of file GameUI.cs.
Referenced by HideGameOverScreen(), and ShowEndGameScreen().
ingameContainer
GameObject GameUI.ingameContainer private
Definition at line 16 of file GameUI.cs.
Referenced by BackToGameMenu(), BackToGameMenuWithoutSave(), HideGameOverScreen(), NewGame(), and ShowEndGameScreen().
ShopWindow
ShopWindow GameUI.ShopWindow private
Definition at line 19 of file GameUI.cs.
mainMenuContainer
GameObject GameUI.mainMenuContainer private
Definition at line 22 of file GameUI.cs.
Referenced by BackToGameMenu(), BackToGameMenuWithoutSave(), and NewGame().
SkinDisplay
Image GameUI.SkinDisplay private
Definition at line 25 of file GameUI.cs.
leaderboardWindow
LeaderboardWindow GameUI.leaderboardWindow private
Definition at line 28 of file GameUI.cs.
Referenced by ShowLeaderboard().
InfamyGameOverText
TMP_Text GameUI.InfamyGameOverText private
Definition at line 31 of file GameUI.cs.
CoinGameOverText
TMP_Text GameUI.CoinGameOverText private
Definition at line 34 of file GameUI.cs.
InfamyInGameText
TMP_Text GameUI.InfamyInGameText private
Definition at line 37 of file GameUI.cs.
TaskScoreInGameText
TMP_Text GameUI.TaskScoreInGameText private
Definition at line 40 of file GameUI.cs.
CoinInGameText
TMP_Text GameUI.CoinInGameText private
Definition at line 43 of file GameUI.cs.
starHandler
StarHandler GameUI.starHandler private
Definition at line 46 of file GameUI.cs.
DoubleCoinButon
Button GameUI.DoubleCoinButon private
Definition at line 49 of file GameUI.cs.
ModalWindow
ModalWindow GameUI.ModalWindow private
Definition at line 52 of file GameUI.cs.
gameController
GameController GameUI.gameController private
Definition at line 54 of file GameUI.cs.
Referenced by BackToGameMenuWithoutSave(), BoughtImmunity(), BoughtTurbo(), Init(), NewGame(), SaveGameResult(), ShowEndGameScreen(), and Update().
Property Documentation
Doubled
bool GameUI.Doubled = false get private set
Definition at line 55 of file GameUI.cs.
{ get; private set; } = false;
Referenced by SaveGameResult(), and ShowEndGameScreen().
SelectedSkinIndex
int GameUI.SelectedSkinIndex = 0 get private set
Definition at line 57 of file GameUI.cs.
{ get; private set; } = 0;
Referenced by LeftRotateSkin(), Game.GameController.NewGame(), and RightRotateSkin().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/GameUI.cs