Thesis: Game.UI.ShopItem Class Reference
Game.UI.ShopItem Class Reference
Public Member Functions
void Init (ShopWindow parentWindow, Shop item, Sprite image, bool owned)
void Buy ()
string GetDisplayedPrice ()
Properties
long Id [get, private set]
bool Owned [get, private set]
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void Bought (Thesis_backend.Data_Structures.Game game)
Private Attributes
TMP_Text ProductName
Image ProductImage
TMP_Text Price
Button BuyButton
ShopWindow shopWindow
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Definition at line 15 of file ShopItem.cs.
Member Function Documentation
Init()
void Game.UI.ShopItem.Init (ShopWindow parentWindow, Shop item, Sprite image, bool owned) inline
Definition at line 35 of file ShopItem.cs.
             {
                 this.shopWindow = parentWindow;
                 this.ProductName.text = item.ProductName;
                 this.ProductImage.sprite = image;
                 this.Price.text = item.Cost.ToString();
                 this.Id = item.ID;
                 this.BuyButton.gameObject.SetActive(!owned);
                 this.Owned = owned;
             }
References Game.UI.ShopItem.Id, and Game.UI.ShopItem.Owned.
Referenced by Game.UI.ShopWindow.LoadedShopItems().
Buy()
void Game.UI.ShopItem.Buy () inline
Definition at line 46 of file ShopItem.cs.
             {
                 CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Game>(ServerConfig.PATH_FOR_BUY_CAR(Id), new WWWForm(), Bought));
             }
References Game.UI.ShopItem.Bought(), Game.UI.ShopItem.Id, Config.ServerConfig.PATH_FOR_BUY_CAR(), and Utility.CoroutineRunner.RunCoroutine().
Bought()
void Game.UI.ShopItem.Bought (Thesis_backend.Data_Structures.Game game) inline private
Definition at line 51 of file ShopItem.cs.
             {
                 UserData.Instance.Game.OwnedCars = game.OwnedCars;
                 UserData.Instance.Game.Currency = game.Currency;
                 this.Owned = true;
                 shopWindow.UpdateShop();
             }
References User.UserData.Game, User.UserData.Instance, Game.UI.ShopItem.Owned, and Game.UI.ShopWindow.UpdateShop().
Referenced by Game.UI.ShopItem.Buy().
GetDisplayedPrice()
string Game.UI.ShopItem.GetDisplayedPrice () inline
Definition at line 61 of file ShopItem.cs.
             {
                 return Price.text;
             }
References Game.UI.ShopItem.Price.
Member Data Documentation
ProductName
TMP_Text Game.UI.ShopItem.ProductName private
Definition at line 18 of file ShopItem.cs.
ProductImage
Image Game.UI.ShopItem.ProductImage private
Definition at line 21 of file ShopItem.cs.
Price
TMP_Text Game.UI.ShopItem.Price private
Definition at line 24 of file ShopItem.cs.
Referenced by Game.UI.ShopItem.GetDisplayedPrice().
BuyButton
Button Game.UI.ShopItem.BuyButton private
Definition at line 27 of file ShopItem.cs.
shopWindow
ShopWindow Game.UI.ShopItem.shopWindow private
Definition at line 29 of file ShopItem.cs.
Property Documentation
Id
long Game.UI.ShopItem.Id get private set
Definition at line 31 of file ShopItem.cs.
 { get; private set; }
Referenced by Game.UI.ShopItem.Buy(), and Game.UI.ShopItem.Init().
Owned
bool Game.UI.ShopItem.Owned get private set
Definition at line 33 of file ShopItem.cs.
 { get; private set; }
Referenced by Game.UI.ShopItem.Bought(), and Game.UI.ShopItem.Init().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/ShopItem.cs