Thesis: Utility.ModalWindow Class Reference
Utility.ModalWindow Class Reference
Modal window for alerting the user
Public Member Functions
void Show ()
Show the modal window
void Show (string title, string content, Action onOkAction=null)
Show the modal window with custom content
void Hide ()
Hides the modal window
void ConfirmButtonClick ()
Action for ok buttton
Private Attributes
TMP_Text ModalTitleText
Reference to the modal title's text object
TMP_Text ModalContentText
Reference to the modal content's text object
Action onOkAction
What to do when the user presses the ok button
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Modal window for alerting the user
Definition at line 10 of file ModalWindowScript.cs.
Member Function Documentation
Show() [1/2]
void Utility.ModalWindow.Show () inline
Show the modal window
Definition at line 32 of file ModalWindowScript.cs.
         {
             if (this.Destroyed)
             {
                 return;
             }
             //Error detection if it been destroyed somehow... can only happen in testing...
             try
             {
                 this.gameObject.SetActive(true);
             }
             catch (MissingReferenceException)
             {
                 return;
             }
         }
References Utility.ThreadSafeMonoBehaviour.Destroyed.
Referenced by User.UserController.SendRegister(), Utility.ModalWindow.Show(), User.UserController.ShowLoginError(), User.UserController.ShowRegisterError(), Game.UI.GameUI.ShowRequestFail(), Game.UI.LeaderboardWindow.ShowRequestFail(), Game.UI.ShopWindow.ShowRequestFail(), MainPage.MainWindowController.ShowRequestFail(), MainPage.FriendWindowHandler.ShowRequestFail(), MainPage.TaskHistoryWindowHandler.ShowRequestFail(), and MainPage.MainWindowController.ShowTaskFail().
Show() [2/2]
void Utility.ModalWindow.Show (string title, string content, Action onOkAction = null) inline
Show the modal window with custom content
Parameters
title The modal window's title
content What should the content be
onOkAction What to do when the ok buttton is pressed
Definition at line 55 of file ModalWindowScript.cs.
         {
             if (this.Destroyed)
             {
                 return;
             }
             //Error detection if it been destroyed somehow... can only happen in testing...
             try
             {
                 this.ModalTitleText.text = title;
                 this.ModalContentText.text = content;
                 this.onOkAction = onOkAction;
                 Show();
             }
             catch (MissingReferenceException)
             {
                 return;
             }
         }
References Utility.ThreadSafeMonoBehaviour.Destroyed, Utility.ModalWindow.onOkAction, and Utility.ModalWindow.Show().
Hide()
void Utility.ModalWindow.Hide () inline
Hides the modal window
Definition at line 79 of file ModalWindowScript.cs.
         {
             if (this.Destroyed)
             {
                 return;
             }
             this.gameObject.SetActive(false);
         }
References Utility.ThreadSafeMonoBehaviour.Destroyed.
Referenced by Utility.ModalWindow.ConfirmButtonClick().
ConfirmButtonClick()
void Utility.ModalWindow.ConfirmButtonClick () inline
Action for ok buttton
Definition at line 91 of file ModalWindowScript.cs.
         {
             if (onOkAction is not null)
             {
                 onOkAction();
             }
             Hide();
         }
References Utility.ModalWindow.Hide(), and Utility.ModalWindow.onOkAction.
Member Data Documentation
ModalTitleText
TMP_Text Utility.ModalWindow.ModalTitleText private
Reference to the modal title's text object
Definition at line 16 of file ModalWindowScript.cs.
ModalContentText
TMP_Text Utility.ModalWindow.ModalContentText private
Reference to the modal content's text object
Definition at line 22 of file ModalWindowScript.cs.
onOkAction
Action Utility.ModalWindow.onOkAction private
What to do when the user presses the ok button
Definition at line 27 of file ModalWindowScript.cs.
Referenced by Utility.ModalWindow.ConfirmButtonClick(), and Utility.ModalWindow.Show().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Utility/ModalWindowScript.cs