Thesis: User.UserController Class Reference
User.UserController Class Reference
Handles the user actions such as registering and login.
Public Member Functions
void SendLogin ()
Send a login request with the login panel's fields.
void SendRegister ()
Send a register request with the register panel's fields.
bool IsValidEmail (string emailaddress)
Check if the email is valid.
void MoveToRegisterWindow ()
Change panels.
void MoveToLoginWindow ()
Change panels.
Public Attributes
GameObject LoginPanel
The login controls.
Private Member Functions
void Start ()
Start is called before the first frame update.
void CheckLoggedIn ()
Send a request to check if the user has logged in already.
void LoggedIn (Thesis_backend.Data_Structures.User result)
When the login request's was responded log the user in.
void ShowRegisterError (string content)
Show the register error on the modal window.
void ShowLoginError (string content)
Show the login error on the modal window.
void Registered (Thesis_backend.Data_Structures.User loggedInUser)
When the register request was responded successfully register the user and log him in.
IEnumerator MoveToMainScence ()
Move from the user creation and login scene.
Private Attributes
GameObject registerPanel
The register controls.
ModalWindow modalWindow
Modal window to alert the user.
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed.
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed.
Detailed Description
Handles the user actions such as registering and login.
Definition at line 16 of file UserController.cs.
Member Function Documentation
Start()
void User.UserController.Start () inline private
Start is called before the first frame update.
Definition at line 39 of file UserController.cs.
        {
            //Cap the fps to 60
            Application.targetFrameRate = 60;
            QualitySettings.vSyncCount = 0;
            //Check if the user is logged in, so the user doesn't need to log in if not necessary
            CheckLoggedIn();
        }
References User.UserController.CheckLoggedIn().
CheckLoggedIn()
void User.UserController.CheckLoggedIn () inline private
Send a request to check if the user has logged in already.
Definition at line 52 of file UserController.cs.
        {
            //If the user is still cached in the RAM move him to the main page
            if (UserData.Instance.LoggedIn)
            {
                MoveToMainScence();
                return;
            }
            CoroutineRunner.RunCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORCHECKLOGGEDIN, LoggedIn));
        }
References User.UserData.Instance, User.UserController.LoggedIn(), User.UserData.LoggedIn, User.UserController.MoveToMainScence(), Config.ServerConfig.PATHFORCHECKLOGGEDIN, and Utility.CoroutineRunner.RunCoroutine().
Referenced by User.UserController.Start().
SendLogin()
void User.UserController.SendLogin () inline
Send a login request with the login panel's fields.
Definition at line 67 of file UserController.cs.
        {
            TMPro.TMP_InputField[] fields = LoginPanel.GetComponentsInChildren<TMPro.TMP_InputField>();
            UserLoginRequest userLoginRequest = new UserLoginRequest()
            {
                UserIdentification = fields[0].text,
                Password = fields[1].text,
            };
            CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORLOGIN, userLoginRequest, LoggedIn, onFailedAction: ShowLoginError));
        }
References User.UserController.LoggedIn(), User.UserController.LoginPanel, Config.ServerConfig.PATHFORLOGIN, Utility.CoroutineRunner.RunCoroutine(), and User.UserController.ShowLoginError().
LoggedIn()
void User.UserController.LoggedIn (Thesis_backend::Data_Structures::User result) inline private
When the login request's was responded log the user in.
Parameters
result The server's response
Definition at line 84 of file UserController.cs.
        {
            UserData.Instance.Init(result);
            CoroutineRunner.RunCoroutine(MoveToMainScence());
        }
References User.UserData.Init(), User.UserData.Instance, User.UserController.MoveToMainScence(), and Utility.CoroutineRunner.RunCoroutine().
Referenced by User.UserController.CheckLoggedIn(), and User.UserController.SendLogin().
SendRegister()
void User.UserController.SendRegister () inline
Send a register request with the register panel's fields.
Definition at line 93 of file UserController.cs.
        {
            TMPro.TMP_InputField[] fields = registerPanel.GetComponentsInChildren<TMPro.TMP_InputField>();
            //Validate the register inputs locally
            if (!IsValidEmail(fields[0].text))
            {
                modalWindow.Show("Register error", "This is not a valid email!");
                return;
            }
            if (fields[2].text != fields[3].text)
            {
                modalWindow.Show("Register error", "Passwords does not match!");
                return;
            }
            UserRequest userRequest = new UserRequest()
            {
                UserName = fields[1].text,
                Email = fields[0].text,
                Password = fields[2].text,
            };
            //Send the request
            CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORREGISTER, userRequest, Registered, onFailedAction: ShowRegisterError));
        }
References Thesis_backend.Data_Structures.Email, User.UserController.IsValidEmail(), User.UserController.modalWindow, Config.ServerConfig.PATHFORREGISTER, Thesis_backend.Data_Structures.Registered, User.UserController.registerPanel, Utility.CoroutineRunner.RunCoroutine(), Utility.ModalWindow.Show(), and User.UserController.ShowRegisterError().
ShowRegisterError()
void User.UserController.ShowRegisterError (string content) inline private
Show the register error on the modal window.
Parameters
content What to show
Definition at line 122 of file UserController.cs.
        {
            modalWindow.Show("Register error", content);
        }
References User.UserController.modalWindow, and Utility.ModalWindow.Show().
Referenced by User.UserController.SendRegister().
ShowLoginError()
void User.UserController.ShowLoginError (string content) inline private
Show the login error on the modal window.
Parameters
content What to show
Definition at line 131 of file UserController.cs.
        {
            modalWindow.Show("Login error", content);
        }
References User.UserController.modalWindow, and Utility.ModalWindow.Show().
Referenced by User.UserController.SendLogin().
Registered()
void User.UserController.Registered (Thesis_backend::Data_Structures::User loggedInUser) inline private
When the register request was responded successfully register the user and log him in.
Parameters
loggedInUser The registered user's data
Definition at line 140 of file UserController.cs.
        {
            UserData.Instance.Init(loggedInUser);
            CoroutineRunner.RunCoroutine(MoveToMainScence());
        }
References User.UserData.Init(), User.UserData.Instance, User.UserController.MoveToMainScence(), and Utility.CoroutineRunner.RunCoroutine().
MoveToMainScence()
IEnumerator User.UserController.MoveToMainScence () inline private
Move from the user creation and login scene.
Definition at line 149 of file UserController.cs.
        {
            AsyncOperation loading = SceneManager.LoadSceneAsync("MainScene", LoadSceneMode.Single);
            while (!loading.isDone)
            {
                yield return null;
            }
        }
Referenced by User.UserController.CheckLoggedIn(), User.UserController.LoggedIn(), and User.UserController.Registered().
IsValidEmail()
bool User.UserController.IsValidEmail (string emailaddress) inline
Check if the email is valid.
Parameters
emailaddress The email to validate
Returns
true-correct false-sus
Definition at line 164 of file UserController.cs.
        {
            try
            {
                if (emailaddress == "")
                {
                    return false;
                }
                MailAddress m = new MailAddress(emailaddress);
                return true;
            }
            catch (FormatException)
            {
                return false;
            }
        }
Referenced by User.UserController.SendRegister().
MoveToRegisterWindow()
void User.UserController.MoveToRegisterWindow () inline
Change panels.
Definition at line 186 of file UserController.cs.
        {
            registerPanel.SetActive(true);
            LoginPanel.SetActive(false);
        }
References User.UserController.LoginPanel, and User.UserController.registerPanel.
MoveToLoginWindow()
void User.UserController.MoveToLoginWindow () inline
Change panels.
Definition at line 195 of file UserController.cs.
        {
            registerPanel.SetActive(false);
            LoginPanel.SetActive(true);
        }
References User.UserController.LoginPanel, and User.UserController.registerPanel.
Member Data Documentation
LoginPanel
GameObject User.UserController.LoginPanel
The login controls.
Definition at line 22 of file UserController.cs.
Referenced by User.UserController.MoveToLoginWindow(), User.UserController.MoveToRegisterWindow(), and User.UserController.SendLogin().
registerPanel
GameObject User.UserController.registerPanel private
The register controls.
Definition at line 28 of file UserController.cs.
Referenced by User.UserController.MoveToLoginWindow(), User.UserController.MoveToRegisterWindow(), and User.UserController.SendRegister().
modalWindow
ModalWindow User.UserController.modalWindow private
Modal window to alert the user.
Definition at line 34 of file UserController.cs.
Referenced by User.UserController.SendRegister(), User.UserController.ShowLoginError(), and User.UserController.ShowRegisterError().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/User/UserController.cs