Thesis: LeaderboardWindow Class Reference
LeaderboardWindow Class Reference
Public Member Functions
void Show ()
void Hide ()
void LoadScores ()
Private Member Functions
void ShowRequestFail (string content)
void LoadedScores (List< GameScore > gameScores)
Private Attributes
GameObject scoreParent
TMP_Dropdown filterTypeDropdown
ModalWindow ModalWindow
GameObject LeaderboardItemPrefab
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Detailed Description
Definition at line 9 of file LeaderboardWindow.cs.
Member Function Documentation
Show()
void LeaderboardWindow.Show () inline
Definition at line 23 of file LeaderboardWindow.cs.
    {
        this.gameObject.SetActive(true);
        LoadScores();
    }
References LoadScores().
Referenced by GameUI.ShowLeaderboard().
Hide()
void LeaderboardWindow.Hide () inline
Definition at line 29 of file LeaderboardWindow.cs.
    {
        this.gameObject.SetActive(false);
    }
LoadScores()
void LeaderboardWindow.LoadScores () inline
Definition at line 34 of file LeaderboardWindow.cs.
    {
        DateTime filterSince = DateTime.Now;
        switch ((LeaderboardFilterType)filterTypeDropdown.value)
        {
            case LeaderboardFilterType.AllTime:
                filterSince = DateTime.MinValue;
                break;
            case LeaderboardFilterType.ThisYear:
                filterSince = DateTime.UtcNow.AddYears(-1);
                break;
            case LeaderboardFilterType.ThisMonth:
                filterSince = DateTime.UtcNow.AddMonths(-1);
                break;
            case LeaderboardFilterType.ThisWeek:
                filterSince = DateTime.UtcNow.AddDays(-7);
                break;
            case LeaderboardFilterType.Today:
                filterSince = DateTime.UtcNow.AddDays(-1);
                break;
            default:
                Debug.LogError("No such leaderboard filter type is known");
                break;
        }
        CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<GameScore>>(ServerConfig.PATH_FOR_GET_GAME_SCORES(filterSince), LoadedScores, onFailedAction: ShowRequestFail));
    }
References filterTypeDropdown, LoadedScores(), Config.ServerConfig.PATH_FOR_GET_GAME_SCORES(), CoroutineRunner.RunCoroutine(), and ShowRequestFail().
Referenced by Show().
ShowRequestFail()
void LeaderboardWindow.ShowRequestFail (string content) inline private
Definition at line 67 of file LeaderboardWindow.cs.
    {
        ModalWindow.Show("Leaderboard error", content);
    }
References ModalWindow.Show().
Referenced by LoadScores().
LoadedScores()
void LeaderboardWindow.LoadedScores (List< GameScore > gameScores) inline private
Definition at line 72 of file LeaderboardWindow.cs.
    {
        if (scoreParent == null || this.scoreParent.transform == null)
        {
            // Exit or handle the case when the Score parent is destroyed
            Debug.LogWarning("Score parent has been destroyed or is missing.");
            return;
        }
        //Delete the previous ones
        for (int i = 0; i < this.scoreParent.transform.childCount; i++)
        {
            Destroy(this.scoreParent.transform.GetChild(i).gameObject);
        }
        this.scoreParent.transform.DetachChildren();
        foreach (var item in gameScores)
        {
            LeaderboardItem leaderboardItem = Instantiate(LeaderboardItemPrefab, scoreParent.transform).GetComponent<LeaderboardItem>();
            leaderboardItem.Init(item.OwnerName, item.Score);
        }
    }
References LeaderboardItem.Init(), LeaderboardItemPrefab, and scoreParent.
Referenced by LoadScores().
Member Data Documentation
scoreParent
GameObject LeaderboardWindow.scoreParent private
Definition at line 12 of file LeaderboardWindow.cs.
Referenced by LoadedScores().
filterTypeDropdown
TMP_Dropdown LeaderboardWindow.filterTypeDropdown private
Definition at line 15 of file LeaderboardWindow.cs.
Referenced by LoadScores().
ModalWindow
ModalWindow LeaderboardWindow.ModalWindow private
Definition at line 18 of file LeaderboardWindow.cs.
LeaderboardItemPrefab
GameObject LeaderboardWindow.LeaderboardItemPrefab private
Definition at line 21 of file LeaderboardWindow.cs.
Referenced by LoadedScores().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/LeaderboardWindow.cs