Thesis: Game.UI.LeaderboardWindow Class Reference
Game.UI.LeaderboardWindow Class Reference
Handles the leaderboard display window
Public Member Functions
void Show ()
Show the window
void Hide ()
Hide the window
void LoadScores ()
Load the scores
Private Member Functions
void ShowRequestFail (string content)
Show if the request failed in the modal
void LoadedScores (List< GameScore > gameScores)
Callback after the scores were loaded
Private Attributes
GameObject scoreParent
Reference to where to put the items
TMP_Dropdown filterTypeDropdown
Drop down of how recent scores should be shown
ModalWindow ModalWindow
Reference to the scene's modal window
GameObject LeaderboardItemPrefab
The prefab of a single leaderboard item
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Handles the leaderboard display window
Definition at line 18 of file LeaderboardWindow.cs.
Member Function Documentation
Show()
void Game.UI.LeaderboardWindow.Show () inline
Show the window
Definition at line 47 of file LeaderboardWindow.cs.
             {
                 this.gameObject.SetActive(true);
                 LoadScores();
             }
References Game.UI.LeaderboardWindow.LoadScores().
Referenced by Game.UI.GameUI.ShowLeaderboard().
Hide()
void Game.UI.LeaderboardWindow.Hide () inline
Hide the window
Definition at line 56 of file LeaderboardWindow.cs.
             {
                 this.gameObject.SetActive(false);
             }
LoadScores()
void Game.UI.LeaderboardWindow.LoadScores () inline
Load the scores
Definition at line 64 of file LeaderboardWindow.cs.
             {
                 DateTime filterSince = DateTime.Now;
                 //Determine what date was selected
                 switch ((LeaderboardFilterType)filterTypeDropdown.value)
                 {
                     case LeaderboardFilterType.AllTime:
                         filterSince = DateTime.MinValue;
                         break;
                     case LeaderboardFilterType.ThisYear:
                         filterSince = DateTime.UtcNow.AddYears(-1);
                         break;
                     case LeaderboardFilterType.ThisMonth:
                         filterSince = DateTime.UtcNow.AddMonths(-1);
                         break;
                     case LeaderboardFilterType.ThisWeek:
                         filterSince = DateTime.UtcNow.AddDays(-7);
                         break;
                     case LeaderboardFilterType.Today:
                         filterSince = DateTime.UtcNow.AddDays(-1);
                         break;
                     default:
                         Debug.LogError("No such leaderboard filter type is known");
                         break;
                 }
                 CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<GameScore>>(ServerConfig.PATH_FOR_GET_GAME_SCORES(filterSince), LoadedScores, onFailedAction: ShowRequestFail));
             }
References Game.UI.LeaderboardWindow.filterTypeDropdown, Game.UI.LeaderboardWindow.LoadedScores(), Config.ServerConfig.PATH_FOR_GET_GAME_SCORES(), Utility.CoroutineRunner.RunCoroutine(), and Game.UI.LeaderboardWindow.ShowRequestFail().
Referenced by Game.UI.LeaderboardWindow.Show().
ShowRequestFail()
void Game.UI.LeaderboardWindow.ShowRequestFail (string content) inline private
Show if the request failed in the modal
Parameters
content The content to display
Definition at line 102 of file LeaderboardWindow.cs.
             {
                 ModalWindow.Show("Leaderboard error", content);
             }
References Utility.ModalWindow.Show().
Referenced by Game.UI.LeaderboardWindow.LoadScores().
LoadedScores()
void Game.UI.LeaderboardWindow.LoadedScores (List< GameScore > gameScores) inline private
Callback after the scores were loaded
Parameters
gameScores The game scores
Definition at line 111 of file LeaderboardWindow.cs.
             {
                 if (scoreParent == null || this.scoreParent.transform == null)
                 {
                     // Exit or handle the case when the Score parent is destroyed
                     Debug.LogWarning("Score parent has been destroyed or is missing.");
                     return;
                 }
                 //Delete the previous ones
                 for (int i = 0; i < this.scoreParent.transform.childCount; i++)
                 {
                     Destroy(this.scoreParent.transform.GetChild(i).gameObject);
                 }
                 this.scoreParent.transform.DetachChildren();
                 foreach (var item in gameScores)
                 {
                     LeaderboardItem leaderboardItem = Instantiate(LeaderboardItemPrefab, scoreParent.transform).GetComponent<LeaderboardItem>();
                     leaderboardItem.Init(item.OwnerName, item.Score);
                 }
             }
References Game.UI.LeaderboardItem.Init(), Game.UI.LeaderboardWindow.LeaderboardItemPrefab, and Game.UI.LeaderboardWindow.scoreParent.
Referenced by Game.UI.LeaderboardWindow.LoadScores().
Member Data Documentation
scoreParent
GameObject Game.UI.LeaderboardWindow.scoreParent private
Reference to where to put the items
Definition at line 24 of file LeaderboardWindow.cs.
Referenced by Game.UI.LeaderboardWindow.LoadedScores().
filterTypeDropdown
TMP_Dropdown Game.UI.LeaderboardWindow.filterTypeDropdown private
Drop down of how recent scores should be shown
Definition at line 30 of file LeaderboardWindow.cs.
Referenced by Game.UI.LeaderboardWindow.LoadScores().
ModalWindow
ModalWindow Game.UI.LeaderboardWindow.ModalWindow private
Reference to the scene's modal window
Definition at line 36 of file LeaderboardWindow.cs.
LeaderboardItemPrefab
GameObject Game.UI.LeaderboardWindow.LeaderboardItemPrefab private
The prefab of a single leaderboard item
Definition at line 42 of file LeaderboardWindow.cs.
Referenced by Game.UI.LeaderboardWindow.LoadedScores().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/LeaderboardWindow.cs