Thesis: MainPage.FriendHandler Class Reference
MainPage.FriendHandler Class Reference
Handles a single friend entry display
Public Member Functions
void InitValues (Friend friend)
Inititializes a new display with the given friend to display
void AcceptFriendRequest ()
Send a request to the server that the user accepted the friend request
void DeleteFriend ()
Send a request to the server that the user deleted this friend
Properties
Friend Friend [get, private set]
Reference to the friend which is being displayed here
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Private Member Functions
void Accepted (Thesis_backend.Data_Structures.Friend result)
After the server responded successfully to the friend accept
void Deleted (string result)
After the server responded successfully to the friend delete
Private Attributes
TMP_Text friendNameLabel
Label to display the friend's name
TMP_Text scoreText
Label to display the friend's total score
TMP_Text scoreLabelText
Label to write out "Score:" referenced so we can hide it or show
Button acceptButton
Button to accept the friend request
TMP_Text pendingtext
Text to show if the friend request is still pending
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Detailed Description
Handles a single friend entry display
Definition at line 13 of file FriendHandler.cs.
Member Function Documentation
InitValues()
void MainPage.FriendHandler.InitValues (Friend friend) inline
Inititializes a new display with the given friend to display
Parameters
friend The friend to display
Definition at line 54 of file FriendHandler.cs.
         {
             this.Friend = friend;
             this.acceptButton.gameObject.SetActive(Friend.Pending);
             //Determine which user to show
             if (UserData.Instance.Id != this.Friend.Sender.ID)
             {
                 friendNameLabel.text = this.Friend.Sender.Username;
                 scoreText.text = this.Friend.Sender.TotalScore.ToString();
                 if (Friend.Pending)
                 {
                     acceptButton.gameObject.SetActive(true);
                 }
             }
             //If the current user is the receiver show him the accept button
             else
             {
                 friendNameLabel.text = this.Friend.Receiver.Username;
                 scoreText.text = this.Friend.Receiver.TotalScore.ToString();
                 if (friend.Pending)
                 {
                     acceptButton.gameObject.SetActive(false);
                     pendingtext.gameObject.SetActive(true);
                 }
             }
             this.scoreText.gameObject.SetActive(!friend.Pending);
             this.scoreLabelText.gameObject.SetActive(!friend.Pending);
         }
References MainPage.FriendHandler.Friend, MainPage.FriendHandler.friendNameLabel, User.UserData.Id, User.UserData.Instance, Thesis_backend.Data_Structures.Pending, and MainPage.FriendHandler.pendingtext.
Referenced by MainPage.FriendWindowHandler.DisplayFriends(), and MainPage.FriendWindowHandler.SentFriendRequest().
AcceptFriendRequest()
void MainPage.FriendHandler.AcceptFriendRequest () inline
Send a request to the server that the user accepted the friend request
Definition at line 87 of file FriendHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Friend>(ServerConfig.PATH_FOR_FRIEND_ACCEPT(this.Friend.ID), onComplete: Accepted));
         }
References MainPage.FriendHandler.Accepted(), Config.ServerConfig.PATH_FOR_FRIEND_ACCEPT(), and CoroutineRunner.RunCoroutine().
DeleteFriend()
void MainPage.FriendHandler.DeleteFriend () inline
Send a request to the server that the user deleted this friend
Definition at line 95 of file FriendHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATH_FOR_FRIEND_DELETE(this.Friend.ID), onComplete: Deleted));
         }
References MainPage.FriendHandler.Deleted(), Config.ServerConfig.PATH_FOR_FRIEND_DELETE(), and CoroutineRunner.RunCoroutine().
Accepted()
void MainPage.FriendHandler.Accepted (Thesis_backend.Data_Structures.Friend result) inline private
After the server responded successfully to the friend accept
Parameters
result Accepted friend
Definition at line 104 of file FriendHandler.cs.
         {
             this.Friend.Pending = false;
             this.acceptButton.gameObject.SetActive(false);
             this.scoreText.gameObject.SetActive(true);
             this.scoreLabelText.gameObject.SetActive(true);
         }
References MainPage.FriendHandler.Friend.
Referenced by MainPage.FriendHandler.AcceptFriendRequest().
Deleted()
void MainPage.FriendHandler.Deleted (string result) inline private
After the server responded successfully to the friend delete
Parameters
result Delete result
Definition at line 116 of file FriendHandler.cs.
         {
             if (result == "Deleted")
             {
                 Destroy(this.gameObject);
             }
         }
Referenced by MainPage.FriendHandler.DeleteFriend().
Member Data Documentation
friendNameLabel
TMP_Text MainPage.FriendHandler.friendNameLabel private
Label to display the friend's name
Definition at line 19 of file FriendHandler.cs.
Referenced by MainPage.FriendHandler.InitValues().
scoreText
TMP_Text MainPage.FriendHandler.scoreText private
Label to display the friend's total score
Definition at line 25 of file FriendHandler.cs.
scoreLabelText
TMP_Text MainPage.FriendHandler.scoreLabelText private
Label to write out "Score:" referenced so we can hide it or show
Definition at line 31 of file FriendHandler.cs.
acceptButton
Button MainPage.FriendHandler.acceptButton private
Button to accept the friend request
Definition at line 37 of file FriendHandler.cs.
pendingtext
TMP_Text MainPage.FriendHandler.pendingtext private
Text to show if the friend request is still pending
Definition at line 43 of file FriendHandler.cs.
Referenced by MainPage.FriendHandler.InitValues().
Property Documentation
Friend
Friend MainPage.FriendHandler.Friend get private set
Reference to the friend which is being displayed here
Definition at line 48 of file FriendHandler.cs.
 { get; private set; }
Referenced by MainPage.FriendHandler.Accepted(), and MainPage.FriendHandler.InitValues().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/DisplayElements/FriendHandler.cs