Thesis: MainPage.TaskOpenPanelController Class Reference
MainPage.TaskOpenPanelController Class Reference
Controller for displaying, editing and creating tasks
Public Member Functions
void OpenUp ()
Open up the panel
void OpenUp (PlayerTask taskContainer=null, TaskType type=TaskType.GoodTask)
Open's the panel with the task's values added also
void MakeItBadHabit ()
Make this task a bad habit
void MakeItGoodTask ()
Make it a good task
void Cancel ()
Cancel this edit/task creation
void Save ()
Save the task to the server
void DeleteTask ()
Send a delete task request to the server
Public Attributes
EventHandler< TaskClosedEventArgs > TaskClosedEventHandler
Event for when the window is closed
Static Public Attributes
static readonly int[] TASKINTERVALS = { 60, 120, 240, 1440, 2880, 10080, 20160, 40320 }
Task intervals
Properties
PlayerTask CurrentTask = new PlayerTask() { ID = -1 } [get, private set]
The current task which is being displayed/edited
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void SavedTask (Thesis_backend.Data_Structures.PlayerTask savedTask)
When the task was stored on the server show it also visually and close the panel
void DeletedTask (string result)
After the task were deleted from the server delete it also from the client
void CollectFromFields ()
Collect the values from the inputs
void UpdateButtons ()
Update the buttons with the appropriate color based on the current task
Private Attributes
TMP_InputField taskNameInput
Input for the task's name
TMP_Dropdown taskIntervals
Input dropdown for the task intervals
TMP_InputField descriptionInput
Input for the task's description
Button goodTaskButton
Make the task good
Button badHabitButton
Make the task bad
MainWindowController uIController
Reference to the ui controller
Button deleteTaskButton
Delete button for the task
bool isNewTask = false
Is the task a new one
PlayerTask playerTaskOnOpen
What was the task when the task was opened so we can revert back on cancel
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Controller for displaying, editing and creating tasks
Definition at line 15 of file TaskOpenPanelController.cs.
Member Function Documentation
OpenUp() [1/2]
void MainPage.TaskOpenPanelController.OpenUp () inline
Open up the panel
Definition at line 90 of file TaskOpenPanelController.cs.
         {
             if (this.CurrentTask is not null)
             {
                 OpenUp(type: this.CurrentTask.TaskType ? TaskType.BadHabit : TaskType.GoodTask);
             }
             else
             {
                 OpenUp(null);
             }
         }
References MainPage.TaskOpenPanelController.CurrentTask.
Referenced by MainPage.TaskDisplayHandler.OpenEditor().
OpenUp() [2/2]
void MainPage.TaskOpenPanelController.OpenUp (PlayerTask taskContainer = null, TaskType type = TaskType.GoodTask) inline
Open's the panel with the task's values added also
Parameters
taskContainer The task to load
type The type of the task
Definition at line 107 of file TaskOpenPanelController.cs.
         {
             try
             {
                 //If the task is null create a dummy otherwise load it
                 if (taskContainer is not null)
                 {
                     this.CurrentTask = taskContainer;
                     this.isNewTask = false;
                     //Create a deep copy
                     this.playerTaskOnOpen = new PlayerTask(taskContainer);
                 }
                 else
                 {
                     this.CurrentTask = new PlayerTask() { ID = -1 };
                     this.CurrentTask.ChangeType(type);
                     this.isNewTask = true;
                     this.playerTaskOnOpen = null;
                 }
                 taskNameInput.text = this.CurrentTask.TaskName;
                 descriptionInput.text = this.CurrentTask.Description;
                 for (int i = 0; i < TASKINTERVALS.Length; i++)
                 {
                     if (TASKINTERVALS[i] == (int)this.CurrentTask.PeriodRate)
                     {
                         taskIntervals.SetValueWithoutNotify(i);
                         break;
                     }
                 }
                 //Show/Hide the delete button
                 deleteTaskButton.gameObject.SetActive(!isNewTask);
                 this.gameObject.SetActive(true);
                 UpdateButtons();
             }
             catch (MissingReferenceException)
             {
                 Debug.LogWarning("Task open panel had a destroyed game object");
             }
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.TaskOpenPanelController.deleteTaskButton, MainPage.TaskOpenPanelController.isNewTask, Thesis_backend.Data_Structures.PlayerTask, MainPage.TaskOpenPanelController.TASKINTERVALS, MainPage.TaskOpenPanelController.taskNameInput, and MainPage.TaskOpenPanelController.UpdateButtons().
MakeItBadHabit()
void MainPage.TaskOpenPanelController.MakeItBadHabit () inline
Make this task a bad habit
Definition at line 152 of file TaskOpenPanelController.cs.
         {
             this.CurrentTask?.ChangeType(TaskType.BadHabit);
             UpdateButtons();
             uIController.LoadBadHabits(false);
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.MainWindowController.LoadBadHabits(), MainPage.TaskOpenPanelController.uIController, and MainPage.TaskOpenPanelController.UpdateButtons().
Referenced by MainPage.MainWindowController.LoadBadHabits().
MakeItGoodTask()
void MainPage.TaskOpenPanelController.MakeItGoodTask () inline
Make it a good task
Definition at line 163 of file TaskOpenPanelController.cs.
         {
             this.CurrentTask?.ChangeType(TaskType.GoodTask);
             UpdateButtons();
             uIController.LoadGoodTasks(false);
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.MainWindowController.LoadGoodTasks(), MainPage.TaskOpenPanelController.uIController, and MainPage.TaskOpenPanelController.UpdateButtons().
Referenced by MainPage.MainWindowController.LoadGoodTasks().
Cancel()
void MainPage.TaskOpenPanelController.Cancel () inline
Cancel this edit/task creation
Definition at line 174 of file TaskOpenPanelController.cs.
         {
             try
             {
                 //If it wasn't a new task revert it to the previous state
                 if (this.CurrentTask.ID != -1)
                 {
                     if (playerTaskOnOpen is not null)
                     {
                         CurrentTask.UpdateValues(playerTaskOnOpen);
                         if (playerTaskOnOpen.TaskType)
{
                             uIController.LoadBadHabits();
                         }
                         else
{
                             uIController.LoadGoodTasks();
                         }
                         this.CurrentTask = playerTaskOnOpen;
                     }
                 }
                 this.CurrentTask = new PlayerTask() { ID = -1 };
                 this.gameObject.SetActive(false);
             }
             catch (MissingReferenceException)
             {
                 Debug.LogWarning("Missing reference task open panel in cancel");
             }
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.MainWindowController.LoadBadHabits(), MainPage.MainWindowController.LoadGoodTasks(), Thesis_backend.Data_Structures.PlayerTask, MainPage.TaskOpenPanelController.playerTaskOnOpen, and MainPage.TaskOpenPanelController.uIController.
Referenced by MainPage.TaskOpenPanelController.DeletedTask().
Save()
void MainPage.TaskOpenPanelController.Save () inline
Save the task to the server
Definition at line 208 of file TaskOpenPanelController.cs.
         {
             //Collect the values from the inputs
             CollectFromFields();
             TaskRequest taskRequest = new TaskRequest()
             {
                 TaskName = this.CurrentTask.TaskName,
                 Description = this.CurrentTask.Description,
                 PeriodRate = (int)CurrentTask.PeriodRate,
                 TaskType = Convert.ToBoolean(CurrentTask.TaskType)
             };
             //If it is a new one call the create endpoint for the task otherwise the update one
             if (isNewTask)
             {
                 CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKCREATE, taskRequest, SavedTask, onFailedAction: uIController.ShowTaskFail));
             }
             else
             {
                 CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKUPDATE(CurrentTask.ID), taskRequest, SavedTask, onFailedAction: uIController.ShowTaskFail));
             }
         }
References MainPage.TaskOpenPanelController.CollectFromFields(), MainPage.TaskOpenPanelController.CurrentTask, Thesis_backend.Data_Structures.Description, MainPage.TaskOpenPanelController.isNewTask, Config.ServerConfig.PATHFORTASKCREATE, Config.ServerConfig.PATHFORTASKUPDATE(), Thesis_backend.Data_Structures.PeriodRate, Utility.CoroutineRunner.RunCoroutine(), MainPage.TaskOpenPanelController.SavedTask(), MainPage.MainWindowController.ShowTaskFail(), Thesis_backend.Data_Structures.TaskName, and MainPage.TaskOpenPanelController.uIController.
SavedTask()
void MainPage.TaskOpenPanelController.SavedTask (Thesis_backend.Data_Structures.PlayerTask savedTask) inline private
When the task was stored on the server show it also visually and close the panel
Parameters
savedTask The Task which was recieved from the server
Definition at line 235 of file TaskOpenPanelController.cs.
         {
             this.TaskClosedEventHandler?.Invoke(this, new TaskClosedEventArgs(true));
             this.gameObject.SetActive(false);
             this.CurrentTask = savedTask;
             //If it was a new task create it's prefab otherwise just update it
             if (isNewTask)
             {
                 uIController.CreateTask(this.CurrentTask);
             }
             else
             {
                 uIController.UpdateTaskLabel(CurrentTask.ID);
             }
             uIController.SortingChanged();
             this.CurrentTask = new PlayerTask() { ID = -1 };
         }
References MainPage.MainWindowController.CreateTask(), MainPage.TaskOpenPanelController.CurrentTask, MainPage.TaskOpenPanelController.isNewTask, Thesis_backend.Data_Structures.PlayerTask, MainPage.MainWindowController.SortingChanged(), MainPage.TaskOpenPanelController.uIController, and MainPage.MainWindowController.UpdateTaskLabel().
Referenced by MainPage.TaskOpenPanelController.Save().
DeleteTask()
void MainPage.TaskOpenPanelController.DeleteTask () inline
Send a delete task request to the server
Definition at line 256 of file TaskOpenPanelController.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORTASKDELETE(CurrentTask.ID), onComplete: DeletedTask, onFailedAction: uIController.ShowTaskFail));
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.TaskOpenPanelController.DeletedTask(), Config.ServerConfig.PATHFORTASKDELETE(), Utility.CoroutineRunner.RunCoroutine(), MainPage.MainWindowController.ShowTaskFail(), and MainPage.TaskOpenPanelController.uIController.
DeletedTask()
void MainPage.TaskOpenPanelController.DeletedTask (string result) inline private
After the task were deleted from the server delete it also from the client
Parameters
result The result of the deletion
Definition at line 265 of file TaskOpenPanelController.cs.
         {
             uIController.RemoveTask(CurrentTask.ID);
             Cancel();
         }
References MainPage.TaskOpenPanelController.Cancel(), MainPage.TaskOpenPanelController.CurrentTask, MainPage.MainWindowController.RemoveTask(), and MainPage.TaskOpenPanelController.uIController.
Referenced by MainPage.TaskOpenPanelController.DeleteTask().
CollectFromFields()
void MainPage.TaskOpenPanelController.CollectFromFields () inline private
Collect the values from the inputs
Definition at line 274 of file TaskOpenPanelController.cs.
         {
             string taskName = taskNameInput.text;
             string description = descriptionInput.text;
             TaskIntervals taskInterval = (TaskIntervals)TASKINTERVALS[taskIntervals.value];
             CurrentTask.UpdateValues(taskName, CurrentTask.TaskType, taskInterval, description);
         }
References MainPage.TaskOpenPanelController.CurrentTask, MainPage.TaskOpenPanelController.descriptionInput, MainPage.TaskOpenPanelController.taskIntervals, MainPage.TaskOpenPanelController.TASKINTERVALS, and MainPage.TaskOpenPanelController.taskNameInput.
Referenced by MainPage.TaskOpenPanelController.Save().
UpdateButtons()
void MainPage.TaskOpenPanelController.UpdateButtons () inline private
Update the buttons with the appropriate color based on the current task
Definition at line 285 of file TaskOpenPanelController.cs.
         {
             if (!this.CurrentTask.TaskType)
             {
                 goodTaskButton.image.color = new Color(134f / 255f, 1f, 90f / 255f, 1.0f);
                 badHabitButton.image.color = new Color(185 / 255f, 185f / 255f, 185f / 255f, 1f);
             }
             else
             {
                 goodTaskButton.image.color = new Color(185f / 255f, 185f / 255f, 185f / 255f, 1f);
                 badHabitButton.image.color = new Color(248f / 255f, 34f / 255f, 44f / 255f, 1f);
             }
         }
References MainPage.TaskOpenPanelController.badHabitButton, MainPage.TaskOpenPanelController.CurrentTask, and MainPage.TaskOpenPanelController.goodTaskButton.
Referenced by MainPage.TaskOpenPanelController.MakeItBadHabit(), MainPage.TaskOpenPanelController.MakeItGoodTask(), and MainPage.TaskOpenPanelController.OpenUp().
Member Data Documentation
TaskClosedEventHandler
EventHandler<TaskClosedEventArgs> MainPage.TaskOpenPanelController.TaskClosedEventHandler
Event for when the window is closed
Definition at line 27 of file TaskOpenPanelController.cs.
taskNameInput
TMP_InputField MainPage.TaskOpenPanelController.taskNameInput private
Input for the task's name
Definition at line 33 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.CollectFromFields(), and MainPage.TaskOpenPanelController.OpenUp().
taskIntervals
TMP_Dropdown MainPage.TaskOpenPanelController.taskIntervals private
Input dropdown for the task intervals
Definition at line 39 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.CollectFromFields().
descriptionInput
TMP_InputField MainPage.TaskOpenPanelController.descriptionInput private
Input for the task's description
Definition at line 45 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.CollectFromFields().
goodTaskButton
Button MainPage.TaskOpenPanelController.goodTaskButton private
Make the task good
Definition at line 51 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.UpdateButtons().
badHabitButton
Button MainPage.TaskOpenPanelController.badHabitButton private
Make the task bad
Definition at line 57 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.UpdateButtons().
uIController
MainWindowController MainPage.TaskOpenPanelController.uIController private
Reference to the ui controller
Definition at line 63 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.Cancel(), MainPage.TaskOpenPanelController.DeletedTask(), MainPage.TaskOpenPanelController.DeleteTask(), MainPage.TaskOpenPanelController.MakeItBadHabit(), MainPage.TaskOpenPanelController.MakeItGoodTask(), MainPage.TaskOpenPanelController.Save(), and MainPage.TaskOpenPanelController.SavedTask().
deleteTaskButton
Button MainPage.TaskOpenPanelController.deleteTaskButton private
Delete button for the task
Definition at line 69 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.OpenUp().
isNewTask
bool MainPage.TaskOpenPanelController.isNewTask = false private
Is the task a new one
Definition at line 74 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.OpenUp(), MainPage.TaskOpenPanelController.Save(), and MainPage.TaskOpenPanelController.SavedTask().
TASKINTERVALS
readonly int [] MainPage.TaskOpenPanelController.TASKINTERVALS = { 60, 120, 240, 1440, 2880, 10080, 20160, 40320 } static
Task intervals
Definition at line 79 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.CollectFromFields(), and MainPage.TaskOpenPanelController.OpenUp().
playerTaskOnOpen
PlayerTask MainPage.TaskOpenPanelController.playerTaskOnOpen private
What was the task when the task was opened so we can revert back on cancel
Definition at line 85 of file TaskOpenPanelController.cs.
Referenced by MainPage.TaskOpenPanelController.Cancel().
Property Documentation
CurrentTask
PlayerTask MainPage.TaskOpenPanelController.CurrentTask = new PlayerTask() { ID = -1 } get private set
The current task which is being displayed/edited
Definition at line 21 of file TaskOpenPanelController.cs.
 { get; private set; } = new PlayerTask() { ID = -1 };
Referenced by MainPage.TaskOpenPanelController.Cancel(), MainPage.TaskOpenPanelController.CollectFromFields(), MainPage.TaskOpenPanelController.DeletedTask(), MainPage.TaskOpenPanelController.DeleteTask(), MainPage.TaskOpenPanelController.MakeItBadHabit(), MainPage.TaskOpenPanelController.MakeItGoodTask(), MainPage.TaskOpenPanelController.OpenUp(), MainPage.TaskOpenPanelController.Save(), MainPage.TaskOpenPanelController.SavedTask(), MainPage.MainWindowController.SortingChanged(), and MainPage.TaskOpenPanelController.UpdateButtons().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/TaskOpenPanelController.cs