Bomberman: FriendWindowHandler Class Reference
FriendWindowHandler Class Reference
Public Member Functions
void ShowPendingChanged (bool newValue)
void Show ()
void SendFriendRequest ()
void Hide ()
Private Member Functions
void SentFriendRequest (Friend friend)
void LoadFriends ()
void DisplayFriends (List< Friend > friends)
Private Attributes
GameObject FriendsContainer
TMP_InputField userIdentificationInput
GameObject friendPrefab
bool showPending = true
Detailed Description
Definition at line 9 of file FriendWindowHandler.cs.
Member Function Documentation
ShowPendingChanged()
void FriendWindowHandler.ShowPendingChanged (bool newValue) inline
Definition at line 22 of file FriendWindowHandler.cs.
    {
        this.showPending = newValue;
        LoadFriends();
    }
References LoadFriends().
Show()
void FriendWindowHandler.Show () inline
Definition at line 28 of file FriendWindowHandler.cs.
    {
        this.gameObject.SetActive(true);
        LoadFriends();
    }
References LoadFriends().
SendFriendRequest()
void FriendWindowHandler.SendFriendRequest () inline
Definition at line 34 of file FriendWindowHandler.cs.
    {
        if (userIdentificationInput.text == "")
        {
            return;
        }
        StartCoroutine(Server.SendPostRequest<Friend>(ServerConfig.PATH_FOR_FRIEND_REQUEST_SEND, userIdentificationInput.text, onComplete: SentFriendRequest));
    }
References Thesis_backend.Data_Structures.Friend, Config.ServerConfig.PATH_FOR_FRIEND_REQUEST_SEND, SentFriendRequest(), and userIdentificationInput.
SentFriendRequest()
void FriendWindowHandler.SentFriendRequest (Friend friend) inline private
Definition at line 44 of file FriendWindowHandler.cs.
    {
        if (showPending)
        {
            FriendHandler friendDisplay = Instantiate(friendPrefab, this.FriendsContainer.transform).GetComponent<FriendHandler>();
            friendDisplay.InitValues(friend);
        }
    }
References friendPrefab, FriendHandler.InitValues(), and showPending.
Referenced by SendFriendRequest().
Hide()
void FriendWindowHandler.Hide () inline
Definition at line 53 of file FriendWindowHandler.cs.
    {
        this.gameObject.SetActive(false);
    }
LoadFriends()
void FriendWindowHandler.LoadFriends () inline private
Definition at line 58 of file FriendWindowHandler.cs.
    {
        StartCoroutine(Server.SendGetRequest<List<Friend>>(ServerConfig.PATH_FOR_FRIEND_GETALL, onComplete: DisplayFriends));
    }
References DisplayFriends(), and Config.ServerConfig.PATH_FOR_FRIEND_GETALL.
Referenced by Show(), and ShowPendingChanged().
DisplayFriends()
void FriendWindowHandler.DisplayFriends (List< Friend > friends) inline private
Definition at line 63 of file FriendWindowHandler.cs.
    {
        //Delete the previous ones
        for (int i = 0; i < this.FriendsContainer.transform.childCount; i++)
        {
            Destroy(this.FriendsContainer.transform.GetChild(i).gameObject);
        }
        this.FriendsContainer.transform.DetachChildren();
        foreach (var item in friends)
        {
            if (showPending)
            {
                FriendHandler friendDisplay = Instantiate(friendPrefab, this.FriendsContainer.transform).GetComponent<FriendHandler>();
                friendDisplay.InitValues(item);
            }
            else
            {
                if (!item.Pending)
                {
                    FriendHandler friendDisplay = Instantiate(friendPrefab, this.FriendsContainer.transform).GetComponent<FriendHandler>();
                    friendDisplay.InitValues(item);
                }
            }
        }
    }
References friendPrefab, FriendHandler.InitValues(), and showPending.
Referenced by LoadFriends().
Member Data Documentation
FriendsContainer
GameObject FriendWindowHandler.FriendsContainer private
Definition at line 12 of file FriendWindowHandler.cs.
userIdentificationInput
TMP_InputField FriendWindowHandler.userIdentificationInput private
Definition at line 15 of file FriendWindowHandler.cs.
Referenced by SendFriendRequest().
friendPrefab
GameObject FriendWindowHandler.friendPrefab private
Definition at line 18 of file FriendWindowHandler.cs.
Referenced by DisplayFriends(), and SentFriendRequest().
showPending
bool FriendWindowHandler.showPending = true private
Definition at line 20 of file FriendWindowHandler.cs.
Referenced by DisplayFriends(), and SentFriendRequest().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/FriendWindowHandler.cs