Thesis: Game.GameController Class Reference
Game.GameController Class Reference
Handles the main flow of the game scene
Public Member Functions
void IncreaseCoinCount (float amount)
Increases the game's collected coin count
async Task NewGame ()
Create a new game
async Task LoadAndDespawnChunks (int centerRow, int centerColumn)
Handle the load and despawning of the chunks relative to the given indices
Properties
World.GameWorld World [get, private set]
Gets the world
int Score [get, private set]
Getter to the score
PlayerCar? Player [get, private set]
Reference to the player's car
Vector3 PlayerPos [get]
Getter to the player's current absolute position in the world
bool Running = false [get, private set]
Is the game running
int Difficulty = 0 [get, private set]
The current difficulty of the game
float Coins = 0 [get, private set]
The number of picked up coins
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void Awake ()
Called when script is loaded
void Start ()
Called just before the first frame
void Update ()
Called every frame
void PlayerSkinsLoaded (GameObject playerSkin)
Add the loaded skin to the player variants list
void PlayerDied (object? sender, EventArgs args)
Event for when the player is killed
void DespawnFarAwayChunks (int row, int col)
Despawn the chunks which are too far away from the player
async Task SpawnNearbyChunks (int row, int col)
Spawns and loads the nearby chunks
async Task ValidateAndLoadChunk (int row, int col)
Checks if the selected chunk is in range and loads it if the world exists
Private Attributes
World.GameWorld world
Reference to the generated world
int chunkLoadDistance = 1
How far should the chunks be loaded
GameUI gameUI
Reference to the game ui controller
Dictionary< long, GameObject > playerVariants = new Dictionary<long, GameObject>()
The possible skins that can be used
float elapsedTime = 0
Stores how long the game had been in progress (score is rounded from this)
CarSpawner? carSpawner
Reference to the gameobject which will handle the spawning of cars
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Handles the main flow of the game scene
Definition at line 18 of file GameController.cs.
Member Function Documentation
Awake()
void Game.GameController.Awake () inline private
Called when script is loaded
Definition at line 92 of file GameController.cs.
         {
             //Load the skins
             var handle = Addressables.LoadAssetsAsync<GameObject>("PlayerVariants", PlayerSkinsLoaded);
             //Get the reference to the other gameobjects
             this.carSpawner = this.GetComponentInChildren<CarSpawner>();
             gameUI = this.gameObject.GetComponentInChildren<GameUI>();
             if (gameUI is null)
             {
                 Debug.LogError("Can't load the ui");
             }
             else
             {
                 gameUI.Init(this);
             }
         }
References Game.GameController.gameUI, Game.UI.GameUI.Init(), and Game.GameController.PlayerSkinsLoaded().
Start()
void Game.GameController.Start () inline private
Called just before the first frame
Definition at line 112 of file GameController.cs.
         {
             Application.targetFrameRate = 60;
             QualitySettings.vSyncCount = 0;
         }
Update()
void Game.GameController.Update () inline private
Called every frame
Definition at line 121 of file GameController.cs.
         {
             if (!Running)
             {
                 return;
             }
             if (this.Difficulty < 5)
             {
                 if (Difficulty < this.elapsedTime / 20)
                 {
                     this.Difficulty = (int)this.elapsedTime / 20;
                     this.gameUI.ChangeDifficulyDisplay(Difficulty);
                 }
             }
             this.elapsedTime += Time.deltaTime;
         }
References Game.UI.GameUI.ChangeDifficulyDisplay(), Game.GameController.Difficulty, and Game.GameController.Running.
PlayerSkinsLoaded()
void Game.GameController.PlayerSkinsLoaded (GameObject playerSkin) inline private
Add the loaded skin to the player variants list
Parameters
playerSkin The loaded player skin
Definition at line 143 of file GameController.cs.
         {
             this.playerVariants.Add(playerSkin.GetComponent<PlayerCar>().SkinId, playerSkin);
         }
References Game.PlayerCar.SkinId.
Referenced by Game.GameController.Awake().
IncreaseCoinCount()
void Game.GameController.IncreaseCoinCount (float amount) inline
Increases the game's collected coin count
Parameters
amount How much to increase it
Definition at line 152 of file GameController.cs.
         {
             this.Coins += amount;
         }
References Game.GameController.Coins.
Referenced by Game.PlayerCar.PickedUpCoin().
PlayerDied()
void Game.GameController.PlayerDied (object? sender, EventArgs args) inline private
Event for when the player is killed
Parameters
sender (not used)
args (not used)
Definition at line 162 of file GameController.cs.
         {
             //If the game is not running skip
             if (!Running)
             {
                 return;
             }
             this.gameUI.ShowEndGameScreen();
             Running = false;
         }
References Game.GameController.Running, and Game.UI.GameUI.ShowEndGameScreen().
Referenced by Game.GameController.NewGame().
NewGame()
async Task Game.GameController.NewGame () inline
Create a new game
Returns
Definition at line 178 of file GameController.cs.
         {
             //Loads the player
             long skinId = UserData.Instance.Game.OwnedCars![gameUI.SelectedSkinIndex].ShopId;
             //If the skin hasn't loaded yet wait
             for (int i = 0; i < 100 && !playerVariants.ContainsKey(skinId); i++)
             {
                 await Task.Delay(100);
             }
             Player = Instantiate(playerVariants[skinId], this.transform).GetComponent<PlayerCar>();
             Player.Init(this);
             Player.DestroyedEvent += PlayerDied;
             //Reset the parameters
             this.carSpawner?.Reset();
             this.Score = 0;
             await World.CreateNewGame();
             Vector3 baseChunkPos = (await World.GetChunk(GameConfig.CHUNK_COUNT / 2, GameConfig.CHUNK_COUNT / 2)).gameObject.transform.position;
             Player.gameObject.transform.position = new Vector3(baseChunkPos.x + GameConfig.CHUNK_SIZE * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL / 2 + 10, baseChunkPos.y + 2, baseChunkPos.z);
             this.gameUI.ChangeDifficulyDisplay(0);
             this.Running = true;
             this.Coins = 0;
             this.Difficulty = 0;
         }
References Game.UI.GameUI.ChangeDifficulyDisplay(), Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_COUNT, Game.GameConfig.CHUNK_SCALE, Game.GameConfig.CHUNK_SIZE, Game.GameController.Coins, Game.World.GameWorld.CreateNewGame(), Game.Car.DestroyedEvent, Game.GameController.Difficulty, User.UserData.Game, Game.GameController.gameUI, Game.World.GameWorld.GetChunk(), Game.Car.Init(), User.UserData.Instance, Game.GameController.Player, Game.GameController.PlayerDied(), Game.GameController.playerVariants, Game.World.CarSpawner.Reset(), Game.GameController.Running, Game.GameController.Score, Game.UI.GameUI.SelectedSkinIndex, and Game.GameController.World.
Referenced by Game.UI.GameUI.NewGame().
LoadAndDespawnChunks()
async Task Game.GameController.LoadAndDespawnChunks (int centerRow, int centerColumn) inline
Handle the load and despawning of the chunks relative to the given indices
Parameters
centerRow Chunk row index
centerColumn Chunk col index
Definition at line 207 of file GameController.cs.
         {
             await SpawnNearbyChunks(centerRow, centerColumn);
             DespawnFarAwayChunks(centerRow, centerColumn);
         }
References Game.GameController.DespawnFarAwayChunks(), and Game.GameController.SpawnNearbyChunks().
Referenced by Game.PlayerCar.ChunkChanged().
DespawnFarAwayChunks()
void Game.GameController.DespawnFarAwayChunks (int row, int col) inline private
Despawn the chunks which are too far away from the player
Parameters
row The center row index of the chunks
col The center col index of the chunks
Definition at line 218 of file GameController.cs.
         {
             for (int i = -(chunkLoadDistance + 1); i <= chunkLoadDistance + 1; i++)
             {
                 for (int j = -(chunkLoadDistance + 1); j <= chunkLoadDistance + 1; j++)
                 {
                     //If the chunk is close enough skip it
                     if (Mathf.Abs(i) <= chunkLoadDistance && Mathf.Abs(j) <= chunkLoadDistance)
                     {
                         continue;
                     }
                     //If the chunk is far away unload it
                     if (i + row >= 0 && j + col >= 0 && i + row < GameConfig.CHUNK_COUNT && j + col < GameConfig.CHUNK_COUNT)
                     {
                         if (world is not null)
                             world.HideChunk(j + col, i + row);
                     }
                 }
             }
         }
References Game.GameConfig.CHUNK_COUNT, Game.GameController.chunkLoadDistance, Game.World.GameWorld.HideChunk(), and Game.GameController.world.
Referenced by Game.GameController.LoadAndDespawnChunks().
SpawnNearbyChunks()
async Task Game.GameController.SpawnNearbyChunks (int row, int col) inline private
Spawns and loads the nearby chunks
Parameters
row The center row index of the chunks
col The center col index of the chunks
Definition at line 244 of file GameController.cs.
         {
             await ValidateAndLoadChunk(row, col);
             for (int currSize = 1; currSize <= chunkLoadDistance; currSize++)
             {
                 for (int x = 0 - currSize; x <= 0 + currSize; x += currSize * 2)
                 {
                     for (int y = 0; y <= currSize - 1; y++)
                     {
                         await ValidateAndLoadChunk(row + y, col + x);
                         await ValidateAndLoadChunk(row - y, col + x);
                     }
                 }
                 for (int y = 0 - currSize; y <= 0 + currSize; y += currSize * 2)
                 {
                     for (int x = 0; x <= currSize - 1; x++)
                     {
                         await ValidateAndLoadChunk(row + y, col + x);
                         await ValidateAndLoadChunk(row + y, col - x);
                     }
                 }
                 await ValidateAndLoadChunk(row + currSize, col + currSize);
                 await ValidateAndLoadChunk(row - currSize, col - currSize);
                 await ValidateAndLoadChunk(row + currSize, col - currSize);
                 await ValidateAndLoadChunk(row - currSize, col + currSize);
             }
         }
References Game.GameController.chunkLoadDistance, and Game.GameController.ValidateAndLoadChunk().
Referenced by Game.GameController.LoadAndDespawnChunks().
ValidateAndLoadChunk()
async Task Game.GameController.ValidateAndLoadChunk (int row, int col) inline private
Checks if the selected chunk is in range and loads it if the world exists
Parameters
row Row index of the chunk
col Col index of the chunk
Definition at line 280 of file GameController.cs.
         {
             if (row < 0 || row >= GameConfig.CHUNK_COUNT || col < 0 || col >= GameConfig.CHUNK_COUNT)
             {
                 return;
             }
             if (world is not null)
                 await world.LoadChunk(col, row);
         }
References Game.GameConfig.CHUNK_COUNT, Game.World.GameWorld.LoadChunk(), and Game.GameController.world.
Referenced by Game.GameController.SpawnNearbyChunks().
Member Data Documentation
world
World.GameWorld Game.GameController.world private
Reference to the generated world
Definition at line 24 of file GameController.cs.
Referenced by Game.GameController.DespawnFarAwayChunks(), and Game.GameController.ValidateAndLoadChunk().
chunkLoadDistance
int Game.GameController.chunkLoadDistance = 1 private
How far should the chunks be loaded
Definition at line 30 of file GameController.cs.
Referenced by Game.GameController.DespawnFarAwayChunks(), and Game.GameController.SpawnNearbyChunks().
gameUI
GameUI Game.GameController.gameUI private
Reference to the game ui controller
Definition at line 35 of file GameController.cs.
Referenced by Game.GameController.Awake(), and Game.GameController.NewGame().
playerVariants
Dictionary<long, GameObject> Game.GameController.playerVariants = new Dictionary<long, GameObject>() private
The possible skins that can be used
Definition at line 40 of file GameController.cs.
Referenced by Game.GameController.NewGame().
elapsedTime
float Game.GameController.elapsedTime = 0 private
Stores how long the game had been in progress (score is rounded from this)
Definition at line 52 of file GameController.cs.
carSpawner
CarSpawner? Game.GameController.carSpawner private
Reference to the gameobject which will handle the spawning of cars
Definition at line 57 of file GameController.cs.
Property Documentation
World
World.GameWorld Game.GameController.World get private set
Gets the world
Definition at line 45 of file GameController.cs.
 { get => world; private set => world = value; }
Referenced by Game.Car.ChangeChunkIfNeeded(), Game.GameController.NewGame(), and Game.World.CarSpawner.SpawnPolice().
Score
int Game.GameController.Score get private set
Getter to the score
Definition at line 62 of file GameController.cs.
 { get => Mathf.RoundToInt(elapsedTime); private set => elapsedTime = value; }
Referenced by Game.GameController.NewGame(), Game.UI.GameUI.SaveGameResult(), Game.UI.GameUI.ShowEndGameScreen(), and Game.UI.GameUI.Update().
Player
PlayerCar? Game.GameController.Player get private set
Reference to the player's car
Definition at line 67 of file GameController.cs.
 { get; private set; }
Referenced by Game.UI.GameUI.BackToGameMenuWithoutSave(), Game.UI.GameUI.BuyImmunity(), Game.UI.GameUI.BuyTurbo(), Game.GameController.NewGame(), and Game.UI.GameUI.Update().
PlayerPos
Vector3 Game.GameController.PlayerPos get
Getter to the player's current absolute position in the world
Definition at line 72 of file GameController.cs.
Referenced by Game.NpcCar.DetermineSteeringDirectionTowardsPlayer(), Game.World.CarSpawner.SpawnPolice(), CameraScript.Update(), and Game.CopCar.Update().
Running
bool Game.GameController.Running = false get private set
Is the game running
Definition at line 77 of file GameController.cs.
 { get; private set; } = false;
Referenced by Game.GameController.NewGame(), Game.GameController.PlayerDied(), CameraScript.Update(), Game.PlayerCar.Update(), Game.GameController.Update(), Game.UI.GameUI.Update(), and Game.World.CarSpawner.Update().
Difficulty
int Game.GameController.Difficulty = 0 get private set
The current difficulty of the game
Definition at line 82 of file GameController.cs.
 { get; private set; } = 0;
Referenced by Game.GameController.NewGame(), Game.GameController.Update(), and Game.World.CarSpawner.Update().
Coins
float Game.GameController.Coins = 0 get private set
The number of picked up coins
Definition at line 87 of file GameController.cs.
 { get; private set; } = 0;
Referenced by Game.UI.GameUI.DoubledCoins(), Game.GameController.IncreaseCoinCount(), Game.GameController.NewGame(), Game.UI.GameUI.SaveGameResult(), Game.UI.GameUI.ShowEndGameScreen(), and Game.UI.GameUI.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/GameController.cs