Bomberman: UnityStandardAssets.CrossPlatformInput.MobileControlRig Class Reference
UnityStandardAssets.CrossPlatformInput.MobileControlRig Class Reference
Private Member Functions
void OnEnable ()
void Start ()
void CheckEnableControlRig ()
void EnableControlRig (bool enabled)
Detailed Description
Definition at line 11 of file MobileControlRig.cs.
Member Function Documentation
OnEnable()
void UnityStandardAssets.CrossPlatformInput.MobileControlRig.OnEnable () inline private
Definition at line 20 of file MobileControlRig.cs.
   {
     CheckEnableControlRig();
   }
References UnityStandardAssets.CrossPlatformInput.MobileControlRig.CheckEnableControlRig().
Start()
void UnityStandardAssets.CrossPlatformInput.MobileControlRig.Start () inline private
Definition at line 26 of file MobileControlRig.cs.
         {
 #if UNITY_EDITOR
             if (Application.isPlaying) //if in the editor, need to check if we are playing, as start is also called just after exiting play
 #endif
             {
                 UnityEngine.EventSystems.EventSystem system = GameObject.FindObjectOfType<UnityEngine.EventSystems.EventSystem>();
                 if (system == null)
                 {//the scene have no event system, spawn one
                     GameObject o = new GameObject("EventSystem");
                     o.AddComponent<UnityEngine.EventSystems.EventSystem>();
                     o.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();
                 }
             }
         }
CheckEnableControlRig()
void UnityStandardAssets.CrossPlatformInput.MobileControlRig.CheckEnableControlRig () inline private
Definition at line 67 of file MobileControlRig.cs.
         {
 #if MOBILE_INPUT
     EnableControlRig(true);
     #else
             EnableControlRig(false);
 #endif
         }
References UnityStandardAssets.CrossPlatformInput.MobileControlRig.EnableControlRig().
Referenced by UnityStandardAssets.CrossPlatformInput.MobileControlRig.OnEnable().
EnableControlRig()
void UnityStandardAssets.CrossPlatformInput.MobileControlRig.EnableControlRig (bool enabled) inline private
Definition at line 77 of file MobileControlRig.cs.
         {
             foreach (Transform t in transform)
             {
                 t.gameObject.SetActive(enabled);
             }
         }
Referenced by UnityStandardAssets.CrossPlatformInput.MobileControlRig.CheckEnableControlRig().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/MobileControlRig.cs