Thesis: MainPage.TaskHistoryWindowHandler Class Reference
MainPage.TaskHistoryWindowHandler Class Reference
Task histories window controller
Public Member Functions
void Show ()
Shows the task history window
void Hide ()
Hides the task history window
void LoadTaskHistories ()
Loads the task histories from the server
Private Member Functions
void ShowRequestFail (string content)
Show the server response errors
void LoadedHistories (List< TaskHistory > taskHistories)
When the server response is recieved load the histories
Private Attributes
GameObject taskHistoriesParent
The container where to put the task histories
ModalWindow modalWindow
Reference to the modal window to alert the user for api fails
GameObject taskHistoryItemPrefab
Task history prefab
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Task histories window controller
Definition at line 12 of file TaskHistoryWindowHandler.cs.
Member Function Documentation
Show()
void MainPage.TaskHistoryWindowHandler.Show () inline
Shows the task history window
Definition at line 35 of file TaskHistoryWindowHandler.cs.
         {
             this.gameObject.SetActive(true);
             LoadTaskHistories();
         }
References MainPage.TaskHistoryWindowHandler.LoadTaskHistories().
Hide()
void MainPage.TaskHistoryWindowHandler.Hide () inline
Hides the task history window
Definition at line 44 of file TaskHistoryWindowHandler.cs.
         {
             this.gameObject.SetActive(false);
         }
LoadTaskHistories()
void MainPage.TaskHistoryWindowHandler.LoadTaskHistories () inline
Loads the task histories from the server
Definition at line 52 of file TaskHistoryWindowHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<TaskHistory>>(ServerConfig.PATH_FOR_GET_TASK_HISTORIES, LoadedHistories, onFailedAction: ShowRequestFail));
         }
References MainPage.TaskHistoryWindowHandler.LoadedHistories(), Config.ServerConfig.PATH_FOR_GET_TASK_HISTORIES, Utility.CoroutineRunner.RunCoroutine(), and MainPage.TaskHistoryWindowHandler.ShowRequestFail().
Referenced by MainPage.TaskHistoryWindowHandler.Show().
ShowRequestFail()
void MainPage.TaskHistoryWindowHandler.ShowRequestFail (string content) inline private
Show the server response errors
Parameters
content The server response
Definition at line 61 of file TaskHistoryWindowHandler.cs.
         {
             modalWindow.Show("Task history error", content);
         }
References MainPage.TaskHistoryWindowHandler.modalWindow, and Utility.ModalWindow.Show().
Referenced by MainPage.TaskHistoryWindowHandler.LoadTaskHistories().
LoadedHistories()
void MainPage.TaskHistoryWindowHandler.LoadedHistories (List< TaskHistory > taskHistories) inline private
When the server response is recieved load the histories
Parameters
taskHistories
Definition at line 70 of file TaskHistoryWindowHandler.cs.
         {
             //Protect from errors during testing
             try
             {
                 //Delete the previous ones
                 for (int i = 0; i < this.taskHistoriesParent.transform.childCount; i++)
                 {
                     Destroy(this.taskHistoriesParent.transform.GetChild(i).gameObject);
                 }
                 this.taskHistoriesParent.transform.DetachChildren();
                 foreach (var item in taskHistories)
                 {
                     TaskHistoryHandler leaderboardItem = Instantiate(taskHistoryItemPrefab, taskHistoriesParent.transform).GetComponent<TaskHistoryHandler>();
                     leaderboardItem.Init(item);
                 }
             }
             catch (MissingReferenceException)
             {
                 throw;
             }
         }
References MainPage.TaskHistoryHandler.Init(), MainPage.TaskHistoryWindowHandler.taskHistoriesParent, and MainPage.TaskHistoryWindowHandler.taskHistoryItemPrefab.
Referenced by MainPage.TaskHistoryWindowHandler.LoadTaskHistories().
Member Data Documentation
taskHistoriesParent
GameObject MainPage.TaskHistoryWindowHandler.taskHistoriesParent private
The container where to put the task histories
Definition at line 18 of file TaskHistoryWindowHandler.cs.
Referenced by MainPage.TaskHistoryWindowHandler.LoadedHistories().
modalWindow
ModalWindow MainPage.TaskHistoryWindowHandler.modalWindow private
Reference to the modal window to alert the user for api fails
Definition at line 24 of file TaskHistoryWindowHandler.cs.
Referenced by MainPage.TaskHistoryWindowHandler.ShowRequestFail().
taskHistoryItemPrefab
GameObject MainPage.TaskHistoryWindowHandler.taskHistoryItemPrefab private
Task history prefab
Definition at line 30 of file TaskHistoryWindowHandler.cs.
Referenced by MainPage.TaskHistoryWindowHandler.LoadedHistories().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/TaskHistoryWindowHandler.cs