Thesis: MainPage.FriendWindowHandler Class Reference
MainPage.FriendWindowHandler Class Reference
Handles the friend window display
Public Member Functions
void ShowPendingChanged (bool newValue)
Changed event for pending checkbox Loads/Unloads the pending friend requests
void Show ()
Shows the profile window
void SendFriendRequest ()
Sends a friend request to the user which was specified in the useridentification input
void Hide ()
Hides the friend window
Private Member Functions
void ShowRequestFail (string content)
Show api request failure
void SentFriendRequest (Friend friend)
After the friend request was sent load the friend prefab if it can show pending
void LoadFriends ()
Loads the friends from the server
void DisplayFriends (List< Friend > friends)
Display the friends which was recieved from the server
Private Attributes
GameObject friendsParent
Parent for the friend prefabs
TMP_InputField userIdentificationInput
What is the user identification for the user
GameObject friendPrefab
The friend prefab
ModalWindow modalWindow
Modal window reference
bool showPending = true
Should we display the pending friends
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Handles the friend window display
Definition at line 13 of file FriendWindowHandler.cs.
Member Function Documentation
ShowPendingChanged()
void MainPage.FriendWindowHandler.ShowPendingChanged (bool newValue) inline
Changed event for pending checkbox Loads/Unloads the pending friend requests
Parameters
newValue State of the checkbox
Definition at line 49 of file FriendWindowHandler.cs.
         {
             this.showPending = newValue;
             LoadFriends();
         }
References MainPage.FriendWindowHandler.LoadFriends().
Show()
void MainPage.FriendWindowHandler.Show () inline
Shows the profile window
Definition at line 58 of file FriendWindowHandler.cs.
         {
             this.gameObject.SetActive(true);
             LoadFriends();
         }
References MainPage.FriendWindowHandler.LoadFriends().
SendFriendRequest()
void MainPage.FriendWindowHandler.SendFriendRequest () inline
Sends a friend request to the user which was specified in the useridentification input
Definition at line 67 of file FriendWindowHandler.cs.
         {
             if (userIdentificationInput.text == "")
             {
                 return;
             }
             //Send request to server
             CoroutineRunner.RunCoroutine(Server.SendPostRequest<Friend>(ServerConfig.PATH_FOR_FRIEND_REQUEST_SEND, userIdentificationInput.text, onComplete: SentFriendRequest, onFailedAction: ShowRequestFail));
         }
References Thesis_backend.Data_Structures.Friend, Config.ServerConfig.PATH_FOR_FRIEND_REQUEST_SEND, Utility.CoroutineRunner.RunCoroutine(), MainPage.FriendWindowHandler.SentFriendRequest(), MainPage.FriendWindowHandler.ShowRequestFail(), and MainPage.FriendWindowHandler.userIdentificationInput.
ShowRequestFail()
void MainPage.FriendWindowHandler.ShowRequestFail (string content) inline private
Show api request failure
Parameters
content Server response
Definition at line 81 of file FriendWindowHandler.cs.
         {
             modalWindow.Show("Request fail", content);
         }
References MainPage.FriendWindowHandler.modalWindow, and Utility.ModalWindow.Show().
Referenced by MainPage.FriendWindowHandler.SendFriendRequest().
SentFriendRequest()
void MainPage.FriendWindowHandler.SentFriendRequest (Friend friend) inline private
After the friend request was sent load the friend prefab if it can show pending
Parameters
friend The friend to display
Definition at line 90 of file FriendWindowHandler.cs.
         {
             if (showPending)
             {
                 FriendHandler friendDisplay = Instantiate(friendPrefab, this.friendsParent.transform).GetComponent<FriendHandler>();
                 friendDisplay.InitValues(friend);
             }
         }
References MainPage.FriendWindowHandler.friendPrefab, MainPage.FriendHandler.InitValues(), and MainPage.FriendWindowHandler.showPending.
Referenced by MainPage.FriendWindowHandler.SendFriendRequest().
Hide()
void MainPage.FriendWindowHandler.Hide () inline
Hides the friend window
Definition at line 102 of file FriendWindowHandler.cs.
         {
             this.gameObject.SetActive(false);
         }
LoadFriends()
void MainPage.FriendWindowHandler.LoadFriends () inline private
Loads the friends from the server
Definition at line 110 of file FriendWindowHandler.cs.
         {
             CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<Friend>>(ServerConfig.PATH_FOR_FRIEND_GETALL, onComplete: DisplayFriends));
         }
References MainPage.FriendWindowHandler.DisplayFriends(), Config.ServerConfig.PATH_FOR_FRIEND_GETALL, and Utility.CoroutineRunner.RunCoroutine().
Referenced by MainPage.FriendWindowHandler.Show(), and MainPage.FriendWindowHandler.ShowPendingChanged().
DisplayFriends()
void MainPage.FriendWindowHandler.DisplayFriends (List< Friend > friends) inline private
Display the friends which was recieved from the server
Parameters
friends The friend list recieved from the server
Definition at line 119 of file FriendWindowHandler.cs.
         {
             try
             {
                 //Delete the previous ones
                 for (int i = 0; i < this.friendsParent.transform.childCount; i++)
                 {
                     Destroy(this.friendsParent.transform.GetChild(i).gameObject);
                 }
                 this.friendsParent.transform.DetachChildren();
                 //Create the prefabs
                 foreach (var item in friends)
                 {
                     if (showPending)
                     {
                         FriendHandler friendDisplay = Instantiate(friendPrefab, this.friendsParent.transform).GetComponent<FriendHandler>();
                         friendDisplay.InitValues(item);
                     }
                     else
                     {
                         if (!item.Pending)
{
                             FriendHandler friendDisplay = Instantiate(friendPrefab, this.friendsParent.transform).GetComponent<FriendHandler>();
                             friendDisplay.InitValues(item);
                         }
                     }
                 }
             }
             catch (MissingReferenceException)
             {
                 Debug.LogWarning("Friend window tried to reference destroyed object");
                 return;
             }
         }
References MainPage.FriendWindowHandler.friendPrefab, MainPage.FriendHandler.InitValues(), and MainPage.FriendWindowHandler.showPending.
Referenced by MainPage.FriendWindowHandler.LoadFriends().
Member Data Documentation
friendsParent
GameObject MainPage.FriendWindowHandler.friendsParent private
Parent for the friend prefabs
Definition at line 19 of file FriendWindowHandler.cs.
userIdentificationInput
TMP_InputField MainPage.FriendWindowHandler.userIdentificationInput private
What is the user identification for the user
Definition at line 25 of file FriendWindowHandler.cs.
Referenced by MainPage.FriendWindowHandler.SendFriendRequest().
friendPrefab
GameObject MainPage.FriendWindowHandler.friendPrefab private
The friend prefab
Definition at line 31 of file FriendWindowHandler.cs.
Referenced by MainPage.FriendWindowHandler.DisplayFriends(), and MainPage.FriendWindowHandler.SentFriendRequest().
modalWindow
ModalWindow MainPage.FriendWindowHandler.modalWindow private
Modal window reference
Definition at line 37 of file FriendWindowHandler.cs.
Referenced by MainPage.FriendWindowHandler.ShowRequestFail().
showPending
bool MainPage.FriendWindowHandler.showPending = true private
Should we display the pending friends
Definition at line 42 of file FriendWindowHandler.cs.
Referenced by MainPage.FriendWindowHandler.DisplayFriends(), and MainPage.FriendWindowHandler.SentFriendRequest().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/FriendWindowHandler.cs