Bomberman: UnityStandardAssets.CrossPlatformInput.TiltInput Class Reference
UnityStandardAssets.CrossPlatformInput.TiltInput Class Reference
Classes
class AxisMapping
Public Types
enum AxisOptions { ForwardAxis , SidewaysAxis }
Public Attributes
AxisMapping mapping
AxisOptions tiltAroundAxis = AxisOptions.ForwardAxis
float fullTiltAngle = 25
float centreAngleOffset = 0
Private Member Functions
void OnEnable ()
void Update ()
void OnDisable ()
Private Attributes
CrossPlatformInputManager.VirtualAxis m_SteerAxis
Detailed Description
Definition at line 10 of file TiltInput.cs.
Member Enumeration Documentation
AxisOptions
enum UnityStandardAssets.CrossPlatformInput.TiltInput.AxisOptions
Enumerator
ForwardAxis
SidewaysAxis
Definition at line 13 of file TiltInput.cs.
        {
            ForwardAxis,
            SidewaysAxis,
        }
Member Function Documentation
OnEnable()
void UnityStandardAssets.CrossPlatformInput.TiltInput.OnEnable () inline private
Definition at line 46 of file TiltInput.cs.
        {
            if (mapping.type == AxisMapping.MappingType.NamedAxis)
            {
                m_SteerAxis = new CrossPlatformInputManager.VirtualAxis(mapping.axisName);
                CrossPlatformInputManager.RegisterVirtualAxis(m_SteerAxis);
            }
        }
References UnityStandardAssets.CrossPlatformInput.TiltInput.AxisMapping.axisName, UnityStandardAssets.CrossPlatformInput.TiltInput.m_SteerAxis, UnityStandardAssets.CrossPlatformInput.TiltInput.mapping, UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis(), and UnityStandardAssets.CrossPlatformInput.TiltInput.AxisMapping.type.
Update()
void UnityStandardAssets.CrossPlatformInput.TiltInput.Update () inline private
Definition at line 56 of file TiltInput.cs.
        {
            float angle = 0;
            if (Input.acceleration != Vector3.zero)
            {
                switch (tiltAroundAxis)
                {
                    case AxisOptions.ForwardAxis:
                        angle = Mathf.Atan2(Input.acceleration.x, -Input.acceleration.y)*Mathf.Rad2Deg +
                                centreAngleOffset;
                        break;
                    case AxisOptions.SidewaysAxis:
                        angle = Mathf.Atan2(Input.acceleration.z, -Input.acceleration.y)*Mathf.Rad2Deg +
                                centreAngleOffset;
                        break;
                }
            }
            float axisValue = Mathf.InverseLerp(-fullTiltAngle, fullTiltAngle, angle)*2 - 1;
            switch (mapping.type)
            {
                case AxisMapping.MappingType.NamedAxis:
                    m_SteerAxis.Update(axisValue);
                    break;
                case AxisMapping.MappingType.MousePositionX:
                    CrossPlatformInputManager.SetVirtualMousePositionX(axisValue*Screen.width);
                    break;
                case AxisMapping.MappingType.MousePositionY:
                    CrossPlatformInputManager.SetVirtualMousePositionY(axisValue*Screen.width);
                    break;
                case AxisMapping.MappingType.MousePositionZ:
                    CrossPlatformInputManager.SetVirtualMousePositionZ(axisValue*Screen.width);
                    break;
            }
        }
References UnityStandardAssets.CrossPlatformInput.TiltInput.centreAngleOffset, UnityStandardAssets.CrossPlatformInput.TiltInput.fullTiltAngle, UnityStandardAssets.CrossPlatformInput.TiltInput.m_SteerAxis, UnityStandardAssets.CrossPlatformInput.TiltInput.mapping, UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionX(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionY(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionZ(), UnityStandardAssets.CrossPlatformInput.TiltInput.tiltAroundAxis, and UnityStandardAssets.CrossPlatformInput.TiltInput.AxisMapping.type.
OnDisable()
void UnityStandardAssets.CrossPlatformInput.TiltInput.OnDisable () inline private
Definition at line 93 of file TiltInput.cs.
        {
            m_SteerAxis.Remove();
        }
References UnityStandardAssets.CrossPlatformInput.TiltInput.m_SteerAxis.
Member Data Documentation
mapping
AxisMapping UnityStandardAssets.CrossPlatformInput.TiltInput.mapping
Definition at line 37 of file TiltInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.OnEnable(), and UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
tiltAroundAxis
AxisOptions UnityStandardAssets.CrossPlatformInput.TiltInput.tiltAroundAxis = AxisOptions.ForwardAxis
Definition at line 38 of file TiltInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
fullTiltAngle
float UnityStandardAssets.CrossPlatformInput.TiltInput.fullTiltAngle = 25
Definition at line 39 of file TiltInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
centreAngleOffset
float UnityStandardAssets.CrossPlatformInput.TiltInput.centreAngleOffset = 0
Definition at line 40 of file TiltInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
m_SteerAxis
CrossPlatformInputManager.VirtualAxis UnityStandardAssets.CrossPlatformInput.TiltInput.m_SteerAxis private
Definition at line 43 of file TiltInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.OnDisable(), UnityStandardAssets.CrossPlatformInput.TiltInput.OnEnable(), and UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/TiltInput.cs