Bomberman: Car Class Reference
Car Class Reference
Public Member Functions
void Init (GameController world)
Protected Member Functions
virtual void Update ()
bool ChangeChunkIfNeeded ()
virtual void ChunkChanged (Chunk newChunk)
Protected Attributes
GameController gameController
CarController carController
Chunk lastChunk
Private Member Functions
void Awake ()
Detailed Description
Definition at line 8 of file Car.cs.
Member Function Documentation
Update()
virtual void Car.Update () inline protected virtual
Reimplemented in CopCar.
Definition at line 14 of file Car.cs.
     {
         if (gameController is null)
         {
             return;
         }
         if (ChangeChunkIfNeeded())
         {
         }
     }
References ChangeChunkIfNeeded(), and gameController.
ChangeChunkIfNeeded()
bool Car.ChangeChunkIfNeeded () inline protected
Definition at line 25 of file Car.cs.
     {
         Chunk newChunk = this.gameController.World.GetChunk(this.gameObject.transform.position);
         if (lastChunk != newChunk)
         {
             ChunkChanged(newChunk);
             lastChunk = newChunk;
             this.gameObject.transform.parent = newChunk.transform;
             return true;
         }
         return false;
     }
References ChunkChanged(), Game.World.GameWorld.GetChunk(), lastChunk, and Game.GameController.World.
Referenced by Update().
ChunkChanged()
virtual void Car.ChunkChanged (Chunk newChunk) inline protected virtual
Definition at line 40 of file Car.cs.
     {
     }
Referenced by ChangeChunkIfNeeded().
Init()
void Car.Init (GameController world) inline
Definition at line 44 of file Car.cs.
     {
         this.gameController = world;
     }
Referenced by CarSpawner.SpawnPolice().
Awake()
void Car.Awake () inline private
Definition at line 50 of file Car.cs.
     {
         this.carController = this.gameObject.GetComponent<CarController>();
     }
Member Data Documentation
gameController
GameController Car.gameController protected
Definition at line 10 of file Car.cs.
Referenced by NpcCar.DetermineSteeringDirection(), and Update().
carController
CarController Car.carController protected
Definition at line 11 of file Car.cs.
Referenced by CopCar.Update().
lastChunk
Chunk Car.lastChunk protected
Definition at line 12 of file Car.cs.
Referenced by ChangeChunkIfNeeded().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CarScripts/Car.cs