Bomberman: Game.World.World Class Reference
Game.World.World Class Reference
A class for handling chunk loading and unloading
Public Member Functions
void LoadChunk (int x, int z)
Loads a chunk
void HideChunk (int x, int z)
Private Member Functions
void Start ()
Start is called before the first frame update
Private Attributes
GameObject ChunkPrefab
Chunk prefab for the chunk creation
int ScaleAmount = 1
Chunk[,] Chunks
The chunks of the world
Detailed Description
A class for handling chunk loading and unloading
Definition at line 13 of file World.cs.
Member Function Documentation
Start()
void Game.World.World.Start () inline private
Start is called before the first frame update
Definition at line 32 of file World.cs.
             {
                 Chunks = new Chunk[GameConfig.CHUNK_COUNT, GameConfig.CHUNK_COUNT];
                 LoadChunk(0, 0);
                 //for (int i = 0; i < GameConfig.CHUNK_COUNT; i++)
                 //{
                 //    for (int j = 0; j < GameConfig.CHUNK_COUNT; j++)
                 //    {
                 //        LoadChunk(j, i);
                 //    }
                 //}
                 //this.transform.localScale = new Vector3(ScaleAmount, 1, ScaleAmount);
             }
References GameConfig.CHUNK_COUNT, Game.World.World.Chunks, and Game.World.World.LoadChunk().
LoadChunk()
void Game.World.World.LoadChunk (int x, int z) inline
Loads a chunk
Parameters
x The x index of the chunk (horizontal)
z The z index of the chunk (vertical)
Definition at line 54 of file World.cs.
             {
                 if (Chunks[z, x] == null)
                 {
                     Chunks[z, x] = Instantiate(ChunkPrefab, this.transform, false).GetComponent<Chunk>();
                     List<EdgeRoadContainer> edges = new List<EdgeRoadContainer>();
                     if (z - 1 >= 0 && Chunks[z - 1, x] != null)
                     {
                         edges.AddRange(Chunks[z - 1, x].EdgeRoads.Where(x => x.EdgeRoad.y == GameConfig.CHUNK_SIZE - 1));
                     }
                     if (z + 1 < GameConfig.CHUNK_COUNT && Chunks[z + 1, x] != null)
                     {
                         edges.AddRange(Chunks[z + 1, x].EdgeRoads.Where(x => x.EdgeRoad.y == 0));
                     }
                     if (x - 1 >= 0 && Chunks[z, x - 1] != null)
                     {
                         edges.AddRange(Chunks[z, x - 1].EdgeRoads.Where(x => x.EdgeRoad.x == GameConfig.CHUNK_SIZE - 1));
                     }
                     if (x + 1 < GameConfig.CHUNK_COUNT && Chunks[z, x + 1] != null)
                     {
                         edges.AddRange(Chunks[z, x + 1].EdgeRoads.Where(x => x.EdgeRoad.x == 0));
                     }
                     Chunks[z, x].InitChunk(x, z, edges);
                 }
                 else
                 {
                     Chunks[z, x].Display();
                 }
             }
References GameConfig.CHUNK_COUNT, GameConfig.CHUNK_SIZE, Game.World.World.ChunkPrefab, Game.World.World.Chunks, Game.World.Chunk.Display(), and Game.World.Chunk.InitChunk().
Referenced by CarProbeScript.OnTriggerEnter(), and Game.World.World.Start().
HideChunk()
void Game.World.World.HideChunk (int x, int z) inline
Definition at line 85 of file World.cs.
             {
                 if (Chunks[z, x] is not null)
                 {
                     Chunks[z, x].HideChunk();
                 }
             }
References Game.World.World.Chunks, and Game.World.Chunk.HideChunk().
Referenced by CarProbeScript.OnTriggerEnter().
Member Data Documentation
ChunkPrefab
GameObject Game.World.World.ChunkPrefab private
Chunk prefab for the chunk creation
Definition at line 19 of file World.cs.
Referenced by Game.World.World.LoadChunk().
ScaleAmount
int Game.World.World.ScaleAmount = 1 private
Definition at line 22 of file World.cs.
Chunks
Chunk [,] Game.World.World.Chunks private
The chunks of the world
Definition at line 27 of file World.cs.
Referenced by Game.World.World.HideChunk(), Game.World.World.LoadChunk(), and Game.World.World.Start().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World.cs