Bomberman: CarSpawner Class Reference
CarSpawner Class Reference
Public Member Functions
void Update ()
void SpawnPolice ()
void SpawnNpc ()
Private Attributes
GameController gameController
List< GameObject > CopCars
List< GameObject > CitizenCars
float timer = 0
Static Private Attributes
const float spawnInterval = 10f
Detailed Description
Definition at line 7 of file CarSpawner.cs.
Member Function Documentation
Update()
void CarSpawner.Update () inline
Definition at line 22 of file CarSpawner.cs.
     {
         timer += Time.deltaTime;
         if (timer > spawnInterval)
         {
             timer = 0;
             SpawnPolice();
         }
     }
References spawnInterval, SpawnPolice(), and timer.
SpawnPolice()
void CarSpawner.SpawnPolice () inline
Definition at line 32 of file CarSpawner.cs.
     {
         foreach (var item in CopCars)
         {
             Chunk playerChunk = gameController.World.GetChunk(gameController.PlayerPos);
             CopCar copCar = Instantiate(item, playerChunk.gameObject.transform, true).GetComponent<CopCar>();
             copCar.Init(gameController);
             Vector3 roadPos = playerChunk.GetARandomRoad();
             copCar.transform.transform.localPosition = new Vector3(roadPos.x * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL, playerChunk.gameObject.transform.position.y + 2, roadPos.z * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL);
         }
     }
References GameConfig.CHUNK_CELL, GameConfig.CHUNK_SCALE, CopCars, gameController, Game.World.Chunk.GetARandomRoad(), Game.World.GameWorld.GetChunk(), Car.Init(), Game.GameController.PlayerPos, and Game.GameController.World.
Referenced by Update().
SpawnNpc()
void CarSpawner.SpawnNpc () inline
Definition at line 46 of file CarSpawner.cs.
     {
     }
Member Data Documentation
gameController
GameController CarSpawner.gameController private
Definition at line 10 of file CarSpawner.cs.
Referenced by SpawnPolice().
CopCars
List<GameObject> CarSpawner.CopCars private
Definition at line 13 of file CarSpawner.cs.
Referenced by SpawnPolice().
CitizenCars
List<GameObject> CarSpawner.CitizenCars private
Definition at line 16 of file CarSpawner.cs.
timer
float CarSpawner.timer = 0 private
Definition at line 18 of file CarSpawner.cs.
Referenced by Update().
spawnInterval
const float CarSpawner.spawnInterval = 10f static private
Definition at line 20 of file CarSpawner.cs.
Referenced by Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World/CarSpawner.cs