Bomberman: ShopWindow Class Reference
ShopWindow Class Reference
Public Member Functions
void Show ()
void Hide ()
void UpdateShop ()
string GetCoinText ()
GameObject GetShopParent ()
Public Attributes
List< Sprite > ShopItemSprites = new List<Sprite>()
Private Member Functions
void ShowRequestFail (string content)
void LoadedShopItems (List< Shop > shopItems)
Private Attributes
GameObject ShopParent
GameObject ShopItemPrefab
TMP_Text CoinText
ModalWindow ModalWindow
List< Shop > shopItemsCache
Detailed Description
Definition at line 8 of file ShopWindow.cs.
Member Function Documentation
Show()
void ShopWindow.Show () inline
Definition at line 27 of file ShopWindow.cs.
    {
        this.gameObject.SetActive(true);
        UpdateShop();
    }
References UpdateShop().
Referenced by GameUI.ShowShopWindow().
Hide()
void ShopWindow.Hide () inline
Definition at line 34 of file ShopWindow.cs.
    {
        this.gameObject.SetActive(false);
    }
Referenced by GameUI.HideShopWindow().
ShowRequestFail()
void ShopWindow.ShowRequestFail (string content) inline private
Definition at line 39 of file ShopWindow.cs.
    {
        ModalWindow.Show("Shop error", content);
    }
References ModalWindow.Show().
Referenced by UpdateShop().
UpdateShop()
void ShopWindow.UpdateShop () inline
Definition at line 44 of file ShopWindow.cs.
    {
        if (shopItemsCache is null)
        {
            StartCoroutine(Server.SendGetRequest<List<Shop>>(ServerConfig.PATH_FOR_SHOP_GET_ALL, LoadedShopItems, onFailedAction: ShowRequestFail));
        }
        else
        {
            LoadedShopItems(shopItemsCache);
        }
        CoinText.text = UserData.Instance.Game.Currency.ToString();
    }
References User.UserData.Game, User.UserData.Instance, LoadedShopItems(), Config.ServerConfig.PATH_FOR_SHOP_GET_ALL, shopItemsCache, and ShowRequestFail().
Referenced by ShopItem.Bought(), and Show().
LoadedShopItems()
void ShopWindow.LoadedShopItems (List< Shop > shopItems) inline private
Definition at line 57 of file ShopWindow.cs.
    {
        //Delete the previous ones
        for (int i = 0; i < this.ShopParent.transform.childCount; i++)
        {
            Destroy(this.ShopParent.transform.GetChild(i).gameObject);
        }
        this.ShopParent.transform.DetachChildren();
        this.shopItemsCache = shopItems;
        foreach (var item in shopItems)
        {
            ShopItem shopItem = Instantiate(ShopItemPrefab, ShopParent.transform).GetComponent<ShopItem>();
            bool owned = UserData.Instance.Game.OwnedCars.Find(x => x.ShopId == item.ID) != null;
            if (ShopItemSprites.Count <= (item.ID - 1))
            {
                shopItem.Init(this, item, ShopItemSprites[0], owned);
                Debug.LogError("No sprite for this shop item");
            }
            else
            {
                shopItem.Init(this, item, ShopItemSprites[(int)(item.ID - 1)], owned);
            }
        }
    }
References User.UserData.Game, ShopItem.Init(), User.UserData.Instance, ShopItemPrefab, ShopItemSprites, and ShopParent.
Referenced by UpdateShop().
GetCoinText()
string ShopWindow.GetCoinText () inline
Definition at line 85 of file ShopWindow.cs.
    {
        return this.CoinText.text;
    }
GetShopParent()
GameObject ShopWindow.GetShopParent () inline
Definition at line 90 of file ShopWindow.cs.
    {
        return this.ShopParent;
    }
References ShopParent.
Member Data Documentation
ShopParent
GameObject ShopWindow.ShopParent private
Definition at line 11 of file ShopWindow.cs.
Referenced by GetShopParent(), and LoadedShopItems().
ShopItemPrefab
GameObject ShopWindow.ShopItemPrefab private
Definition at line 14 of file ShopWindow.cs.
Referenced by LoadedShopItems().
ShopItemSprites
List<Sprite> ShopWindow.ShopItemSprites = new List<Sprite>()
Definition at line 17 of file ShopWindow.cs.
Referenced by GameUI.LeftRotateSkin(), LoadedShopItems(), and GameUI.RightRotateSkin().
CoinText
TMP_Text ShopWindow.CoinText private
Definition at line 20 of file ShopWindow.cs.
ModalWindow
ModalWindow ShopWindow.ModalWindow private
Definition at line 23 of file ShopWindow.cs.
shopItemsCache
List<Shop> ShopWindow.shopItemsCache private
Definition at line 25 of file ShopWindow.cs.
Referenced by UpdateShop().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/ShopWindow.cs