Thesis: Game.World.Chunk Class Reference
Game.World.Chunk Class Reference
Stores a single chunk of the world.
Public Member Functions
void Display ()
Show the chunk.
async Task InitChunk (int col, int row, List< EdgeRoadContainer > edgeRoads, GameWorld world)
Initialize the chunk.
void HideChunk ()
Hide the chunk.
Vector3 GetARandomRoad ()
Gets a random road's position.
async Task SpawnWorldObjects ()
Spawns the buildings and the props on a seperate thread.
Static Public Member Functions
static void InitUniTaskLoop ()
For single threaded tasks.
Public Attributes
float XOffset = 0f
float ZOffset = 0f
bool RandomizeOffset = false
Should it randomize the perlin noise offset.
GameObject straightRoadPrefab
Reference to the straight road prefab.
GameObject grassPrefab
Reference to the grass prefab.
GameObject coinPrefab
Reference to the coin prefab.
Properties
int? zSize [get, private set]
The size of the world on the z axis.
int? xSize [get, private set]
The size of the world on the x axis.
int Row [get, private set]
Row index of the chunk in the chunk matrix.
int Col [get, private set]
Col index of the chunk in the chunk matrix.
bool[,] Roads [get]
Matrix which stores the roads.
List< EdgeRoadContainer > EdgeRoads [get]
Reference to the road generator's edge roads.
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed.
Private Member Functions
async void Awake ()
Start when the script is loaded.
void BuildingLoaded (GameObject building)
Callback for when each building asset is loaded.
void PropLoaded (GameObject prop)
Callback for when each prop asset is loaded.
float GetAbsolutePosition ()
void LoadFromSettings ()
Load the chunk's sizes.
void CreateTiles ()
Creates the tiles for the chunk.
ChunkCellContainer DetermineRoadType (int col, int row)
Determine what type of road it is.
ChunkCellContainer DetermineTileType (int x, int z)
Determines the type of the tile at the coord.
void GenerateCellMatrix ()
Generate the building cells matrix so we know which way the roads are.
IEnumerator AddRoadBuildings ()
Add the buildings which are next to the roads.
IEnumerator AddEnvironmentProps ()
void LockAndTryToPlaceBuilding (int index, int row, int col)
Lock the cell and try to place it.
async Task< Chunk[,]> GetNearbyChunks (int row, int col)
Gets tthe nearby chunks.
Private Attributes
GameObject curvedRoadPrefab
Reference to the curved road prefab.
GameObject threeWayRoadPrefab
Reference to the three way road prefab.
GameObject crossRoadsPrefab
Reference to the cross roads prefab (4 way)
List< Building > buildings
The buildings which can be spawn.
List< Prop > props
The probs which can be spawn (objects which are away from the road)
Dictionary< ChunkCellType, List< Vector3 > > chunkCells = new Dictionary<ChunkCellType, List<Vector3>>()
The cells of tthe chunk categorized.
RoadGenerator roadGenerator
Class which generates the road matrix.
GameWorld world
Reference to the parent world.
List< Vector3Int > roads = new List<Vector3Int>()
The road positions.
Dictionary< ChunkCellType, List< GameObject > > objectsToCombine
Mostly deprecated but can be used to combine the cell's meshes into a one big mesh.
BuildingCell[,] buildingCells
Matrix to help the building placements stores road direction and if it is buildable.
float
Get the chunk's absolute position in the world.
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed.
Detailed Description
Stores a single chunk of the world.
Definition at line 22 of file Chunk.cs.
Member Function Documentation
InitUniTaskLoop()
static void Game.World.Chunk.InitUniTaskLoop () inline static
For single threaded tasks.
Definition at line 146 of file Chunk.cs.
            {
                var loop = PlayerLoop.GetCurrentPlayerLoop();
                Cysharp.Threading.Tasks.PlayerLoopHelper.Initialize(ref loop);
            }
Awake()
async void Game.World.Chunk.Awake () inline private
Start when the script is loaded.
Definition at line 155 of file Chunk.cs.
            {
                //Load the addressables
                buildings = new List<Building>();
                var buildingsLoadHandle = Addressables.LoadAssetsAsync<GameObject>("Buildings", BuildingLoaded);
                await buildingsLoadHandle.Task;
                props = new List<Prop>();
                var propsLoadHandle = Addressables.LoadAssetsAsync<GameObject>("Props", PropLoaded);
                await propsLoadHandle.Task;
                //Load the values from the settings
                LoadFromSettings();
                //Randomizes the offset
                if (RandomizeOffset)
                {
                    this.XOffset = Random.Range(0, 99999);
                    this.ZOffset = Random.Range(0, 99999);
                }
                this.objectsToCombine = new Dictionary<ChunkCellType, List<GameObject>>();
            }
References Game.World.Chunk.BuildingLoaded(), Game.World.Chunk.buildings, Game.World.Chunk.LoadFromSettings(), Game.World.Chunk.PropLoaded(), Game.World.Chunk.props, and Game.World.Chunk.RandomizeOffset.
BuildingLoaded()
void Game.World.Chunk.BuildingLoaded (GameObject building) inline private
Callback for when each building asset is loaded.
Parameters
building Loaded building
Definition at line 182 of file Chunk.cs.
            {
                buildings.Add(building.GetComponent<Building>());
                buildings.Last().SetAddressableKey($"Buildings/{building.name}.prefab");
            }
References Game.World.Chunk.buildings.
Referenced by Game.World.Chunk.Awake().
PropLoaded()
void Game.World.Chunk.PropLoaded (GameObject prop) inline private
Callback for when each prop asset is loaded.
Parameters
prop Loaded prop
Definition at line 192 of file Chunk.cs.
            {
                props.Add(prop.GetComponent<Prop>());
                props.Last().SetAddressableKey($"Props/{prop.name}.prefab");
            }
References Game.World.Chunk.props.
Referenced by Game.World.Chunk.Awake().
GetAbsolutePosition()
float Game.World.Chunk.GetAbsolutePosition () inline private
Definition at line 202 of file Chunk.cs.
            {
                return (Col * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL * GameConfig.CHUNK_SIZE, Row * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL * GameConfig.CHUNK_SIZE);
            }
Referenced by Game.World.Chunk.AddEnvironmentProps(), and Game.World.Chunk.LockAndTryToPlaceBuilding().
Display()
void Game.World.Chunk.Display () inline
Show the chunk.
Definition at line 210 of file Chunk.cs.
            {
                this.gameObject.SetActive(true);
            }
Referenced by Game.World.GameWorld.LoadChunk().
InitChunk()
async Task Game.World.Chunk.InitChunk (int col, int row, List< EdgeRoadContainer > edgeRoads, GameWorld world) inline
Initialize the chunk.
Parameters
col The column offset
row The row offset
edgeRoads
world
Returns
Definition at line 223 of file Chunk.cs.
            {
                //Wait for the addressables to be loaded
                while (objectsToCombine is null)
                {
#if UNITY_WEBGL
                    await UniTask.Delay(System.TimeSpan.FromSeconds(0.001f), ignoreTimeScale: false);
#else
                    await Task.Delay(1);
#endif
                }
                this.world = world;
                this.Row = row;
                this.Col = col;
                //Add every type of chunk cell to the dictionary
                for (ChunkCellType i = 0; i <= ChunkCellType.StraightRoad; i++)
                {
                    chunkCells.Add(i, new List<Vector3>());
                }
                //Detroyed check
                if (Destroyed)
                {
                    return;
                }
                //Get the nearby chunks and generate the road matrix
                Chunk[,] nearbyChunks = await GetNearbyChunks(Row, Col);
                roadGenerator = new RoadGenerator(GameConfig.CHUNK_SIZE, edgeRoads, nearbyChunks);
                //Create the tiles
                CreateTiles();
                //Deprecated
                //Create the props
                //AddEnviromentObjects();
                //Combine the objects
                foreach (var item in objectsToCombine)
                {
                    if (item.Value.Count != 0)
                    {
                        //   CombineMeshes(item.Key);
                    }
                }
                //CreateMeshes();
                //Destroyed check
                if (Destroyed)
                {
                    return;
                }
                this.gameObject.transform.localPosition = new Vector3(col * GameConfig.CHUNK_SIZE * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL, 0, row * GameConfig.CHUNK_SIZE * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL);
                this.gameObject.transform.localScale = new Vector3(GameConfig.CHUNK_SCALE, 1, GameConfig.CHUNK_SCALE);
                //Generate the obstacles
                await SpawnWorldObjects();
            }
References Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_SCALE, Game.GameConfig.CHUNK_SIZE, Game.World.Chunk.chunkCells, Game.World.Chunk.Col, Game.World.Chunk.CreateTiles(), Utility.ThreadSafeMonoBehaviour.Destroyed, Game.World.Chunk.GetNearbyChunks(), Game.World.Chunk.objectsToCombine, Game.World.Chunk.roadGenerator, Game.World.Chunk.Row, Game.World.Chunk.SpawnWorldObjects(), and Game.World.Chunk.world.
Referenced by Game.World.GameWorld.LoadChunk().
HideChunk()
void Game.World.Chunk.HideChunk () inline
Hide the chunk.
Definition at line 283 of file Chunk.cs.
            {
                this.gameObject.SetActive(false);
            }
Referenced by Game.World.GameWorld.HideChunk().
GetARandomRoad()
Vector3 Game.World.Chunk.GetARandomRoad () inline
Gets a random road's position.
Returns
Definition at line 292 of file Chunk.cs.
            {
                if (roads.Count == 0)
                {
                    return new Vector3(GameConfig.CHUNK_SIZE / 2, 0, GameConfig.CHUNK_SIZE / 2);
                }
                return roads[Random.Range(0, roads.Count)];
            }
References Game.GameConfig.CHUNK_SIZE, and Game.World.Chunk.roads.
Referenced by Game.World.CarSpawner.SpawnPolice().
LoadFromSettings()
void Game.World.Chunk.LoadFromSettings () inline private
Load the chunk's sizes.
Definition at line 304 of file Chunk.cs.
            {
                this.xSize = GameConfig.CHUNK_SIZE;
                this.zSize = GameConfig.CHUNK_SIZE;
            }
References Game.GameConfig.CHUNK_SIZE.
Referenced by Game.World.Chunk.Awake().
CreateTiles()
void Game.World.Chunk.CreateTiles () inline private
Creates the tiles for the chunk.
Definition at line 313 of file Chunk.cs.
            {
                for (int x = 0; x < xSize; x++)
                {
                    for (int z = 0; z < zSize; z++)
                    {
                        if (Destroyed)
{
                            return;
                        }
                        ChunkCellContainer tileType = DetermineTileType(x, z);
                        GameObject created = null;
                        //Load tthe correct prefab
                        switch (tileType.Type)
{
                            case ChunkCellType.StraightRoad:
                                created = Instantiate(straightRoadPrefab, this.transform);
                                break;
                            case ChunkCellType.CurvedRoad:
                                created = Instantiate(curvedRoadPrefab, this.transform);
                                break;
                            case ChunkCellType.ThreeWay:
                                created = Instantiate(threeWayRoadPrefab, this.transform);
                                break;
                            case ChunkCellType.CrossRoads:
                                created = Instantiate(crossRoadsPrefab, this.transform);
                                break;
                            case ChunkCellType.Grass:
                                created = Instantiate(grassPrefab, this.transform);
                                break;
                            case ChunkCellType.Sand:
                                break;
                            case ChunkCellType.Water:
                                break;
                            default:
                                break;
                        }
                        //Move it to the proper position and store it
                        if (created != null)
{
                            created.transform.localScale = created.transform.localScale * 1.01f;
                            created.transform.localPosition = new Vector3(x * 32, created.transform.localPosition.y, z * 32);
                            if (tileType.Orientation != Vector3.zero)
                                created.transform.Rotate(tileType.Orientation);
                        }
                        if (roadGenerator.RoadMatrix[z, x] && Random.Range(0f, 1f) <= GameConfig.COIN_RATE)
{
                            Coin coin = Instantiate(coinPrefab, created.transform).GetComponent<Coin>();
                            coin.gameObject.transform.position = new Vector3(x * 32, created.transform.localPosition.y + 3, z * 32);
                        }
                        if (!objectsToCombine.ContainsKey(tileType.Type))
{
                            objectsToCombine.Add(tileType.Type, new List<GameObject>());
                        }
                        created.isStatic = true;
                        objectsToCombine[tileType.Type].Add(created);
                        //chunkCells[tileType].Add(new Vector3(x, 0f, z));
                    }
                }
            }
References Game.GameConfig.COIN_RATE, Game.World.Chunk.coinPrefab, Game.World.Chunk.crossRoadsPrefab, Game.World.Chunk.curvedRoadPrefab, Utility.ThreadSafeMonoBehaviour.Destroyed, Game.World.Chunk.DetermineTileType(), Game.World.Chunk.grassPrefab, Game.World.Chunk.objectsToCombine, Assets.Scripts.Client.DataTypes.ChunkCellContainer.Orientation, Game.World.Chunk.roadGenerator, Game.World.RoadGenerator.RoadMatrix, Game.World.Chunk.straightRoadPrefab, Game.World.Chunk.threeWayRoadPrefab, Assets.Scripts.Client.DataTypes.ChunkCellContainer.Type, Game.World.Chunk.xSize, and Game.World.Chunk.zSize.
Referenced by Game.World.Chunk.InitChunk().
DetermineRoadType()
ChunkCellContainer Game.World.Chunk.DetermineRoadType (int col, int row) inline private
Determine what type of road it is.
Parameters
col Column index
row Row index
Returns
The chunk cell container with the correct road type
Definition at line 389 of file Chunk.cs.
            {
                int roadCount = 0;
                int firstIndex = -1;
                int lastIndex = -1;
                int secondIndex = -1;
                if (col - 1 >= 0 && roadGenerator.RoadMatrix[row, col - 1])
                {
                    roadCount++;
                    firstIndex = 0;
                    lastIndex = 0;
                }
                if (row + 1 < GameConfig.CHUNK_SIZE && roadGenerator.RoadMatrix[row + 1, col])
                {
                    roadCount++;
                    if (firstIndex == -1)
                    {
                        firstIndex = 1;
                    }
                    else
                    {
                        secondIndex = 1;
                    }
                    lastIndex = 1;
                }
                if (col + 1 < GameConfig.CHUNK_SIZE && roadGenerator.RoadMatrix[row, col + 1])
                {
                    roadCount++;
                    if (firstIndex == -1)
                    {
                        firstIndex = 2;
                    }
                    else if (secondIndex == -1)
                    {
                        secondIndex = 2;
                    }
                    lastIndex = 2;
                }
                if (row - 1 >= 0 && roadGenerator.RoadMatrix[row - 1, col])
                {
                    roadCount++;
                    if (firstIndex == -1)
                    {
                        firstIndex = 3;
                    }
                    else if (secondIndex == -1)
                    {
                        secondIndex = 3;
                    }
                    lastIndex = 3;
                }
                if (roadCount == 4)
                {
                    return new ChunkCellContainer(ChunkCellType.CrossRoads, Vector3.zero);
                }
                else if (roadCount == 3)
                {
                    if (firstIndex == 0 && lastIndex == 3)
                    {
                        if (secondIndex == 1)
{
                            return new ChunkCellContainer(ChunkCellType.ThreeWay, new Vector3(0, (1) * 90, 0));
                        }
                        else
{
                            return new ChunkCellContainer(ChunkCellType.ThreeWay, Vector3.zero);
                        }
                    }
                    return new ChunkCellContainer(ChunkCellType.ThreeWay, new Vector3(0, (secondIndex + 1) * 90, 0));
                }
                else if (roadCount == 2 && (lastIndex - firstIndex) % 2 == 1)
                {
                    if (secondIndex == 3 && firstIndex == 0)
                    {
                        return new ChunkCellContainer(ChunkCellType.CurvedRoad, new Vector3(0, (-1) * 90, 0));
                    }
                    return new ChunkCellContainer(ChunkCellType.CurvedRoad, new Vector3(0, (lastIndex - 1) * 90, 0));
                }
                else
                {
                    return new ChunkCellContainer(ChunkCellType.StraightRoad, new Vector3(0, (lastIndex % 2 + 1) * 90, 0));
                }
            }
References Game.GameConfig.CHUNK_SIZE, Game.World.Chunk.roadGenerator, and Game.World.RoadGenerator.RoadMatrix.
Referenced by Game.World.Chunk.DetermineTileType().
DetermineTileType()
ChunkCellContainer Game.World.Chunk.DetermineTileType (int x, int z) inline private
Determines the type of the tile at the coord.
Parameters
x x coord where we want to sample the perlin noise
z z coord where we want to sample the perlin noise
Returns
the proper TileType
Definition at line 491 of file Chunk.cs.
            {
                if (roadGenerator.RoadMatrix[z, x])
                {
                    roads.Add(new Vector3Int(x, 0, z));
                    return DetermineRoadType((int)x, (int)z);
                }
                float noise = Mathf.PerlinNoise((float)(x / (float)xSize * 5f) + XOffset, (float)(z / (float)zSize * 5f) + ZOffset) * 10f - 1.5f;
                // Debug.Log("noise:" + noise);
                if (noise > 0.15f || true)
                {
                    return new ChunkCellContainer(ChunkCellType.Grass, Vector3.zero);
                }
                //If later we want other types of biomes
                else if (noise > 0.05f)
                {
                    return new ChunkCellContainer(ChunkCellType.Sand, Vector3.zero);
                }
                else
                {
                    return new ChunkCellContainer(ChunkCellType.Water, Vector3.zero);
                }
            }
References Game.World.Chunk.DetermineRoadType(), Game.World.Chunk.roadGenerator, Game.World.RoadGenerator.RoadMatrix, Game.World.Chunk.roads, Game.World.Chunk.XOffset, Game.World.Chunk.xSize, Game.World.Chunk.ZOffset, and Game.World.Chunk.zSize.
Referenced by Game.World.Chunk.CreateTiles().
SpawnWorldObjects()
async Task Game.World.Chunk.SpawnWorldObjects () inline
Spawns the buildings and the props on a seperate thread.
Definition at line 520 of file Chunk.cs.
            {
                buildingCells = new BuildingCell[GameConfig.CHUNK_SIZE, GameConfig.CHUNK_SIZE];
#if UNITY_WEBGL
                GenerateCellMatrix();
#else
                await Task.Run(() => GenerateCellMatrix());
#endif
                CoroutineRunner.RunCoroutine(AddRoadBuildings());
                CoroutineRunner.RunCoroutine(AddEnvironmentProps());
            }
References Game.World.Chunk.AddEnvironmentProps(), Game.World.Chunk.AddRoadBuildings(), Game.World.Chunk.buildingCells, Game.GameConfig.CHUNK_SIZE, Game.World.Chunk.GenerateCellMatrix(), and Utility.CoroutineRunner.RunCoroutine().
Referenced by Game.World.Chunk.InitChunk().
GenerateCellMatrix()
void Game.World.Chunk.GenerateCellMatrix () inline private
Generate the building cells matrix so we know which way the roads are.
Definition at line 535 of file Chunk.cs.
            {
                foreach (var road in roads)
                {
                    buildingCells[road.z, road.x] = new BuildingCell(BuildingDirection.None, false);
                    for (var i = road.z - 1; i <= road.z + 1; i += 2)
                    {
                        if (i < 0 || i >= GameConfig.CHUNK_SIZE || buildingCells[i, road.x] != null)
{
                            continue;
                        }
                        if (roadGenerator.RoadMatrix[i, road.x])
{
                            buildingCells[i, road.x] = new BuildingCell(BuildingDirection.None, false);
                        }
                        else
{
                            BuildingDirection roadDir = BuildingDirection.None;
                            if (i > road.z)
{
                                roadDir = BuildingDirection.Down;
                            }
                            else if (i < road.z)
{
                                roadDir = BuildingDirection.Up;
                            }
                            buildingCells[i, road.x] = new BuildingCell(roadDir, true);
                        }
                    }
                    for (int j = road.x - 1; j <= road.x + 1; j += 2)
                    {
                        if (j < 0 || j >= GameConfig.CHUNK_SIZE || buildingCells[road.z, j] != null)
{
                            continue;
                        }
                        if (roadGenerator.RoadMatrix[road.z, j])
{
                            buildingCells[road.z, j] = new BuildingCell(BuildingDirection.None, false);
                        }
                        else
{
                            BuildingDirection roadDir = BuildingDirection.None;
                            if (j > road.x)
{
                                roadDir = BuildingDirection.Left;
                            }
                            else if (j < road.x)
{
                                roadDir = BuildingDirection.Right;
                            }
                            buildingCells[road.z, j] = new BuildingCell(roadDir, true);
                        }
                    }
                }
                for (int i = 0; i < GameConfig.CHUNK_SIZE; i++)
                {
                    for (int j = 0; j < GameConfig.CHUNK_SIZE; j++)
                    {
                        if (buildingCells[i, j] is null)
{
                            buildingCells[i, j] = new BuildingCell(BuildingDirection.None, true);
                        }
                    }
                }
            }
References Game.World.Chunk.buildingCells, Game.GameConfig.CHUNK_SIZE, Game.World.Chunk.roadGenerator, Game.World.RoadGenerator.RoadMatrix, and Game.World.Chunk.roads.
Referenced by Game.World.Chunk.SpawnWorldObjects().
AddRoadBuildings()
IEnumerator Game.World.Chunk.AddRoadBuildings () inline private
Add the buildings which are next to the roads.
Definition at line 610 of file Chunk.cs.
            {
                for (int i = 1; i < GameConfig.CHUNK_SIZE - 1; i++)
                {
                    for (int j = 1; j < GameConfig.CHUNK_SIZE - 1; j++)
                    {
                        //If the scene is destroyed
                        try
{
                            LockAndTryToPlaceBuilding(UnityEngine.Random.Range(0, this.buildings.Count), i, j);
                        }
                        catch (MissingReferenceException)
{
                        }
                        catch (System.NullReferenceException)
{
                        }
                    }
                    yield return null;
                }
                yield return null;
            }
References Game.World.Chunk.LockAndTryToPlaceBuilding().
Referenced by Game.World.Chunk.SpawnWorldObjects().
AddEnvironmentProps()
IEnumerator Game.World.Chunk.AddEnvironmentProps () inline private
Definition at line 633 of file Chunk.cs.
            {
                for (int i = 1; i < GameConfig.CHUNK_SIZE - 1; i++)
                {
                    for (int j = 1; j < GameConfig.CHUNK_SIZE - 1; j++)
                    {
                        //If the scene is destroyed
                        try
{
                            if (buildingCells[i, j].GotRoadNext || !buildingCells[i, j].Buildable || Random.Range(0, 5) != 0)
{
                                continue;
                            }
                            if (Random.Range(0, 2) == 0)
{
                                Prop prop = props[Random.Range(0, props.Count)];
                                var absolutePosition = GetAbsolutePosition();
                                Vector3 postition = new Vector3(absolutePosition.Item1 + j * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL, 0, absolutePosition.Item2 + i * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL);
                                Addressables.InstantiateAsync(prop.AddressableKey, postition, Quaternion.Euler(0, Random.Range(0, 4) * 90f, 0), this.gameObject.transform);
                            }
                        }
                        catch (MissingReferenceException)
{
                        }
                        catch (System.NullReferenceException)
{
                        }
                        yield return null;
                    }
                }
                yield return null;
            }
References Game.World.Prop.AddressableKey, Game.World.Chunk.buildingCells, Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_SCALE, Game.World.Chunk.GetAbsolutePosition(), and Game.World.Chunk.props.
Referenced by Game.World.Chunk.SpawnWorldObjects().
LockAndTryToPlaceBuilding()
void Game.World.Chunk.LockAndTryToPlaceBuilding (int index, int row, int col) inline private
Lock the cell and try to place it.
Parameters
index The building index
row The row position
col The column position
Definition at line 673 of file Chunk.cs.
            {
                if (buildingCells[row, col].GotRoadNext && buildingCells[row, col].Buildable)
                {
                    Building building = this.buildings[index];
                    List<BuildingCell> neighbourBuildingCells = new List<BuildingCell>();
                    float zPosCorrection = 0f;
                    float xPosCorrection = 0f;
                    if (((int)buildingCells[row, col].RoadDirection) % 2 == 1)
                    {
                        for (int i = building.RowCount / -2; i < Mathf.CeilToInt(building.RowCount / 2f); i++)
{
                            if (!buildingCells[row, col + i].Buildable)
{
                                return;
                            }
                            neighbourBuildingCells.Add(buildingCells[row, col + i]);
                        }
                        if (building.RowCount % 2 == 0)
{
                            xPosCorrection = GameConfig.CHUNK_SIZE / -2;
                        }
                        if (building.ColumnCount % 2 == 0)
{
                            zPosCorrection = GameConfig.CHUNK_SIZE / 2;
                        }
                    }
                    else
                    {
                        for (int i = building.RowCount / -2; i < Mathf.CeilToInt(building.RowCount / 2f); i++)
{
                            if (!buildingCells[row + i, col].Buildable)
{
                                return;
                            }
                            neighbourBuildingCells.Add(buildingCells[row + i, col]);
                        }
                        if (building.RowCount % 2 == 0)
{
                            zPosCorrection = GameConfig.CHUNK_SIZE / -2;
                        }
                        if (building.ColumnCount % 2 == 0)
{
                            xPosCorrection = GameConfig.CHUNK_SIZE / 2;
                        }
                    }
                    if (Random.Range(0, 2) == 0)
                    {
                        float rotation = ((int)buildingCells[row, col].RoadDirection) % 4 * 90f;
                        var absolutePosition = GetAbsolutePosition();
                        Vector3 postition = new Vector3(absolutePosition.Item1 + col * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL + xPosCorrection, 0, absolutePosition.Item2 + row * GameConfig.CHUNK_SCALE * GameConfig.CHUNK_CELL + zPosCorrection);
                        Addressables.InstantiateAsync(building.AddressableKey, postition, Quaternion.Euler(0, rotation, 0), this.gameObject.transform);
                        foreach (var item in neighbourBuildingCells)
{
                            item.Occupy();
                        }
                    }
                }
            }
References Game.World.Building.AddressableKey, Game.World.Chunk.buildingCells, Game.GameConfig.CHUNK_CELL, Game.GameConfig.CHUNK_SCALE, Game.World.Building.ColumnCount, Game.World.Chunk.GetAbsolutePosition(), and Game.World.Building.RowCount.
Referenced by Game.World.Chunk.AddRoadBuildings().
GetNearbyChunks()
async Task< Chunk[,]> Game.World.Chunk.GetNearbyChunks (int row, int col) inline private
Gets tthe nearby chunks.
Parameters
row The row index of the center chunk
col The col index of the center chunk
Returns
3*3 matrix of chunks
Definition at line 743 of file Chunk.cs.
            {
                Chunk[,] nearbyChunks = new Chunk[3, 3];
                for (int i = -1; i < 2; i++)
                {
                    if (row + i < 0 || row + i >= GameConfig.CHUNK_COUNT || i == 0)
                    {
                        continue;
                    }
                    for (int j = -1; j < 2; j++)
                    {
                        if (col + j < 0 || col + j >= GameConfig.CHUNK_COUNT || j == 0)
{
                            continue;
                        }
                        nearbyChunks[i + 1, j + 1] = world.GetChunkWithoutLoad(col + j, row + i);
                        if (nearbyChunks[i + 1, j + 1] is not null)
{
                            if (nearbyChunks[i + 1, j + 1].roadGenerator is null)
{
                                return nearbyChunks;
                            }
                            while (nearbyChunks[i + 1, j + 1].Roads is null)
{
                                await UniTask.Delay(System.TimeSpan.FromSeconds(0.001f), ignoreTimeScale: false);
                            }
                        }
                    }
                }
                return nearbyChunks;
            }
References Game.GameConfig.CHUNK_COUNT, Game.World.GameWorld.GetChunkWithoutLoad(), Game.World.Chunk.roadGenerator, Game.World.Chunk.Roads, and Game.World.Chunk.world.
Referenced by Game.World.Chunk.InitChunk().
Member Data Documentation
XOffset
float Game.World.Chunk.XOffset = 0f
Definition at line 25 of file Chunk.cs.
Referenced by Game.World.Chunk.DetermineTileType().
ZOffset
float Game.World.Chunk.ZOffset = 0f
Definition at line 28 of file Chunk.cs.
Referenced by Game.World.Chunk.DetermineTileType().
RandomizeOffset
bool Game.World.Chunk.RandomizeOffset = false
Should it randomize the perlin noise offset.
Definition at line 34 of file Chunk.cs.
Referenced by Game.World.Chunk.Awake().
straightRoadPrefab
GameObject Game.World.Chunk.straightRoadPrefab
Reference to the straight road prefab.
Definition at line 40 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
curvedRoadPrefab
GameObject Game.World.Chunk.curvedRoadPrefab private
Reference to the curved road prefab.
Definition at line 46 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
threeWayRoadPrefab
GameObject Game.World.Chunk.threeWayRoadPrefab private
Reference to the three way road prefab.
Definition at line 52 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
crossRoadsPrefab
GameObject Game.World.Chunk.crossRoadsPrefab private
Reference to the cross roads prefab (4 way)
Definition at line 58 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
grassPrefab
GameObject Game.World.Chunk.grassPrefab
Reference to the grass prefab.
Definition at line 64 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
coinPrefab
GameObject Game.World.Chunk.coinPrefab
Reference to the coin prefab.
Definition at line 70 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles().
buildings
List<Building> Game.World.Chunk.buildings private
The buildings which can be spawn.
Definition at line 75 of file Chunk.cs.
Referenced by Game.World.Chunk.Awake(), and Game.World.Chunk.BuildingLoaded().
props
List<Prop> Game.World.Chunk.props private
The probs which can be spawn (objects which are away from the road)
Definition at line 80 of file Chunk.cs.
Referenced by Game.World.Chunk.AddEnvironmentProps(), Game.World.Chunk.Awake(), and Game.World.Chunk.PropLoaded().
chunkCells
Dictionary<ChunkCellType, List<Vector3> > Game.World.Chunk.chunkCells = new Dictionary<ChunkCellType, List<Vector3>>() private
The cells of tthe chunk categorized.
Definition at line 115 of file Chunk.cs.
Referenced by Game.World.Chunk.InitChunk().
roadGenerator
RoadGenerator Game.World.Chunk.roadGenerator private
Class which generates the road matrix.
Definition at line 120 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles(), Game.World.Chunk.DetermineRoadType(), Game.World.Chunk.DetermineTileType(), Game.World.Chunk.GenerateCellMatrix(), Game.World.Chunk.GetNearbyChunks(), and Game.World.Chunk.InitChunk().
world
GameWorld Game.World.Chunk.world private
Reference to the parent world.
Definition at line 125 of file Chunk.cs.
Referenced by Game.World.Chunk.GetNearbyChunks(), and Game.World.Chunk.InitChunk().
roads
List<Vector3Int> Game.World.Chunk.roads = new List<Vector3Int>() private
The road positions.
Definition at line 130 of file Chunk.cs.
Referenced by Game.World.Chunk.DetermineTileType(), Game.World.Chunk.GenerateCellMatrix(), and Game.World.Chunk.GetARandomRoad().
objectsToCombine
Dictionary<ChunkCellType, List<GameObject> > Game.World.Chunk.objectsToCombine private
Mostly deprecated but can be used to combine the cell's meshes into a one big mesh.
Definition at line 135 of file Chunk.cs.
Referenced by Game.World.Chunk.CreateTiles(), and Game.World.Chunk.InitChunk().
buildingCells
BuildingCell [,] Game.World.Chunk.buildingCells private
Matrix to help the building placements stores road direction and if it is buildable.
Definition at line 140 of file Chunk.cs.
Referenced by Game.World.Chunk.AddEnvironmentProps(), Game.World.Chunk.GenerateCellMatrix(), Game.World.Chunk.LockAndTryToPlaceBuilding(), and Game.World.Chunk.SpawnWorldObjects().
float
Game.World.Chunk.float private
Get the chunk's absolute position in the world.
Returns
The chunk's absolute position in a tuple
Definition at line 202 of file Chunk.cs.
Property Documentation
zSize
int? Game.World.Chunk.zSize get private set
The size of the world on the z axis.
Definition at line 85 of file Chunk.cs.
{ get; private set; }
Referenced by Game.World.Chunk.CreateTiles(), and Game.World.Chunk.DetermineTileType().
xSize
int? Game.World.Chunk.xSize get private set
The size of the world on the x axis.
Definition at line 90 of file Chunk.cs.
{ get; private set; }
Referenced by Game.World.Chunk.CreateTiles(), and Game.World.Chunk.DetermineTileType().
Row
int Game.World.Chunk.Row get private set
Row index of the chunk in the chunk matrix.
Definition at line 95 of file Chunk.cs.
{ get; private set; }
Referenced by Game.PlayerCar.ChunkChanged(), and Game.World.Chunk.InitChunk().
Col
int Game.World.Chunk.Col get private set
Col index of the chunk in the chunk matrix.
Definition at line 100 of file Chunk.cs.
{ get; private set; }
Referenced by Game.PlayerCar.ChunkChanged(), and Game.World.Chunk.InitChunk().
Roads
bool [,] Game.World.Chunk.Roads get
Matrix which stores the roads.
Definition at line 105 of file Chunk.cs.
Referenced by Game.World.Chunk.GetNearbyChunks().
EdgeRoads
List<EdgeRoadContainer> Game.World.Chunk.EdgeRoads get
Reference to the road generator's edge roads.
Definition at line 110 of file Chunk.cs.
{ get => roadGenerator?.EdgeRoads; }
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/World/Chunk.cs