Bomberman: ProfileHandler Class Reference
ProfileHandler Class Reference
Public Member Functions
void Show ()
void Hide ()
void SendLogout ()
Send a login request with the login panel's fields.
Private Member Functions
void LoadFromApi ()
void LoggedOut (string result)
When the logout was a success.
IEnumerator MoveToLoginScene ()
Private Attributes
TMP_Text TotalTaskCount
TMP_Text GoodTaskCount
TMP_Text BadTaskCount
TMP_Text TotalScore
Additional Inherited Members
Protected Member Functions inherited from ThreadSafeMonoBehaviour
void OnDestroy ()
Properties inherited from ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
Detailed Description
Definition at line 11 of file ProfileHandler.cs.
Member Function Documentation
Show()
void ProfileHandler.Show () inline
Definition at line 25 of file ProfileHandler.cs.
    {
        this.gameObject.SetActive(true);
        LoadFromApi();
        this.TotalTaskCount.text = (UserData.Instance.CompletedGoodTasks + UserData.Instance.CompletedBadTasks).ToString();
        this.BadTaskCount.text = UserData.Instance.CompletedBadTasks.ToString();
        this.GoodTaskCount.text = UserData.Instance.CompletedGoodTasks.ToString();
        this.TotalScore.text = UserData.Instance.TotalScore.ToString();
    }
References User.UserData.CompletedBadTasks, User.UserData.CompletedGoodTasks, User.UserData.Instance, LoadFromApi(), and User.UserData.TotalScore.
Hide()
void ProfileHandler.Hide () inline
Definition at line 35 of file ProfileHandler.cs.
    {
        this.gameObject.SetActive(false);
    }
LoadFromApi()
void ProfileHandler.LoadFromApi () inline private
Definition at line 40 of file ProfileHandler.cs.
    {
    }
Referenced by Show().
SendLogout()
void ProfileHandler.SendLogout () inline
Send a login request with the login panel's fields.
Definition at line 47 of file ProfileHandler.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORLOGOUT, LoggedOut));
    }
References LoggedOut(), Config.ServerConfig.PATHFORLOGOUT, and CoroutineRunner.RunCoroutine().
LoggedOut()
void ProfileHandler.LoggedOut (string result) inline private
When the logout was a success.
Parameters
result The server's response
Definition at line 56 of file ProfileHandler.cs.
    {
        UserData.Instance.Logout();
        CoroutineRunner.RunCoroutine(MoveToLoginScene());
    }
References User.UserData.Instance, User.UserData.Logout(), MoveToLoginScene(), and CoroutineRunner.RunCoroutine().
Referenced by SendLogout().
MoveToLoginScene()
IEnumerator ProfileHandler.MoveToLoginScene () inline private
Definition at line 63 of file ProfileHandler.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
        while (!loading.isDone)
        {
            Debug.Log(loading.progress);
            yield return null;
        }
    }
Referenced by LoggedOut().
Member Data Documentation
TotalTaskCount
TMP_Text ProfileHandler.TotalTaskCount private
Definition at line 14 of file ProfileHandler.cs.
GoodTaskCount
TMP_Text ProfileHandler.GoodTaskCount private
Definition at line 17 of file ProfileHandler.cs.
BadTaskCount
TMP_Text ProfileHandler.BadTaskCount private
Definition at line 20 of file ProfileHandler.cs.
TotalScore
TMP_Text ProfileHandler.TotalScore private
Definition at line 23 of file ProfileHandler.cs.
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/ProfileHandler.cs