Bomberman: CoroutineRunner Class Reference
CoroutineRunner Class Reference
Static Public Member Functions
static Coroutine RunCoroutine (IEnumerator coroutine)
static void StopAllCoroutinesGlobal ()
Properties
static CoroutineRunner Instance [get]
Static Private Attributes
static CoroutineRunner _instance
Detailed Description
Definition at line 4 of file CoroutineRunner .cs.
Member Function Documentation
RunCoroutine()
static Coroutine CoroutineRunner.RunCoroutine (IEnumerator coroutine) inline static
Definition at line 24 of file CoroutineRunner .cs.
    {
        return Instance.StartCoroutine(coroutine);
    }
References Instance.
Referenced by MainPage.FriendHandler.AcceptFriendRequest(), ShopItem.Buy(), GameUI.BuyImmunity(), GameUI.BuyTurbo(), User.UserController.CheckLoggedIn(), User.LoggedInChecker.CheckLoggedInPeriodically(), MainPage.TaskDisplayHandler.CompleteTask(), MainPage.FriendHandler.DeleteFriend(), MainPage.TaskOpenPanelController.DeleteTask(), GameUI.DoubleCoins(), MainPage.FriendWindowHandler.LoadFriends(), LeaderboardWindow.LoadScores(), MainPage.TaskHistoryWindowHandler.LoadTaskHistories(), MainPage.MainWindowController.LoadTasks(), User.UserController.LoggedIn(), MainPage.ProfileHandler.LoggedOut(), User.UserController.Registered(), MainPage.TaskOpenPanelController.Save(), GameUI.SaveGameResult(), MainPage.FriendWindowHandler.SendFriendRequest(), User.UserController.SendLogin(), MainPage.ProfileHandler.SendLogout(), User.UserController.SendRegister(), MainPage.TaskDisplayHandler.TaskCompleted(), and ShopWindow.UpdateShop().
StopAllCoroutinesGlobal()
static void CoroutineRunner.StopAllCoroutinesGlobal () inline static
Definition at line 29 of file CoroutineRunner .cs.
    {
        Instance.StopAllCoroutines(); // Directly stop coroutines without recursion
    }
References Instance.
Member Data Documentation
_instance
CoroutineRunner CoroutineRunner._instance static private
Definition at line 6 of file CoroutineRunner .cs.
Property Documentation
Instance
CoroutineRunner CoroutineRunner.Instance static get
Definition at line 8 of file CoroutineRunner .cs.
    {
        get
        {
            if (_instance == null)
            {
                // Create a new GameObject to host the CoroutineRunner if it doesn't exist
                GameObject obj = new GameObject("CoroutineRunner");
                _instance = obj.AddComponent<CoroutineRunner>();
                DontDestroyOnLoad(obj); // Make sure it persists across scenes
            }
            return _instance;
        }
    }
Referenced by RunCoroutine(), and StopAllCoroutinesGlobal().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Utility/CoroutineRunner .cs