Bomberman: TaskOpenPanelController Class Reference
TaskOpenPanelController Class Reference
Public Member Functions
void OpenUp ()
void OpenUp (PlayerTask taskContainer=null, TaskType type=TaskType.GoodTask)
void MakeItBadHabit ()
void MakeItGoodTask ()
void Cancel ()
void Save ()
void DeleteTask ()
Public Attributes
PlayerTask CurrentTask = new PlayerTask() { ID = -1 }
EventHandler< TaskClosedEventArgs > TaskClosedEventHandler
Static Public Attributes
static readonly int[] TASKINTERVALS = { 60, 120, 240, 1440, 2880, 10080, 20160, 40320 }
Private Member Functions
void SavedTask (Thesis_backend.Data_Structures.PlayerTask savedTask)
void DeletedTask (string result)
void CollectFromFields ()
void UpdateButtons ()
Private Attributes
GameObject tasksOpenPanel
TMP_InputField taskNameInput
TMP_Dropdown taskIntervals
TMP_InputField descriptionInput
Button goodTaskButton
Button badHabitButton
MainWindowController UIController
Button deleteTaskButton
bool isNewTask = false
PlayerTask playerTaskOnOpen
Detailed Description
Definition at line 14 of file TaskOpenPanelController.cs.
Member Function Documentation
OpenUp() [1/2]
void TaskOpenPanelController.OpenUp () inline
Definition at line 52 of file TaskOpenPanelController.cs.
    {
        if (this.CurrentTask is not null)
        {
            OpenUp(type: this.CurrentTask.TaskType ? TaskType.BadHabit : TaskType.GoodTask);
        }
        else
        {
            OpenUp(null);
        }
    }
References OpenUp().
Referenced by TaskDisplayHandler.OpenEditor(), and OpenUp().
OpenUp() [2/2]
void TaskOpenPanelController.OpenUp (PlayerTask taskContainer = null, TaskType type = TaskType::GoodTask) inline
Definition at line 64 of file TaskOpenPanelController.cs.
    {
        if (taskContainer is not null)
        {
            this.CurrentTask = taskContainer;
            this.isNewTask = false;
            this.playerTaskOnOpen = new PlayerTask(taskContainer);
        }
        else
        {
            this.CurrentTask = new PlayerTask() { ID = -1 };
            this.CurrentTask.ChangeType(type);
            this.isNewTask = true;
            this.playerTaskOnOpen = null;
        }
        taskNameInput.text = this.CurrentTask.TaskName;
        descriptionInput.text = this.CurrentTask.Description;
        for (int i = 0; i < TASKINTERVALS.Length; i++)
        {
            if (TASKINTERVALS[i] == (int)this.CurrentTask.PeriodRate)
            {
                taskIntervals.SetValueWithoutNotify(i);
                break;
            }
        }
        deleteTaskButton.gameObject.SetActive(!isNewTask);
        tasksOpenPanel.SetActive(true);
        UpdateButtons();
    }
References deleteTaskButton, isNewTask, Thesis_backend.Data_Structures.PlayerTask, taskIntervals, TASKINTERVALS, tasksOpenPanel, and UpdateButtons().
MakeItBadHabit()
void TaskOpenPanelController.MakeItBadHabit () inline
Definition at line 100 of file TaskOpenPanelController.cs.
    {
        this.CurrentTask?.ChangeType(TaskType.BadHabit);
        UpdateButtons();
        UIController.LoadBadHabits(false);
    }
References MainWindowController.LoadBadHabits(), UIController, and UpdateButtons().
Referenced by MainWindowController.LoadBadHabits().
MakeItGoodTask()
void TaskOpenPanelController.MakeItGoodTask () inline
Definition at line 108 of file TaskOpenPanelController.cs.
    {
        this.CurrentTask?.ChangeType(TaskType.GoodTask);
        UpdateButtons();
        UIController.LoadGoodTasks(false);
    }
References MainWindowController.LoadGoodTasks(), UIController, and UpdateButtons().
Referenced by MainWindowController.LoadGoodTasks().
Cancel()
void TaskOpenPanelController.Cancel () inline
Definition at line 116 of file TaskOpenPanelController.cs.
    {
        this.TaskClosedEventHandler?.Invoke(this, new TaskClosedEventArgs(false));
        tasksOpenPanel.SetActive(false);
        if (this.CurrentTask.ID != -1)
        {
            if (playerTaskOnOpen is not null)
            {
                CurrentTask.UpdateValues(playerTaskOnOpen);
                if (playerTaskOnOpen.TaskType)
                {
                    UIController.LoadBadHabits();
                }
                else
                {
                    UIController.LoadGoodTasks();
                }
                this.CurrentTask = playerTaskOnOpen;
            }
        }
        this.CurrentTask = new PlayerTask();
    }
References CurrentTask, MainWindowController.LoadBadHabits(), MainWindowController.LoadGoodTasks(), Thesis_backend.Data_Structures.PlayerTask, playerTaskOnOpen, tasksOpenPanel, and UIController.
Referenced by DeletedTask().
Save()
void TaskOpenPanelController.Save () inline
Definition at line 140 of file TaskOpenPanelController.cs.
    {
        CollectFromFields();
        TaskRequest taskRequest = new TaskRequest()
        {
            TaskName = this.CurrentTask.TaskName,
            Description = this.CurrentTask.Description,
            PeriodRate = (int)CurrentTask.PeriodRate,
            TaskType = Convert.ToBoolean(CurrentTask.TaskType)
        };
        if (isNewTask)
        {
            CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKCREATE, taskRequest, SavedTask, onFailedAction: UIController.ShowTaskFail));
        }
        else
        {
            CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKUPDATE(CurrentTask.ID), taskRequest, SavedTask, onFailedAction: UIController.ShowTaskFail));
        }
    }
References CollectFromFields(), CurrentTask, Thesis_backend.Data_Structures.Description, isNewTask, Config.ServerConfig.PATHFORTASKCREATE, Config.ServerConfig.PATHFORTASKUPDATE(), Thesis_backend.Data_Structures.PeriodRate, CoroutineRunner.RunCoroutine(), SavedTask(), MainWindowController.ShowTaskFail(), Thesis_backend.Data_Structures.TaskName, Thesis_backend.Data_Structures.TaskRequest.TaskName, and UIController.
SavedTask()
void TaskOpenPanelController.SavedTask (Thesis_backend::Data_Structures::PlayerTask savedTask) inline private
Definition at line 162 of file TaskOpenPanelController.cs.
    {
        this.TaskClosedEventHandler?.Invoke(this, new TaskClosedEventArgs(true));
        tasksOpenPanel.SetActive(false);
        bool isNewTask = CurrentTask.ID == -1;
        this.CurrentTask = savedTask;
        if (isNewTask)
        {
            UIController.CreateTask(this.CurrentTask);
        }
        else
        {
            UIController.UpdateTask(CurrentTask.ID);
        }
        UIController.SortingChanged();
        this.CurrentTask = new PlayerTask();
    }
References MainWindowController.CreateTask(), CurrentTask, isNewTask, Thesis_backend.Data_Structures.PlayerTask, MainWindowController.SortingChanged(), tasksOpenPanel, UIController, and MainWindowController.UpdateTask().
Referenced by Save().
DeleteTask()
void TaskOpenPanelController.DeleteTask () inline
Definition at line 183 of file TaskOpenPanelController.cs.
    {
        CoroutineRunner.RunCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORTASKDELETE(CurrentTask.ID), onComplete: DeletedTask, onFailedAction: UIController.ShowTaskFail));
    }
References CurrentTask, DeletedTask(), Config.ServerConfig.PATHFORTASKDELETE(), CoroutineRunner.RunCoroutine(), MainWindowController.ShowTaskFail(), and UIController.
DeletedTask()
void TaskOpenPanelController.DeletedTask (string result) inline private
Definition at line 188 of file TaskOpenPanelController.cs.
    {
        UIController.RemoveTask(CurrentTask.ID);
        Cancel();
    }
References Cancel(), CurrentTask, MainWindowController.RemoveTask(), and UIController.
Referenced by DeleteTask().
CollectFromFields()
void TaskOpenPanelController.CollectFromFields () inline private
Definition at line 194 of file TaskOpenPanelController.cs.
    {
        string taskName = taskNameInput.text;
        string description = descriptionInput.text;
        TaskIntervals taskInterval = (TaskIntervals)TASKINTERVALS[taskIntervals.value];
        CurrentTask.UpdateValues(taskName, CurrentTask.TaskType, taskInterval, description);
    }
References CurrentTask, descriptionInput, taskIntervals, TASKINTERVALS, and taskNameInput.
Referenced by Save().
UpdateButtons()
void TaskOpenPanelController.UpdateButtons () inline private
Definition at line 203 of file TaskOpenPanelController.cs.
    {
        if (!this.CurrentTask.TaskType)
        {
            goodTaskButton.image.color = new Color(134f / 255f, 1f, 90f / 255f, 1.0f);
            badHabitButton.image.color = new Color(185 / 255f, 185f / 255f, 185f / 255f, 1f);
        }
        else
        {
            goodTaskButton.image.color = new Color(185f / 255f, 185f / 255f, 185f / 255f, 1f);
            badHabitButton.image.color = new Color(248f / 255f, 34f / 255f, 44f / 255f, 1f);
        }
    }
Referenced by MakeItBadHabit(), MakeItGoodTask(), and OpenUp().
Member Data Documentation
CurrentTask
PlayerTask TaskOpenPanelController.CurrentTask = new PlayerTask() { ID = -1 }
Definition at line 17 of file TaskOpenPanelController.cs.
{ ID = -1 };
Referenced by Cancel(), CollectFromFields(), DeletedTask(), DeleteTask(), Save(), SavedTask(), and MainWindowController.SortingChanged().
TaskClosedEventHandler
EventHandler<TaskClosedEventArgs> TaskOpenPanelController.TaskClosedEventHandler
Definition at line 20 of file TaskOpenPanelController.cs.
tasksOpenPanel
GameObject TaskOpenPanelController.tasksOpenPanel private
Definition at line 23 of file TaskOpenPanelController.cs.
Referenced by Cancel(), OpenUp(), and SavedTask().
taskNameInput
TMP_InputField TaskOpenPanelController.taskNameInput private
Definition at line 26 of file TaskOpenPanelController.cs.
Referenced by CollectFromFields().
taskIntervals
TMP_Dropdown TaskOpenPanelController.taskIntervals private
Definition at line 29 of file TaskOpenPanelController.cs.
Referenced by CollectFromFields(), and OpenUp().
descriptionInput
TMP_InputField TaskOpenPanelController.descriptionInput private
Definition at line 32 of file TaskOpenPanelController.cs.
Referenced by CollectFromFields().
goodTaskButton
Button TaskOpenPanelController.goodTaskButton private
Definition at line 35 of file TaskOpenPanelController.cs.
badHabitButton
Button TaskOpenPanelController.badHabitButton private
Definition at line 38 of file TaskOpenPanelController.cs.
UIController
MainWindowController TaskOpenPanelController.UIController private
Definition at line 41 of file TaskOpenPanelController.cs.
Referenced by Cancel(), DeletedTask(), DeleteTask(), MakeItBadHabit(), MakeItGoodTask(), Save(), and SavedTask().
deleteTaskButton
Button TaskOpenPanelController.deleteTaskButton private
Definition at line 44 of file TaskOpenPanelController.cs.
Referenced by OpenUp().
isNewTask
bool TaskOpenPanelController.isNewTask = false private
Definition at line 46 of file TaskOpenPanelController.cs.
Referenced by OpenUp(), Save(), and SavedTask().
TASKINTERVALS
readonly int [] TaskOpenPanelController.TASKINTERVALS = { 60, 120, 240, 1440, 2880, 10080, 20160, 40320 } static
Definition at line 48 of file TaskOpenPanelController.cs.
{ 60, 120, 240, 1440, 2880, 10080, 20160, 40320 };
Referenced by CollectFromFields(), and OpenUp().
playerTaskOnOpen
PlayerTask TaskOpenPanelController.playerTaskOnOpen private
Definition at line 50 of file TaskOpenPanelController.cs.
Referenced by Cancel().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/WindowHandlers/TaskOpenPanelController.cs