Bomberman: UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager Class Reference
UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager Class Reference
Classes
class VirtualAxis
class VirtualButton
Public Types
enum ActiveInputMethod { Hardware , Touch }
Static Public Member Functions
static void SwitchActiveInputMethod (ActiveInputMethod activeInputMethod)
static bool AxisExists (string name)
static bool ButtonExists (string name)
static void RegisterVirtualAxis (VirtualAxis axis)
static void RegisterVirtualButton (VirtualButton button)
static void UnRegisterVirtualAxis (string name)
static void UnRegisterVirtualButton (string name)
static VirtualAxis VirtualAxisReference (string name)
static float GetAxis (string name)
static float GetAxisRaw (string name)
static bool GetButton (string name)
static bool GetButtonDown (string name)
static bool GetButtonUp (string name)
static void SetButtonDown (string name)
static void SetButtonUp (string name)
static void SetAxisPositive (string name)
static void SetAxisNegative (string name)
static void SetAxisZero (string name)
static void SetAxis (string name, float value)
static void SetVirtualMousePositionX (float f)
static void SetVirtualMousePositionY (float f)
static void SetVirtualMousePositionZ (float f)
Properties
static Vector3 mousePosition [get]
Static Private Member Functions
static CrossPlatformInputManager ()
static float GetAxis (string name, bool raw)
Static Private Attributes
static VirtualInput activeInput
static VirtualInput s_TouchInput
static VirtualInput s_HardwareInput
Detailed Description
Definition at line 7 of file CrossPlatformInputManager.cs.
Member Enumeration Documentation
ActiveInputMethod
enum UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.ActiveInputMethod
Enumerator
Hardware
Touch
Definition at line 9 of file CrossPlatformInputManager.cs.
    {
      Hardware,
      Touch
    }
Constructor & Destructor Documentation
CrossPlatformInputManager()
static UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.CrossPlatformInputManager () inline static private
Definition at line 22 of file CrossPlatformInputManager.cs.
    {
      s_TouchInput = new MobileInput();
      s_HardwareInput = new StandaloneInput();
#if MOBILE_INPUT
            activeInput = s_TouchInput;
#else
      activeInput = s_HardwareInput;
#endif
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_HardwareInput, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_TouchInput.
Member Function Documentation
SwitchActiveInputMethod()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SwitchActiveInputMethod (ActiveInputMethod activeInputMethod) inline static
Definition at line 33 of file CrossPlatformInputManager.cs.
    {
      switch (activeInputMethod)
      {
        case ActiveInputMethod.Hardware:
          activeInput = s_HardwareInput;
          break;
        case ActiveInputMethod.Touch:
          activeInput = s_TouchInput;
          break;
      }
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_HardwareInput, and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_TouchInput.
AxisExists()
static bool UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.AxisExists (string name) inline static
Definition at line 47 of file CrossPlatformInputManager.cs.
    {
      return activeInput.AxisExists(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.AxisExists().
Referenced by UnityStandardAssets.CrossPlatformInput.TouchPad.OnDisable(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable().
ButtonExists()
static bool UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.ButtonExists (string name) inline static
Definition at line 52 of file CrossPlatformInputManager.cs.
    {
      return activeInput.ButtonExists(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.ButtonExists().
RegisterVirtualAxis()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis (VirtualAxis axis) inline static
Definition at line 57 of file CrossPlatformInputManager.cs.
    {
      activeInput.RegisterVirtualAxis(axis);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualAxis().
Referenced by UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddAxes(), UnityStandardAssets.CrossPlatformInput.Joystick.CreateVirtualAxes(), UnityStandardAssets.CrossPlatformInput.TouchPad.CreateVirtualAxes(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable(), and UnityStandardAssets.CrossPlatformInput.TiltInput.OnEnable().
RegisterVirtualButton()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualButton (VirtualButton button) inline static
Definition at line 63 of file CrossPlatformInputManager.cs.
    {
      activeInput.RegisterVirtualButton(button);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualButton().
Referenced by UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.AddButton().
UnRegisterVirtualAxis()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualAxis (string name) inline static
Definition at line 69 of file CrossPlatformInputManager.cs.
    {
      if (name == null)
      {
        throw new ArgumentNullException("name");
      }
      activeInput.UnRegisterVirtualAxis(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualAxis().
Referenced by UnityStandardAssets.CrossPlatformInput.TouchPad.OnDisable(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxis.Remove().
UnRegisterVirtualButton()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualButton (string name) inline static
Definition at line 79 of file CrossPlatformInputManager.cs.
    {
      activeInput.UnRegisterVirtualButton(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualButton().
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualButton.Remove().
VirtualAxisReference()
static VirtualAxis UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxisReference (string name) inline static
Definition at line 86 of file CrossPlatformInputManager.cs.
    {
      return activeInput.VirtualAxisReference(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.VirtualAxisReference().
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable().
GetAxis() [1/2]
static float UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis (string name) inline static
Definition at line 93 of file CrossPlatformInputManager.cs.
    {
      return GetAxis(name, false);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis().
Referenced by Game.PlayerCar.FixedUpdate(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxisRaw().
GetAxisRaw()
static float UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxisRaw (string name) inline static
Definition at line 99 of file CrossPlatformInputManager.cs.
    {
      return GetAxis(name, true);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis().
GetAxis() [2/2]
static float UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis (string name, bool raw) inline static private
Definition at line 106 of file CrossPlatformInputManager.cs.
    {
      return activeInput.GetAxis(name, raw);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.GetAxis().
GetButton()
static bool UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButton (string name) inline static
Definition at line 113 of file CrossPlatformInputManager.cs.
    {
      return activeInput.GetButton(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButton().
GetButtonDown()
static bool UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonDown (string name) inline static
Definition at line 119 of file CrossPlatformInputManager.cs.
    {
      return activeInput.GetButtonDown(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButtonDown().
GetButtonUp()
static bool UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonUp (string name) inline static
Definition at line 125 of file CrossPlatformInputManager.cs.
    {
      return activeInput.GetButtonUp(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButtonUp().
SetButtonDown()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonDown (string name) inline static
Definition at line 131 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetButtonDown(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetButtonDown().
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetDownState().
SetButtonUp()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonUp (string name) inline static
Definition at line 137 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetButtonUp(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetButtonUp().
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetUpState().
SetAxisPositive()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisPositive (string name) inline static
Definition at line 143 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetAxisPositive(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisPositive().
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisPositiveState().
SetAxisNegative()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisNegative (string name) inline static
Definition at line 149 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetAxisNegative(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisNegative().
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNegativeState().
SetAxisZero()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisZero (string name) inline static
Definition at line 155 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetAxisZero(name);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisZero().
Referenced by UnityStandardAssets.CrossPlatformInput.ButtonHandler.SetAxisNeutralState().
SetAxis()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxis (string name, float value) inline static
Definition at line 161 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetAxis(name, value);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxis().
Referenced by UnityStandardAssets.CrossPlatformInput.InputAxisScrollbar.HandleInput().
SetVirtualMousePositionX()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionX (float f) inline static
Definition at line 173 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetVirtualMousePositionX(f);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionX().
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
SetVirtualMousePositionY()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionY (float f) inline static
Definition at line 179 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetVirtualMousePositionY(f);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionY().
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
SetVirtualMousePositionZ()
static void UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionZ (float f) inline static
Definition at line 185 of file CrossPlatformInputManager.cs.
    {
      activeInput.SetVirtualMousePositionZ(f);
    }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput, and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionZ().
Referenced by UnityStandardAssets.CrossPlatformInput.TiltInput.Update().
Member Data Documentation
activeInput
VirtualInput UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.activeInput static private
Definition at line 16 of file CrossPlatformInputManager.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.AxisExists(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.ButtonExists(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.CrossPlatformInputManager(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButton(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonDown(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonUp(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualButton(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxis(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisNegative(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisPositive(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisZero(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonDown(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonUp(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionX(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionY(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionZ(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SwitchActiveInputMethod(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualAxis(), UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualButton(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxisReference().
s_TouchInput
VirtualInput UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_TouchInput static private
Definition at line 18 of file CrossPlatformInputManager.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.CrossPlatformInputManager(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SwitchActiveInputMethod().
s_HardwareInput
VirtualInput UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.s_HardwareInput static private
Definition at line 19 of file CrossPlatformInputManager.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.CrossPlatformInputManager(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SwitchActiveInputMethod().
Property Documentation
mousePosition
Vector3 UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.mousePosition static get
Definition at line 167 of file CrossPlatformInputManager.cs.
    {
      get { return activeInput.MousePosition(); }
    }
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/CrossPlatformInputManager.cs