Thesis: Game.UI.GameUI Class Reference
Game.UI.GameUI Class Reference
Controller for the game's UI
Public Member Functions
void SaveGameResult ()
Save the game's result
void DoubleCoins ()
Buy the double coins bonus
void BuyImmunity ()
Buy the immunity power up
void BuyTurbo ()
Buy the turbo power up
void ShowLeaderboard ()
Show the leaderboard window
void LeftRotateSkin ()
Rotate the skin display to the left
void RightRotateSkin ()
Rotate the skin display to the right
void Init (GameController gameController)
Initializes the game use
async void NewGame (bool save=true)
Start a new game
void ChangeDifficulyDisplay (int difficulty)
Change the difficulty and update its display
void ShowEndGameScreen ()
Show the game over screen
void HideGameOverScreen (bool saveGameResults=true)
Hide the game over screen
void ShowShopWindow ()
Display the shop window
void HideShopWindow ()
Hides the shop window
void BackToTasks ()
Move back to the tasks
void BackToGameMenuWithoutSave ()
Show the main menu, but don't save the scores
void BackToGameMenu ()
Show the main menu
Properties
bool Doubled = false [get, private set]
Is the coins doubled now
int SelectedSkinIndex = 0 [get, private set]
The currently selected skin's index
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Member Functions
void Update ()
Called every frame
void SavedCoins (Thesis_backend.Data_Structures.Game game)
Callback after the coins amount were saved
void BoughtImmunity (Thesis_backend.Data_Structures.User user)
Callback after the player bought the immunity
void BoughtTurbo (Thesis_backend.Data_Structures.User user)
Callback after the player bought the turbo
void DoubledCoins (Thesis_backend.Data_Structures.User user)
Callback after the coins were doubled
void ShowRequestFail (string content)
Show if the request failed on the modal window
Private Attributes
GameObject gameOverContainer
GameObject ingameContainer
ShopWindow ShopWindow
GameObject mainMenuContainer
Image SkinDisplay
LeaderboardWindow leaderboardWindow
TMP_Text InfamyGameOverText
TMP_Text CoinGameOverText
TMP_Text InfamyInGameText
TMP_Text TaskScoreInGameText
TMP_Text CoinInGameText
StarHandler starHandler
Button DoubleCoinButon
ModalWindow ModalWindow
GameController gameController
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Detailed Description
Controller for the game's UI
Definition at line 18 of file GameUI.cs.
Member Function Documentation
Update()
void Game.UI.GameUI.Update () inline private
Called every frame
Definition at line 77 of file GameUI.cs.
             {
                 if (gameController.Running)
                 {
                     this.InfamyInGameText.text = "Infamy: " + gameController.Score;
                     this.CoinInGameText.text = Mathf.RoundToInt(gameController.Coins).ToString();
                     Keyboard keyboard = Keyboard.current;
                     // Make the powerups useable with keyboard
                     if (keyboard is not null)
                     {
                         InputSystem.Update();
                         if (keyboard.qKey.isPressed && !gameController.Player.Turbo)
{
                             BuyTurbo();
                         }
                         if (keyboard.eKey.isPressed && !gameController.Player.Immune)
{
                             BuyImmunity();
                         }
                     }
                 }
             }
References Game.UI.GameUI.BuyImmunity(), Game.UI.GameUI.BuyTurbo(), Game.GameController.Coins, Game.UI.GameUI.gameController, Game.PlayerCar.Immune, Game.GameController.Player, Game.GameController.Running, Game.GameController.Score, and Game.PlayerCar.Turbo.
SaveGameResult()
void Game.UI.GameUI.SaveGameResult () inline
Save the game's result
Definition at line 104 of file GameUI.cs.
             {
                 CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.Game>(ServerConfig.PATH_TO_ADD_COINS, (int)(Doubled ? gameController.Coins * 2 : gameController.Coins), SavedCoins, onFailedAction: ShowRequestFail));
                 CoroutineRunner.RunCoroutine(Server.SendPostRequest<Thesis_backend.Data_Structures.GameScore>(ServerConfig.PATH_FOR_STORE_GAME_SCORE, gameController.Score, onFailedAction: ShowRequestFail));
             }
References Game.GameController.Coins, Game.UI.GameUI.Doubled, Game.UI.GameUI.gameController, Config.ServerConfig.PATH_FOR_STORE_GAME_SCORE, Config.ServerConfig.PATH_TO_ADD_COINS, Utility.CoroutineRunner.RunCoroutine(), Game.UI.GameUI.SavedCoins(), Game.GameController.Score, and Game.UI.GameUI.ShowRequestFail().
Referenced by Game.UI.GameUI.HideGameOverScreen().
SavedCoins()
void Game.UI.GameUI.SavedCoins (Thesis_backend.Data_Structures.Game game) inline private
Callback after the coins amount were saved
Parameters
game The responded game with the updated coin amount
Definition at line 114 of file GameUI.cs.
             {
                 UserData.Instance.Game.Currency = game.Currency;
             }
References User.UserData.Game, and User.UserData.Instance.
Referenced by Game.UI.GameUI.SaveGameResult().
DoubleCoins()
void Game.UI.GameUI.DoubleCoins () inline
Buy the double coins bonus
Definition at line 122 of file GameUI.cs.
             {
                 if (UserData.Instance.CurrentTaskScore >= GameConfig.DOUBLE_COIN_COST)
                 {
                     CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_DOUBLE_COINS, new WWWForm(), DoubledCoins, onFailedAction: ShowRequestFail));
                 }
             }
References User.UserData.CurrentTaskScore, Game.GameConfig.DOUBLE_COIN_COST, Game.UI.GameUI.DoubledCoins(), User.UserData.Instance, Config.ServerConfig.PATH_FOR_DOUBLE_COINS, Utility.CoroutineRunner.RunCoroutine(), and Game.UI.GameUI.ShowRequestFail().
BuyImmunity()
void Game.UI.GameUI.BuyImmunity () inline
Buy the immunity power up
Definition at line 133 of file GameUI.cs.
             {
                 if (UserData.Instance.CurrentTaskScore >= GameConfig.IMMUNITY_COST)
                 {
                     CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_BUY_IMMUNITY, new WWWForm(), BoughtImmunity, onFailedAction: (string res) => { ShowRequestFail(res); gameController.Player.CancelImmunity(); }));
                     gameController.Player.ApplyImmunity();
                 }
             }
References Game.PlayerCar.ApplyImmunity(), Game.UI.GameUI.BoughtImmunity(), Game.PlayerCar.CancelImmunity(), User.UserData.CurrentTaskScore, Game.UI.GameUI.gameController, Game.GameConfig.IMMUNITY_COST, User.UserData.Instance, Config.ServerConfig.PATH_FOR_BUY_IMMUNITY, Game.GameController.Player, Utility.CoroutineRunner.RunCoroutine(), and Game.UI.GameUI.ShowRequestFail().
Referenced by Game.UI.GameUI.Update().
BuyTurbo()
void Game.UI.GameUI.BuyTurbo () inline
Buy the turbo power up
Definition at line 145 of file GameUI.cs.
             {
                 if (UserData.Instance.CurrentTaskScore >= GameConfig.TURBO_COST)
                 {
                     CoroutineRunner.RunCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATH_FOR_BUY_TURBO, new WWWForm(), BoughtTurbo, onFailedAction: (string res) => { ShowRequestFail(res); gameController.Player.CancelTurbo(); }));
                     gameController.Player.ApplyTurbo();
                 }
             }
References Game.PlayerCar.ApplyTurbo(), Game.UI.GameUI.BoughtTurbo(), Game.PlayerCar.CancelTurbo(), User.UserData.CurrentTaskScore, Game.UI.GameUI.gameController, User.UserData.Instance, Config.ServerConfig.PATH_FOR_BUY_TURBO, Game.GameController.Player, Utility.CoroutineRunner.RunCoroutine(), Game.UI.GameUI.ShowRequestFail(), and Game.GameConfig.TURBO_COST.
Referenced by Game.UI.GameUI.Update().
BoughtImmunity()
void Game.UI.GameUI.BoughtImmunity (Thesis_backend.Data_Structures.User user) inline private
Callback after the player bought the immunity
Parameters
user The user with the updated task score amount
Definition at line 158 of file GameUI.cs.
             {
                 UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
                 TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
             }
References User.UserData.CurrentTaskScore, User.UserData.Instance, Game.UI.GameUI.TaskScoreInGameText, and User.UserData.UpdateTaskScore().
Referenced by Game.UI.GameUI.BuyImmunity().
BoughtTurbo()
void Game.UI.GameUI.BoughtTurbo (Thesis_backend.Data_Structures.User user) inline private
Callback after the player bought the turbo
Parameters
user The user with the updated task score amount
Definition at line 168 of file GameUI.cs.
             {
                 UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
                 TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
             }
References User.UserData.CurrentTaskScore, User.UserData.Instance, Game.UI.GameUI.TaskScoreInGameText, and User.UserData.UpdateTaskScore().
Referenced by Game.UI.GameUI.BuyTurbo().
DoubledCoins()
void Game.UI.GameUI.DoubledCoins (Thesis_backend.Data_Structures.User user) inline private
Callback after the coins were doubled
Parameters
user The user with the updated task score amount
Definition at line 178 of file GameUI.cs.
             {
                 this.Doubled = true;
                 this.DoubleCoinButon.interactable = false;
                 CoinGameOverText.text = "Coins: " + gameController.Coins * 2;
                 TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
                 UserData.Instance.UpdateTaskScore(user.CurrentTaskScore);
             }
References Game.UI.GameUI.CoinGameOverText, Game.GameController.Coins, User.UserData.CurrentTaskScore, Game.UI.GameUI.Doubled, Game.UI.GameUI.gameController, User.UserData.Instance, Game.UI.GameUI.TaskScoreInGameText, and User.UserData.UpdateTaskScore().
Referenced by Game.UI.GameUI.DoubleCoins().
ShowLeaderboard()
void Game.UI.GameUI.ShowLeaderboard () inline
Show the leaderboard window
Definition at line 190 of file GameUI.cs.
             {
                 leaderboardWindow.Show();
             }
References Game.UI.GameUI.leaderboardWindow, and Game.UI.LeaderboardWindow.Show().
LeftRotateSkin()
void Game.UI.GameUI.LeftRotateSkin () inline
Rotate the skin display to the left
Definition at line 198 of file GameUI.cs.
             {
                 SelectedSkinIndex = (SelectedSkinIndex + UserData.Instance.Game.OwnedCars.Count - 1) % UserData.Instance.Game.OwnedCars.Count;
                 SkinDisplay.sprite = ShopWindow.ShopItemSprites[(int)UserData.Instance.Game.OwnedCars[SelectedSkinIndex].ShopId - 1];
             }
References User.UserData.Game, User.UserData.Instance, Game.UI.GameUI.SelectedSkinIndex, Game.UI.ShopWindow.ShopItemSprites, and Game.UI.GameUI.SkinDisplay.
RightRotateSkin()
void Game.UI.GameUI.RightRotateSkin () inline
Rotate the skin display to the right
Definition at line 207 of file GameUI.cs.
             {
                 SelectedSkinIndex = (SelectedSkinIndex + 1) % UserData.Instance.Game.OwnedCars.Count;
                 SkinDisplay.sprite = ShopWindow.ShopItemSprites[(int)UserData.Instance.Game.OwnedCars[SelectedSkinIndex].ShopId - 1];
             }
References User.UserData.Game, User.UserData.Instance, Game.UI.GameUI.SelectedSkinIndex, Game.UI.ShopWindow.ShopItemSprites, and Game.UI.GameUI.SkinDisplay.
Init()
void Game.UI.GameUI.Init (GameController gameController) inline
Initializes the game use
Parameters
gameController Reference to the game controller
Definition at line 217 of file GameUI.cs.
             {
                 this.gameController = gameController;
             }
References Game.UI.GameUI.gameController.
Referenced by Game.GameController.Awake().
NewGame()
async void Game.UI.GameUI.NewGame (bool save = true) inline
Start a new game
Parameters
save Should it save the gamecontroller's values
Definition at line 226 of file GameUI.cs.
             {
                 HideGameOverScreen(save);
                 ingameContainer.SetActive(true);
                 mainMenuContainer.SetActive(false);
                 TaskScoreInGameText.text = UserData.Instance.CurrentTaskScore.ToString();
                 await gameController?.NewGame();
             }
References User.UserData.CurrentTaskScore, Game.UI.GameUI.gameController, Game.UI.GameUI.HideGameOverScreen(), Game.UI.GameUI.ingameContainer, User.UserData.Instance, Game.UI.GameUI.mainMenuContainer, Game.GameController.NewGame(), and Game.UI.GameUI.TaskScoreInGameText.
ShowRequestFail()
void Game.UI.GameUI.ShowRequestFail (string content) inline private
Show if the request failed on the modal window
Parameters
content The content to display
Definition at line 239 of file GameUI.cs.
             {
                 ModalWindow.Show("Request fail", content);
             }
References Utility.ModalWindow.Show().
Referenced by Game.UI.GameUI.BuyImmunity(), Game.UI.GameUI.BuyTurbo(), Game.UI.GameUI.DoubleCoins(), and Game.UI.GameUI.SaveGameResult().
ChangeDifficulyDisplay()
void Game.UI.GameUI.ChangeDifficulyDisplay (int difficulty) inline
Change the difficulty and update its display
Parameters
difficulty The new difficulty
Definition at line 248 of file GameUI.cs.
             {
                 this.starHandler.ChangeDifficulty(difficulty);
             }
References Game.UI.StarHandler.ChangeDifficulty().
Referenced by Game.GameController.NewGame(), and Game.GameController.Update().
ShowEndGameScreen()
void Game.UI.GameUI.ShowEndGameScreen () inline
Show the game over screen
Definition at line 256 of file GameUI.cs.
             {
                 InfamyGameOverText.text = "Infamy: " + gameController.Score;
                 CoinGameOverText.text = "Coins: " + gameController.Coins;
                 ingameContainer.SetActive(false);
                 gameOverContainer.SetActive(true);
                 Doubled = false;
                 this.DoubleCoinButon.interactable = UserData.Instance.CurrentTaskScore >= 1000;
             }
References Game.UI.GameUI.CoinGameOverText, Game.GameController.Coins, User.UserData.CurrentTaskScore, Game.UI.GameUI.Doubled, Game.UI.GameUI.gameController, Game.UI.GameUI.gameOverContainer, Game.UI.GameUI.InfamyGameOverText, Game.UI.GameUI.ingameContainer, User.UserData.Instance, and Game.GameController.Score.
Referenced by Game.GameController.PlayerDied().
HideGameOverScreen()
void Game.UI.GameUI.HideGameOverScreen (bool saveGameResults = true) inline
Hide the game over screen
Parameters
saveGameResults Should it save the score and the currencies
Definition at line 270 of file GameUI.cs.
             {
                 gameOverContainer.SetActive(false);
                 ingameContainer.SetActive(true);
                 if (saveGameResults)
                 {
                     SaveGameResult();
                 }
             }
References Game.UI.GameUI.gameOverContainer, Game.UI.GameUI.ingameContainer, and Game.UI.GameUI.SaveGameResult().
Referenced by Game.UI.GameUI.BackToGameMenu(), Game.UI.GameUI.BackToGameMenuWithoutSave(), Game.UI.GameUI.BackToTasks(), and Game.UI.GameUI.NewGame().
ShowShopWindow()
void Game.UI.GameUI.ShowShopWindow () inline
Display the shop window
Definition at line 283 of file GameUI.cs.
             {
                 this.ShopWindow.Show();
             }
References Game.UI.ShopWindow.Show().
HideShopWindow()
void Game.UI.GameUI.HideShopWindow () inline
Hides the shop window
Definition at line 291 of file GameUI.cs.
             {
                 this.ShopWindow.Hide();
             }
References Game.UI.ShopWindow.Hide().
BackToTasks()
void Game.UI.GameUI.BackToTasks () inline
Move back to the tasks
Definition at line 299 of file GameUI.cs.
             {
                 HideGameOverScreen(false);
                 SceneManager.LoadScene("MainScene", LoadSceneMode.Single);
             }
References Game.UI.GameUI.HideGameOverScreen().
BackToGameMenuWithoutSave()
void Game.UI.GameUI.BackToGameMenuWithoutSave () inline
Show the main menu, but don't save the scores
Definition at line 308 of file GameUI.cs.
             {
                 gameController.Player.Kill();
                 HideGameOverScreen(false);
                 ingameContainer.SetActive(false);
                 mainMenuContainer.SetActive(true);
             }
References Game.UI.GameUI.gameController, Game.UI.GameUI.HideGameOverScreen(), Game.UI.GameUI.ingameContainer, Game.Car.Kill(), Game.UI.GameUI.mainMenuContainer, and Game.GameController.Player.
BackToGameMenu()
void Game.UI.GameUI.BackToGameMenu () inline
Show the main menu
Definition at line 319 of file GameUI.cs.
             {
                 HideGameOverScreen();
                 ingameContainer.SetActive(false);
                 mainMenuContainer.SetActive(true);
             }
References Game.UI.GameUI.HideGameOverScreen(), Game.UI.GameUI.ingameContainer, and Game.UI.GameUI.mainMenuContainer.
Member Data Documentation
gameOverContainer
GameObject Game.UI.GameUI.gameOverContainer private
Definition at line 21 of file GameUI.cs.
Referenced by Game.UI.GameUI.HideGameOverScreen(), and Game.UI.GameUI.ShowEndGameScreen().
ingameContainer
GameObject Game.UI.GameUI.ingameContainer private
Definition at line 24 of file GameUI.cs.
Referenced by Game.UI.GameUI.BackToGameMenu(), Game.UI.GameUI.BackToGameMenuWithoutSave(), Game.UI.GameUI.HideGameOverScreen(), Game.UI.GameUI.NewGame(), and Game.UI.GameUI.ShowEndGameScreen().
ShopWindow
ShopWindow Game.UI.GameUI.ShopWindow private
Definition at line 27 of file GameUI.cs.
mainMenuContainer
GameObject Game.UI.GameUI.mainMenuContainer private
Definition at line 30 of file GameUI.cs.
Referenced by Game.UI.GameUI.BackToGameMenu(), Game.UI.GameUI.BackToGameMenuWithoutSave(), and Game.UI.GameUI.NewGame().
SkinDisplay
Image Game.UI.GameUI.SkinDisplay private
Definition at line 33 of file GameUI.cs.
Referenced by Game.UI.GameUI.LeftRotateSkin(), and Game.UI.GameUI.RightRotateSkin().
leaderboardWindow
LeaderboardWindow Game.UI.GameUI.leaderboardWindow private
Definition at line 36 of file GameUI.cs.
Referenced by Game.UI.GameUI.ShowLeaderboard().
InfamyGameOverText
TMP_Text Game.UI.GameUI.InfamyGameOverText private
Definition at line 39 of file GameUI.cs.
Referenced by Game.UI.GameUI.ShowEndGameScreen().
CoinGameOverText
TMP_Text Game.UI.GameUI.CoinGameOverText private
Definition at line 42 of file GameUI.cs.
Referenced by Game.UI.GameUI.DoubledCoins(), and Game.UI.GameUI.ShowEndGameScreen().
InfamyInGameText
TMP_Text Game.UI.GameUI.InfamyInGameText private
Definition at line 45 of file GameUI.cs.
TaskScoreInGameText
TMP_Text Game.UI.GameUI.TaskScoreInGameText private
Definition at line 48 of file GameUI.cs.
Referenced by Game.UI.GameUI.BoughtImmunity(), Game.UI.GameUI.BoughtTurbo(), Game.UI.GameUI.DoubledCoins(), and Game.UI.GameUI.NewGame().
CoinInGameText
TMP_Text Game.UI.GameUI.CoinInGameText private
Definition at line 51 of file GameUI.cs.
starHandler
StarHandler Game.UI.GameUI.starHandler private
Definition at line 54 of file GameUI.cs.
DoubleCoinButon
Button Game.UI.GameUI.DoubleCoinButon private
Definition at line 57 of file GameUI.cs.
ModalWindow
ModalWindow Game.UI.GameUI.ModalWindow private
Definition at line 60 of file GameUI.cs.
gameController
GameController Game.UI.GameUI.gameController private
Definition at line 62 of file GameUI.cs.
Referenced by Game.UI.GameUI.BackToGameMenuWithoutSave(), Game.UI.GameUI.BuyImmunity(), Game.UI.GameUI.BuyTurbo(), Game.UI.GameUI.DoubledCoins(), Game.UI.GameUI.Init(), Game.UI.GameUI.NewGame(), Game.UI.GameUI.SaveGameResult(), Game.UI.GameUI.ShowEndGameScreen(), and Game.UI.GameUI.Update().
Property Documentation
Doubled
bool Game.UI.GameUI.Doubled = false get private set
Is the coins doubled now
Definition at line 67 of file GameUI.cs.
 { get; private set; } = false;
Referenced by Game.UI.GameUI.DoubledCoins(), Game.UI.GameUI.SaveGameResult(), and Game.UI.GameUI.ShowEndGameScreen().
SelectedSkinIndex
int Game.UI.GameUI.SelectedSkinIndex = 0 get private set
The currently selected skin's index
Definition at line 72 of file GameUI.cs.
 { get; private set; } = 0;
Referenced by Game.UI.GameUI.LeftRotateSkin(), Game.GameController.NewGame(), and Game.UI.GameUI.RightRotateSkin().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/GameUI.cs