Bomberman: TaskDisplayHandler Class Reference
TaskDisplayHandler Class Reference
Public Member Functions
void Update ()
void InitValues (PlayerTask taskContainer, TaskOpenPanelController taskOpenPanelController, MainWindowController uIController)
void CompleteTask ()
void OpenEditor ()
void UpdateLabels ()
Properties
PlayerTask CurrentTask [get, private set]
Private Member Functions
void TaskCompleted (Thesis_backend.Data_Structures.PlayerTask result)
void CompleteStateChange (bool state)
void UpdateTimeRemaining ()
bool CalculateIfCompleteable ()
Private Attributes
TMP_Text TaskNameLabel
TMP_Text TaskIntervalsLabel
TMP_Text RemainingTimeLabel
Button CompleteButton
MainWindowController UIController
TaskOpenPanelController taskOpenPanelController
Static Private Attributes
static Color AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f)
static Color DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f)
Detailed Description
Definition at line 13 of file TaskDisplayHandler.cs.
Member Function Documentation
Update()
void TaskDisplayHandler.Update () inline
Definition at line 36 of file TaskDisplayHandler.cs.
    {
        if (CurrentTask.Completed)
        {
            UpdateTimeRemaining();
        }
    }
References CurrentTask, and UpdateTimeRemaining().
InitValues()
void TaskDisplayHandler.InitValues (PlayerTask taskContainer, TaskOpenPanelController taskOpenPanelController, MainWindowController uIController) inline
Definition at line 44 of file TaskDisplayHandler.cs.
    {
        this.CurrentTask = taskContainer;
        if (!CalculateIfCompleteable())
        {
            CompleteStateChange(true);
        }
        this.taskOpenPanelController = taskOpenPanelController;
        this.UIController = uIController;
        UpdateLabels();
    }
References CalculateIfCompleteable(), CompleteStateChange(), taskOpenPanelController, and UpdateLabels().
Referenced by MainWindowController.CreateTask().
CompleteTask()
void TaskDisplayHandler.CompleteTask () inline
Definition at line 57 of file TaskDisplayHandler.cs.
    {
        WWWForm form = new WWWForm();
        StartCoroutine(Server.SendPatchRequest<Thesis_backend.Data_Structures.PlayerTask>(ServerConfig.PATHFORTASKCOMPLETE(CurrentTask.ID), onComplete: TaskCompleted, onFailedAction: UIController.ShowTaskFail));
    }
References CurrentTask, Config.ServerConfig.PATHFORTASKCOMPLETE(), MainWindowController.ShowTaskFail(), TaskCompleted(), and UIController.
OpenEditor()
void TaskDisplayHandler.OpenEditor () inline
Definition at line 64 of file TaskDisplayHandler.cs.
    {
        taskOpenPanelController.OpenUp(this.CurrentTask);
    }
References CurrentTask, TaskOpenPanelController.OpenUp(), and taskOpenPanelController.
TaskCompleted()
void TaskDisplayHandler.TaskCompleted (Thesis_backend::Data_Structures::PlayerTask result) inline private
Definition at line 69 of file TaskDisplayHandler.cs.
    {
        CompleteStateChange(true);
        StartCoroutine(Server.SendGetRequest<Thesis_backend.Data_Structures.User>(ServerConfig.PATHFORCHECKLOGGEDIN, UIController.UpdateUserData, onFailedAction: UIController.ShowTaskFail));
    }
References CompleteStateChange(), Config.ServerConfig.PATHFORCHECKLOGGEDIN, MainWindowController.ShowTaskFail(), UIController, and MainWindowController.UpdateUserData().
Referenced by CompleteTask().
UpdateLabels()
void TaskDisplayHandler.UpdateLabels () inline
Definition at line 75 of file TaskDisplayHandler.cs.
    {
        TaskNameLabel.text = CurrentTask.TaskName;
        TaskIntervalsLabel.text = ((TaskIntervals)CurrentTask.PeriodRate).ToString();
        UpdateTimeRemaining();
    }
References CurrentTask, and UpdateTimeRemaining().
Referenced by InitValues().
CompleteStateChange()
void TaskDisplayHandler.CompleteStateChange (bool state) inline private
Definition at line 82 of file TaskDisplayHandler.cs.
    {
        RemainingTimeLabel.gameObject.SetActive(state);
        if (state)
        {
            this.CurrentTask.Complete();
            CompleteButton.GetComponent<Image>().color = DISABLED_FOR_COMPLETE_COLOR;
            UpdateTimeRemaining();
        }
        else
        {
            this.CurrentTask.ResetComplete();
            CompleteButton.GetComponent<Image>().color = AVAILIBLE_FOR_COMPLETE_COLOR;
            return;
        }
    }
References AVAILIBLE_FOR_COMPLETE_COLOR, CurrentTask, DISABLED_FOR_COMPLETE_COLOR, RemainingTimeLabel, and UpdateTimeRemaining().
Referenced by InitValues(), TaskCompleted(), and UpdateTimeRemaining().
UpdateTimeRemaining()
void TaskDisplayHandler.UpdateTimeRemaining () inline private
Definition at line 99 of file TaskDisplayHandler.cs.
    {
        if (CurrentTask.Completed)
        {
            TimeSpan difference = TimeSpan.FromMinutes(CurrentTask.PeriodRate) - (DateTime.UtcNow - CurrentTask.LastCompleted);
            if (difference.TotalMinutes <= 0)
            {
                CompleteStateChange(false);
                return;
            }
            string formatted = string.Format("{0} days {1:D2}:{2:D2}:{3:D2}",
            (int)difference.TotalDays, difference.Hours, difference.Minutes, difference.Seconds);
            RemainingTimeLabel.text = formatted;
        }
    }
References CompleteStateChange(), and CurrentTask.
Referenced by CompleteStateChange(), Update(), and UpdateLabels().
CalculateIfCompleteable()
bool TaskDisplayHandler.CalculateIfCompleteable () inline private
Definition at line 118 of file TaskDisplayHandler.cs.
    {
        TimeSpan difference = TimeSpan.FromMinutes(CurrentTask.PeriodRate) - (DateTime.UtcNow - CurrentTask.LastCompleted);
        return difference.TotalMinutes <= 0;
    }
References CurrentTask.
Referenced by InitValues().
Member Data Documentation
AVAILIBLE_FOR_COMPLETE_COLOR
Color TaskDisplayHandler.AVAILIBLE_FOR_COMPLETE_COLOR = new Color(70 / 255f, 1f, 0, 1f) static private
Definition at line 15 of file TaskDisplayHandler.cs.
Referenced by CompleteStateChange().
DISABLED_FOR_COMPLETE_COLOR
Color TaskDisplayHandler.DISABLED_FOR_COMPLETE_COLOR = new Color(73 / 255f, 59 / 255f, 71 / 255f, 1f) static private
Definition at line 16 of file TaskDisplayHandler.cs.
Referenced by CompleteStateChange().
TaskNameLabel
TMP_Text TaskDisplayHandler.TaskNameLabel private
Definition at line 19 of file TaskDisplayHandler.cs.
TaskIntervalsLabel
TMP_Text TaskDisplayHandler.TaskIntervalsLabel private
Definition at line 22 of file TaskDisplayHandler.cs.
RemainingTimeLabel
TMP_Text TaskDisplayHandler.RemainingTimeLabel private
Definition at line 25 of file TaskDisplayHandler.cs.
Referenced by CompleteStateChange().
CompleteButton
Button TaskDisplayHandler.CompleteButton private
Definition at line 28 of file TaskDisplayHandler.cs.
UIController
MainWindowController TaskDisplayHandler.UIController private
Definition at line 30 of file TaskDisplayHandler.cs.
Referenced by CompleteTask(), and TaskCompleted().
taskOpenPanelController
TaskOpenPanelController TaskDisplayHandler.taskOpenPanelController private
Definition at line 32 of file TaskDisplayHandler.cs.
Referenced by InitValues(), and OpenEditor().
Property Documentation
CurrentTask
PlayerTask TaskDisplayHandler.CurrentTask get private set
Definition at line 34 of file TaskDisplayHandler.cs.
{ get; private set; }
Referenced by CalculateIfCompleteable(), CompleteStateChange(), CompleteTask(), OpenEditor(), Update(), UpdateLabels(), and UpdateTimeRemaining().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/DisplayElements/TaskDisplayHandler.cs