Thesis: Game.UI.ShopWindow Class Reference
Game.UI.ShopWindow Class Reference
Handles the shop window's content display
Public Member Functions
void Show ()
Show the shop window
void Hide ()
Hide the shop window
void ShowRequestFail (string content)
Show if the request failed on the modal window
void UpdateShop ()
Update the shop items
string GetCoinText ()
Get's the coin's displayed text
GameObject GetShopParent ()
Gets the shop's parent
Public Attributes
List< Sprite > ShopItemSprites = new List<Sprite>()
Shop item sprites (needs to be in order with the shop ids)
Private Member Functions
void LoadedShopItems (List< Shop > shopItems)
Display the loaded shop items
Private Attributes
GameObject ShopParent
The parent of the shop items
GameObject ShopItemPrefab
A single shop item's prefab
TMP_Text CoinText
Reference to the coin text display
ModalWindow ModalWindow
Reference to the modal window in the scene
List< Shop > shopItemsCache
Cached shop items so we don't have to refresh every time since it is static mostly
Additional Inherited Members
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Detailed Description
Handles the shop window's content display
Definition at line 16 of file ShopWindow.cs.
Member Function Documentation
Show()
void Game.UI.ShopWindow.Show () inline
Show the shop window
Definition at line 56 of file ShopWindow.cs.
             {
                 this.gameObject.SetActive(true);
                 UpdateShop();
             }
References Game.UI.ShopWindow.UpdateShop().
Referenced by Game.UI.GameUI.ShowShopWindow().
Hide()
void Game.UI.ShopWindow.Hide () inline
Hide the shop window
Definition at line 66 of file ShopWindow.cs.
             {
                 this.gameObject.SetActive(false);
             }
Referenced by Game.UI.GameUI.HideShopWindow().
ShowRequestFail()
void Game.UI.ShopWindow.ShowRequestFail (string content) inline
Show if the request failed on the modal window
Parameters
content The content to show
Definition at line 75 of file ShopWindow.cs.
             {
                 ModalWindow.Show("Shop error", content);
             }
References Utility.ModalWindow.Show().
Referenced by Game.UI.ShopItem.Buy(), and Game.UI.ShopWindow.UpdateShop().
UpdateShop()
void Game.UI.ShopWindow.UpdateShop () inline
Update the shop items
Definition at line 83 of file ShopWindow.cs.
             {
                 if (shopItemsCache is null)
                 {
                     CoroutineRunner.RunCoroutine(Server.SendGetRequest<List<Shop>>(ServerConfig.PATH_FOR_SHOP_GET_ALL, LoadedShopItems, onFailedAction: ShowRequestFail));
                 }
                 else
                 {
                     LoadedShopItems(shopItemsCache);
                 }
                 CoinText.text = UserData.Instance.Game.Currency.ToString();
             }
References Game.UI.ShopWindow.CoinText, User.UserData.Game, User.UserData.Instance, Game.UI.ShopWindow.LoadedShopItems(), Config.ServerConfig.PATH_FOR_SHOP_GET_ALL, Utility.CoroutineRunner.RunCoroutine(), Game.UI.ShopWindow.shopItemsCache, and Game.UI.ShopWindow.ShowRequestFail().
Referenced by Game.UI.ShopItem.Bought(), and Game.UI.ShopWindow.Show().
LoadedShopItems()
void Game.UI.ShopWindow.LoadedShopItems (List< Shop > shopItems) inline private
Display the loaded shop items
Parameters
shopItems
Definition at line 100 of file ShopWindow.cs.
             {
                 //Failsafe for the tests
                 if (this.ShopParent == null || this.ShopParent.transform == null)
                 {
                     // Exit or handle the case when the ShopParent is destroyed
                     Debug.LogWarning("ShopParent has been destroyed or is missing.");
                     return;
                 }
                 //Delete the previous ones
                 for (int i = 0; i < this.ShopParent.transform.childCount; i++)
                 {
                     Destroy(this.ShopParent.transform.GetChild(i).gameObject);
                 }
                 this.ShopParent.transform.DetachChildren();
                 this.shopItemsCache = shopItems;
                 foreach (var item in shopItems)
                 {
                     ShopItem shopItem = Instantiate(ShopItemPrefab, ShopParent.transform).GetComponent<ShopItem>();
                     bool owned = UserData.Instance.Game.OwnedCars.Find(x => x.ShopId == item.ID) != null;
                     if (ShopItemSprites.Count <= (item.ID - 1))
                     {
                         shopItem.Init(this, item, ShopItemSprites[0], owned);
                         Debug.LogError("No sprite for this shop item");
                     }
                     else
                     {
                         shopItem.Init(this, item, ShopItemSprites[(int)(item.ID - 1)], owned);
                     }
                 }
             }
References User.UserData.Game, Game.UI.ShopItem.Init(), User.UserData.Instance, Game.UI.ShopWindow.ShopItemPrefab, Game.UI.ShopWindow.ShopItemSprites, and Game.UI.ShopWindow.ShopParent.
Referenced by Game.UI.ShopWindow.UpdateShop().
GetCoinText()
string Game.UI.ShopWindow.GetCoinText () inline
Get's the coin's displayed text
Returns
The displayed textt
Definition at line 140 of file ShopWindow.cs.
             {
                 return this.CoinText.text;
             }
GetShopParent()
GameObject Game.UI.ShopWindow.GetShopParent () inline
Gets the shop's parent
Returns
Reference to the parent
Definition at line 149 of file ShopWindow.cs.
             {
                 return this.ShopParent;
             }
References Game.UI.ShopWindow.ShopParent.
Member Data Documentation
ShopParent
GameObject Game.UI.ShopWindow.ShopParent private
The parent of the shop items
Definition at line 22 of file ShopWindow.cs.
Referenced by Game.UI.ShopWindow.GetShopParent(), and Game.UI.ShopWindow.LoadedShopItems().
ShopItemPrefab
GameObject Game.UI.ShopWindow.ShopItemPrefab private
A single shop item's prefab
Definition at line 28 of file ShopWindow.cs.
Referenced by Game.UI.ShopWindow.LoadedShopItems().
ShopItemSprites
List<Sprite> Game.UI.ShopWindow.ShopItemSprites = new List<Sprite>()
Shop item sprites (needs to be in order with the shop ids)
Definition at line 34 of file ShopWindow.cs.
Referenced by Game.UI.GameUI.LeftRotateSkin(), Game.UI.ShopWindow.LoadedShopItems(), and Game.UI.GameUI.RightRotateSkin().
CoinText
TMP_Text Game.UI.ShopWindow.CoinText private
Reference to the coin text display
Definition at line 40 of file ShopWindow.cs.
Referenced by Game.UI.ShopWindow.UpdateShop().
ModalWindow
ModalWindow Game.UI.ShopWindow.ModalWindow private
Reference to the modal window in the scene
Definition at line 46 of file ShopWindow.cs.
shopItemsCache
List<Shop> Game.UI.ShopWindow.shopItemsCache private
Cached shop items so we don't have to refresh every time since it is static mostly
Definition at line 51 of file ShopWindow.cs.
Referenced by Game.UI.ShopWindow.UpdateShop().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/UI/ShopWindow.cs