Bomberman: UnityStandardAssets.CrossPlatformInput.VirtualInput Class Reference
UnityStandardAssets.CrossPlatformInput.VirtualInput Class Reference abstract
Public Member Functions
bool AxisExists (string name)
bool ButtonExists (string name)
void RegisterVirtualAxis (CrossPlatformInputManager.VirtualAxis axis)
void RegisterVirtualButton (CrossPlatformInputManager.VirtualButton button)
void UnRegisterVirtualAxis (string name)
void UnRegisterVirtualButton (string name)
CrossPlatformInputManager.VirtualAxis VirtualAxisReference (string name)
void SetVirtualMousePositionX (float f)
void SetVirtualMousePositionY (float f)
void SetVirtualMousePositionZ (float f)
abstract float GetAxis (string name, bool raw)
abstract bool GetButton (string name)
abstract bool GetButtonDown (string name)
abstract bool GetButtonUp (string name)
abstract void SetButtonDown (string name)
abstract void SetButtonUp (string name)
abstract void SetAxisPositive (string name)
abstract void SetAxisNegative (string name)
abstract void SetAxisZero (string name)
abstract void SetAxis (string name, float value)
abstract Vector3 MousePosition ()
Protected Attributes
Dictionary< string, CrossPlatformInputManager.VirtualAxis > m_VirtualAxes
Dictionary< string, CrossPlatformInputManager.VirtualButton > m_VirtualButtons
List< string > m_AlwaysUseVirtual = new List<string>()
Properties
Vector3 virtualMousePosition [get, private set]
Detailed Description
Definition at line 8 of file VirtualInput.cs.
Member Function Documentation
AxisExists()
bool UnityStandardAssets.CrossPlatformInput.VirtualInput.AxisExists (string name) inline
Definition at line 22 of file VirtualInput.cs.
         {
             return m_VirtualAxes.ContainsKey(name);
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.AxisExists().
ButtonExists()
bool UnityStandardAssets.CrossPlatformInput.VirtualInput.ButtonExists (string name) inline
Definition at line 27 of file VirtualInput.cs.
         {
             return m_VirtualButtons.ContainsKey(name);
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.ButtonExists().
RegisterVirtualAxis()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualAxis (CrossPlatformInputManager.VirtualAxis axis) inline
Definition at line 33 of file VirtualInput.cs.
         {
             // check if we already have an axis with that name and log and error if we do
             if (m_VirtualAxes.ContainsKey(axis.name))
             {
                 Debug.LogError("There is already a virtual axis named " + axis.name + " registered.");
             }
             else
             {
                 // add any new axes
                 m_VirtualAxes.Add(axis.name, axis);
                 // if we dont want to match with the input manager setting then revert to always using virtual
                 if (!axis.matchWithInputManager)
                 {
                     m_AlwaysUseVirtual.Add(axis.name);
                 }
             }
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_AlwaysUseVirtual, and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis().
RegisterVirtualButton()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualButton (CrossPlatformInputManager.VirtualButton button) inline
Definition at line 54 of file VirtualInput.cs.
         {
             // check if already have a buttin with that name and log an error if we do
             if (m_VirtualButtons.ContainsKey(button.name))
             {
                 Debug.LogError("There is already a virtual button named " + button.name + " registered.");
             }
             else
             {
                 // add any new buttons
                 m_VirtualButtons.Add(button.name, button);
                 // if we dont want to match to the input manager then always use a virtual axis
                 if (!button.matchWithInputManager)
                 {
                     m_AlwaysUseVirtual.Add(button.name);
                 }
             }
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_AlwaysUseVirtual, and UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualButton().
UnRegisterVirtualAxis()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualAxis (string name) inline
Definition at line 75 of file VirtualInput.cs.
         {
             // if we have an axis with that name then remove it from our dictionary of registered axes
             if (m_VirtualAxes.ContainsKey(name))
             {
                 m_VirtualAxes.Remove(name);
             }
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualAxis().
UnRegisterVirtualButton()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualButton (string name) inline
Definition at line 85 of file VirtualInput.cs.
         {
             // if we have a button with this name then remove it from our dictionary of registered buttons
             if (m_VirtualButtons.ContainsKey(name))
             {
                 m_VirtualButtons.Remove(name);
             }
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.UnRegisterVirtualButton().
VirtualAxisReference()
CrossPlatformInputManager.VirtualAxis UnityStandardAssets.CrossPlatformInput.VirtualInput.VirtualAxisReference (string name) inline
Definition at line 96 of file VirtualInput.cs.
         {
             return m_VirtualAxes.ContainsKey(name) ? m_VirtualAxes[name] : null;
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxisReference().
SetVirtualMousePositionX()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionX (float f) inline
Definition at line 102 of file VirtualInput.cs.
         {
             virtualMousePosition = new Vector3(f, virtualMousePosition.y, virtualMousePosition.z);
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.virtualMousePosition.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionX().
SetVirtualMousePositionY()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionY (float f) inline
Definition at line 108 of file VirtualInput.cs.
         {
             virtualMousePosition = new Vector3(virtualMousePosition.x, f, virtualMousePosition.z);
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.virtualMousePosition.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionY().
SetVirtualMousePositionZ()
void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionZ (float f) inline
Definition at line 114 of file VirtualInput.cs.
         {
             virtualMousePosition = new Vector3(virtualMousePosition.x, virtualMousePosition.y, f);
         }
References UnityStandardAssets.CrossPlatformInput.VirtualInput.virtualMousePosition.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetVirtualMousePositionZ().
GetAxis()
abstract float UnityStandardAssets.CrossPlatformInput.VirtualInput.GetAxis (string name, bool raw) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetAxis().
GetButton()
abstract bool UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButton (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButton().
GetButtonDown()
abstract bool UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButtonDown (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonDown().
GetButtonUp()
abstract bool UnityStandardAssets.CrossPlatformInput.VirtualInput.GetButtonUp (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.GetButtonUp().
SetButtonDown()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetButtonDown (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonDown().
SetButtonUp()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetButtonUp (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetButtonUp().
SetAxisPositive()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisPositive (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisPositive().
SetAxisNegative()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisNegative (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisNegative().
SetAxisZero()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxisZero (string name) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxisZero().
SetAxis()
abstract void UnityStandardAssets.CrossPlatformInput.VirtualInput.SetAxis (string name, float value) pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Referenced by UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.SetAxis().
MousePosition()
abstract Vector3 UnityStandardAssets.CrossPlatformInput.VirtualInput.MousePosition () pure virtual
Implemented in UnityStandardAssets.CrossPlatformInput.PlatformSpecific.StandaloneInput, and UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.
Member Data Documentation
m_VirtualAxes
Dictionary<string, CrossPlatformInputManager.VirtualAxis> UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualAxes protected
Initial value:
=
            new Dictionary<string, CrossPlatformInputManager.VirtualAxis>()
Definition at line 13 of file VirtualInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.VirtualInput.AxisExists(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetAxis(), UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualAxis(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxis(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisNegative(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisPositive(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetAxisZero(), UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualAxis(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.VirtualAxisReference().
m_VirtualButtons
Dictionary<string, CrossPlatformInputManager.VirtualButton> UnityStandardAssets.CrossPlatformInput.VirtualInput.m_VirtualButtons protected
Initial value:
=
            new Dictionary<string, CrossPlatformInputManager.VirtualButton>()
Definition at line 16 of file VirtualInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.VirtualInput.ButtonExists(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButton(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonDown(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.GetButtonUp(), UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualButton(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonDown(), UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.SetButtonUp(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.UnRegisterVirtualButton().
m_AlwaysUseVirtual
List<string> UnityStandardAssets.CrossPlatformInput.VirtualInput.m_AlwaysUseVirtual = new List<string>() protected
Definition at line 18 of file VirtualInput.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualAxis(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.RegisterVirtualButton().
Property Documentation
virtualMousePosition
Vector3 UnityStandardAssets.CrossPlatformInput.VirtualInput.virtualMousePosition get private set
Definition at line 10 of file VirtualInput.cs.
 { get; private set; }
Referenced by UnityStandardAssets.CrossPlatformInput.PlatformSpecific.MobileInput.MousePosition(), UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionX(), UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionY(), and UnityStandardAssets.CrossPlatformInput.VirtualInput.SetVirtualMousePositionZ().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/VirtualInput.cs