Bomberman: UIController Class Reference
UIController Class Reference
Public Member Functions
void UpdateUserData (Thesis_backend.Data_Structures.User user)
void RemoveTask (long taskId)
void UpdateTask (long taskId)
void LoadGoodTasks (bool updateDisplay=true)
void LoadBadHabits (bool updateDisplay=true)
GameObject CreateTask (PlayerTask taskContainer)
void SendLogout ()
Send a login request with the login panel's fields.
void LoadGameScene ()
Public Attributes
ModalWindow ModalWindow
Private Member Functions
void Start ()
void Update ()
void LoggedOut (string result)
When the logout was a success.
IEnumerator MoveToLoginScene ()
void LoadTasks ()
void CreateTaskPrefabs (List< Thesis_backend.Data_Structures.PlayerTask > requestResult)
Private Attributes
TMP_Text UsernameInputText
TMP_Text CurrencyText
GameObject TaskParent
GameObject TaskPrefab
TaskOpenPanelController taskOpenPanelController
Dictionary< long, TaskDisplayHandler > tasks = new Dictionary<long, TaskDisplayHandler>()
Detailed Description
Definition at line 10 of file UIController.cs.
Member Function Documentation
Start()
void UIController.Start () inline private
Definition at line 33 of file UIController.cs.
    {
        if (!UserData.Instance.LoggedIn)
        {
            StartCoroutine(MoveToLoginScene());
        }
        else
        {
            UsernameInputText.text = UserData.Instance.Username;
            CurrencyText.text = UserData.Instance.CurrentTaskScore.ToString();
            LoadTasks();
        }
    }
References User.UserData.CurrentTaskScore, User.UserData.Instance, LoadTasks(), User.UserData.LoggedIn, MoveToLoginScene(), and User.UserData.Username.
UpdateUserData()
void UIController.UpdateUserData (Thesis_backend::Data_Structures::User user) inline
Definition at line 47 of file UIController.cs.
    {
        UserData.Instance.Init(user);
        CurrencyText.text = UserData.Instance.CurrentTaskScore.ToString();
    }
References User.UserData.CurrentTaskScore, User.UserData.Init(), and User.UserData.Instance.
Referenced by TaskDisplayHandler.TaskCompleted().
Update()
void UIController.Update () inline private
Definition at line 54 of file UIController.cs.
    {
    }
RemoveTask()
void UIController.RemoveTask (long taskId) inline
Definition at line 58 of file UIController.cs.
    {
        if (tasks.ContainsKey(taskId))
        {
            TaskDisplayHandler TaskToRemove = tasks[taskId];
            tasks.Remove(taskId);
            Destroy(TaskToRemove.gameObject);
        }
    }
References tasks.
Referenced by TaskOpenPanelController.DeletedTask().
UpdateTask()
void UIController.UpdateTask (long taskId) inline
Definition at line 68 of file UIController.cs.
    {
        if (tasks.ContainsKey(taskId))
        {
            tasks[taskId].UpdateLabels();
        }
    }
References tasks.
Referenced by TaskOpenPanelController.SavedTask().
LoadGoodTasks()
void UIController.LoadGoodTasks (bool updateDisplay = true) inline
Definition at line 76 of file UIController.cs.
    {
        foreach (var task in tasks)
        {
            if (!task.Value.CurrentTask.TaskType)
            {
                task.Value.gameObject.SetActive(true);
            }
            else
            {
                task.Value.gameObject.SetActive(false);
            }
        }
        TaskParent.GetComponentInChildren<TMP_Text>().text = "Good tasks";
        if (updateDisplay)
            taskOpenPanelController.MakeItGoodTask();
    }
References TaskOpenPanelController.MakeItGoodTask(), taskOpenPanelController, TaskParent, and tasks.
Referenced by CreateTaskPrefabs(), and TaskOpenPanelController.MakeItGoodTask().
LoadBadHabits()
void UIController.LoadBadHabits (bool updateDisplay = true) inline
Definition at line 94 of file UIController.cs.
    {
        foreach (var task in tasks)
        {
            if (task.Value.CurrentTask.TaskType)
            {
                task.Value.gameObject.SetActive(true);
            }
            else
            {
                task.Value.gameObject.SetActive(false);
            }
        }
        TaskParent.GetComponentInChildren<TMP_Text>().text = "Bad habits";
        if (updateDisplay)
            taskOpenPanelController.MakeItBadHabit();
    }
References TaskOpenPanelController.MakeItBadHabit(), taskOpenPanelController, TaskParent, and tasks.
Referenced by TaskOpenPanelController.MakeItBadHabit().
CreateTask()
GameObject UIController.CreateTask (PlayerTask taskContainer) inline
Definition at line 112 of file UIController.cs.
    {
        GameObject task = Instantiate(TaskPrefab, TaskParent.transform);
        TaskDisplayHandler taskComponent = task.GetComponent<TaskDisplayHandler>();
        taskComponent.InitValues(taskContainer, taskOpenPanelController, this);
        tasks.Add(taskContainer.ID, taskComponent);
        return task;
    }
References TaskDisplayHandler.InitValues(), taskOpenPanelController, TaskParent, TaskPrefab, and tasks.
Referenced by CreateTaskPrefabs(), and TaskOpenPanelController.SavedTask().
SendLogout()
void UIController.SendLogout () inline
Send a login request with the login panel's fields.
Definition at line 126 of file UIController.cs.
    {
        StartCoroutine(Server.SendDeleteRequest<string>(ServerConfig.PATHFORLOGOUT, LoggedOut));
        //UserData.Instance.Logout();
        //  StartCoroutine(MoveToLoginScene());
    }
References LoggedOut(), and Config.ServerConfig.PATHFORLOGOUT.
LoggedOut()
void UIController.LoggedOut (string result) inline private
When the logout was a success.
Parameters
result The server's response
Definition at line 139 of file UIController.cs.
    {
        UserData.Instance.Logout();
        StartCoroutine(MoveToLoginScene());
    }
References User.UserData.Instance, User.UserData.Logout(), and MoveToLoginScene().
Referenced by SendLogout().
MoveToLoginScene()
IEnumerator UIController.MoveToLoginScene () inline private
Definition at line 146 of file UIController.cs.
    {
        AsyncOperation loading = SceneManager.LoadSceneAsync("LoginScene", LoadSceneMode.Single);
        while (true)
        {
            Debug.Log(loading.progress);
            yield return null;
        }
    }
Referenced by LoggedOut(), and Start().
LoadTasks()
void UIController.LoadTasks () inline private
Definition at line 158 of file UIController.cs.
    {
        StartCoroutine(Server.SendGetRequest<List<Thesis_backend.Data_Structures.PlayerTask>>(ServerConfig.PATHFORTASKSQUERY, CreateTaskPrefabs));
    }
References CreateTaskPrefabs(), and Config.ServerConfig.PATHFORTASKSQUERY.
Referenced by Start().
LoadGameScene()
void UIController.LoadGameScene () inline
Definition at line 163 of file UIController.cs.
    {
        SceneManager.LoadScene("GameScene", LoadSceneMode.Single);
    }
CreateTaskPrefabs()
void UIController.CreateTaskPrefabs (List< Thesis_backend::Data_Structures::PlayerTask > requestResult) inline private
Definition at line 168 of file UIController.cs.
    {
        foreach (var item in requestResult)
        {
            CreateTask(item);
        }
        LoadGoodTasks();
    }
References CreateTask(), and LoadGoodTasks().
Referenced by LoadTasks().
Member Data Documentation
UsernameInputText
TMP_Text UIController.UsernameInputText private
Definition at line 13 of file UIController.cs.
CurrencyText
TMP_Text UIController.CurrencyText private
Definition at line 16 of file UIController.cs.
TaskParent
GameObject UIController.TaskParent private
Definition at line 19 of file UIController.cs.
Referenced by CreateTask(), LoadBadHabits(), and LoadGoodTasks().
TaskPrefab
GameObject UIController.TaskPrefab private
Definition at line 22 of file UIController.cs.
Referenced by CreateTask().
taskOpenPanelController
TaskOpenPanelController UIController.taskOpenPanelController private
Definition at line 25 of file UIController.cs.
Referenced by CreateTask(), LoadBadHabits(), and LoadGoodTasks().
ModalWindow
ModalWindow UIController.ModalWindow
Definition at line 28 of file UIController.cs.
Referenced by TaskOpenPanelController.DeletedTask().
tasks
Dictionary<long, TaskDisplayHandler> UIController.tasks = new Dictionary<long, TaskDisplayHandler>() private
Definition at line 30 of file UIController.cs.
Referenced by CreateTask(), LoadBadHabits(), LoadGoodTasks(), RemoveTask(), and UpdateTask().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/MainPage/UIController.cs