Bomberman: UnityStandardAssets.CrossPlatformInput.AxisTouchButton Class Reference
UnityStandardAssets.CrossPlatformInput.AxisTouchButton Class Reference
Public Member Functions
void OnPointerDown (PointerEventData data)
void OnPointerUp (PointerEventData data)
Public Attributes
string axisName = "Horizontal"
float axisValue = 1
float responseSpeed = 3
float returnToCentreSpeed = 3
Private Member Functions
void OnEnable ()
void FindPairedButton ()
void OnDisable ()
Private Attributes
AxisTouchButton m_PairedWith
CrossPlatformInputManager.VirtualAxis m_Axis
Detailed Description
Definition at line 7 of file AxisTouchButton.cs.
Member Function Documentation
OnEnable()
void UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable () inline private
Definition at line 19 of file AxisTouchButton.cs.
     {
       if (!CrossPlatformInputManager.AxisExists(axisName))
       {
         // if the axis doesnt exist create a new one in cross platform input
         m_Axis = new CrossPlatformInputManager.VirtualAxis(axisName);
         CrossPlatformInputManager.RegisterVirtualAxis(m_Axis);
       }
       else
       {
         m_Axis = CrossPlatformInputManager.VirtualAxisReference(axisName);
       }
       FindPairedButton();
     }
References UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.AxisExists(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.axisName, UnityStandardAssets.CrossPlatformInput.AxisTouchButton.FindPairedButton(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_Axis, UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.RegisterVirtualAxis(), and UnityStandardAssets.CrossPlatformInput.CrossPlatformInputManager.VirtualAxisReference().
FindPairedButton()
void UnityStandardAssets.CrossPlatformInput.AxisTouchButton.FindPairedButton () inline private
Definition at line 34 of file AxisTouchButton.cs.
     {
       // find the other button witch which this button should be paired
       // (it should have the same axisName)
       var otherAxisButtons = FindObjectsOfType(typeof(AxisTouchButton)) as AxisTouchButton[];
       if (otherAxisButtons != null)
       {
         for (int i = 0; i < otherAxisButtons.Length; i++)
         {
           if (otherAxisButtons[i].axisName == axisName && otherAxisButtons[i] != this)
           {
             m_PairedWith = otherAxisButtons[i];
           }
         }
       }
     }
References UnityStandardAssets.CrossPlatformInput.AxisTouchButton.axisName, and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_PairedWith.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown().
OnDisable()
void UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnDisable () inline private
Definition at line 52 of file AxisTouchButton.cs.
     {
       // The object is disabled so remove it from the cross platform input system
       m_Axis.Remove();
     }
References UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_Axis.
OnPointerDown()
void UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown (PointerEventData data) inline
Definition at line 59 of file AxisTouchButton.cs.
     {
       if (m_PairedWith == null)
       {
         FindPairedButton();
       }
       // update the axis and record that the button has been pressed this frame
       m_Axis.Update(Mathf.MoveTowards(m_Axis.GetValue, axisValue, responseSpeed * Time.deltaTime));
     }
References UnityStandardAssets.CrossPlatformInput.AxisTouchButton.axisValue, UnityStandardAssets.CrossPlatformInput.AxisTouchButton.FindPairedButton(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_Axis, UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_PairedWith, and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.responseSpeed.
OnPointerUp()
void UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerUp (PointerEventData data) inline
Definition at line 70 of file AxisTouchButton.cs.
     {
       m_Axis.Update(Mathf.MoveTowards(m_Axis.GetValue, 0, responseSpeed * Time.deltaTime));
     }
References UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_Axis, and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.responseSpeed.
Member Data Documentation
axisName
string UnityStandardAssets.CrossPlatformInput.AxisTouchButton.axisName = "Horizontal"
Definition at line 11 of file AxisTouchButton.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.FindPairedButton(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable().
axisValue
float UnityStandardAssets.CrossPlatformInput.AxisTouchButton.axisValue = 1
Definition at line 12 of file AxisTouchButton.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown().
responseSpeed
float UnityStandardAssets.CrossPlatformInput.AxisTouchButton.responseSpeed = 3
Definition at line 13 of file AxisTouchButton.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerUp().
returnToCentreSpeed
float UnityStandardAssets.CrossPlatformInput.AxisTouchButton.returnToCentreSpeed = 3
Definition at line 14 of file AxisTouchButton.cs.
m_PairedWith
AxisTouchButton UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_PairedWith private
Definition at line 16 of file AxisTouchButton.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.FindPairedButton(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown().
m_Axis
CrossPlatformInputManager.VirtualAxis UnityStandardAssets.CrossPlatformInput.AxisTouchButton.m_Axis private
Definition at line 17 of file AxisTouchButton.cs.
Referenced by UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnDisable(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnEnable(), UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerDown(), and UnityStandardAssets.CrossPlatformInput.AxisTouchButton.OnPointerUp().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CrossPlatformInput/Scripts/AxisTouchButton.cs