Thesis: Game.Car Class Reference
Game.Car Class Reference
Public Member Functions
void Kill ()
void Init (GameController world)
Public Attributes
EventHandler DestroyedEvent
Protected Member Functions
virtual void Update ()
bool ChangeChunkIfNeeded ()
virtual async void ChunkChanged (Chunk newChunk)
virtual void OnCollisionEnter (Collision collision)
void Awake ()
Protected Member Functions inherited from Utility.ThreadSafeMonoBehaviour
void OnDestroy ()
Called when the gameobject has been destroyed
Protected Attributes
GameController gameController
CarController carController
Chunk lastChunk
Dictionary< EffectType, EffectScript > effects = new Dictionary<EffectType, EffectScript>()
Properties
float Health [get, protected set]
float MAX_HEALTH [get, private set]
bool Alive [get]
Properties inherited from Utility.ThreadSafeMonoBehaviour
bool Destroyed [get, private set]
True if the gameobject been destroyed
Private Attributes
float health = 10f
Detailed Description
Definition at line 14 of file Car.cs.
Member Function Documentation
Update()
virtual void Game.Car.Update () inline protected virtual
Reimplemented in Game.PlayerCar, and Game.CopCar.
Definition at line 35 of file Car.cs.
         {
             if (gameController is null || !Alive)
             {
                 return;
             }
             if (ChangeChunkIfNeeded())
             {
             }
         }
References Game.Car.Alive, Game.Car.ChangeChunkIfNeeded(), and Game.Car.gameController.
Kill()
void Game.Car.Kill () inline
Definition at line 46 of file Car.cs.
         {
             this.health = 0;
             this.DestroyedEvent?.Invoke(this, EventArgs.Empty);
         }
Referenced by Game.UI.GameUI.BackToGameMenuWithoutSave().
ChangeChunkIfNeeded()
bool Game.Car.ChangeChunkIfNeeded () inline protected
Definition at line 52 of file Car.cs.
         {
             Chunk newChunk = this.gameController.World.GetChunk(this.gameObject.transform.position);
             if (lastChunk != newChunk && newChunk != null)
             {
                 ChunkChanged(newChunk);
                 lastChunk = newChunk;
                 this.gameObject.transform.parent = newChunk.transform;
                 if (this.gameObject.isStatic)
                 {
                     this.gameObject.isStatic = false;
                 }
                 return true;
             }
             return false;
         }
References Game.Car.ChunkChanged(), Game.World.GameWorld.GetChunk(), Game.Car.lastChunk, and Game.GameController.World.
Referenced by Game.Car.Update().
ChunkChanged()
virtual async void Game.Car.ChunkChanged (Chunk newChunk) inline protected virtual
Reimplemented in Game.PlayerCar.
Definition at line 71 of file Car.cs.
         {
         }
Referenced by Game.Car.ChangeChunkIfNeeded().
Init()
void Game.Car.Init (GameController world) inline
Definition at line 75 of file Car.cs.
         {
             this.health = MAX_HEALTH;
             this.gameController = world;
             if (effects.ContainsKey(EffectType.Smoke))
                 effects[EffectType.Smoke].gameObject.SetActive(false);
             if (effects.ContainsKey(EffectType.Fire))
                 effects[EffectType.Fire].gameObject.SetActive(false);
             if (effects.ContainsKey(EffectType.Shield))
                 effects[EffectType.Shield].gameObject.SetActive(false);
             if (effects.ContainsKey(EffectType.Turbo))
                 effects[EffectType.Turbo].gameObject.SetActive(false);
         }
References Game.Car.effects, and Game.Car.MAX_HEALTH.
Referenced by Game.GameController.NewGame(), and Game.World.CarSpawner.SpawnPolice().
OnCollisionEnter()
virtual void Game.Car.OnCollisionEnter (Collision collision) inline protected virtual
Reimplemented in Game.PlayerCar.
Definition at line 93 of file Car.cs.
         {
             //Debug.Log("Collided " + gameObject.name + "with " + collision.gameObject.name + "at " + collision.relativeVelocity.sqrMagnitude);
             float dmgAmount = collision.relativeVelocity.sqrMagnitude / 500f;
             if (dmgAmount > GameConfig.CAR_DAMAGE_LOWER_LIMIT)
             {
                 if (dmgAmount > GameConfig.CAR_DAMAGE_UPPER_LIMIT)
                 {
                     dmgAmount = GameConfig.CAR_DAMAGE_UPPER_LIMIT;
                 }
                 Health -= dmgAmount;
                 if (health < 0)
                 {
                     DestroyedEvent?.Invoke(this, EventArgs.Empty);
                 }
                 if (Health / MAX_HEALTH < GameConfig.SMOKE_THRESHOLD)
                 {
                     if (effects.ContainsKey(EffectType.Smoke))
                         effects[EffectType.Smoke].gameObject.SetActive(true);
                 }
                 if (Health / MAX_HEALTH < GameConfig.FIRE_THRESHOLD)
                 {
                     if (effects.ContainsKey(EffectType.Fire))
                         effects[EffectType.Fire].gameObject.SetActive(true);
                 }
             }
         }
References Game.GameConfig.CAR_DAMAGE_LOWER_LIMIT, Game.GameConfig.CAR_DAMAGE_UPPER_LIMIT, Game.Car.DestroyedEvent, Game.Car.effects, Game.GameConfig.FIRE_THRESHOLD, Game.Car.health, Game.Car.Health, Game.Car.MAX_HEALTH, and Game.GameConfig.SMOKE_THRESHOLD.
Awake()
void Game.Car.Awake () inline protected
Definition at line 126 of file Car.cs.
         {
             this.carController = this.gameObject.GetComponent<CarController>();
             this.MAX_HEALTH = health;
             foreach (var item in this.GetComponentsInChildren<EffectScript>())
             {
                 item.gameObject.SetActive(false);
                 if (!effects.ContainsKey(item.EffectType))
                 {
                     effects.Add(item.EffectType, item);
                 }
                 else
                 {
                     Debug.LogError("multiple events with this type");
                 }
             }
         }
References Game.Car.effects, Game.Car.health, and Game.Car.MAX_HEALTH.
Member Data Documentation
gameController
GameController Game.Car.gameController protected
Definition at line 16 of file Car.cs.
Referenced by Game.PlayerCar.ChunkChanged(), Game.NpcCar.DetermineSteeringDirectionTowardsPlayer(), Game.PlayerCar.PickedUpCoin(), Game.Car.Update(), Game.CopCar.Update(), and Game.PlayerCar.Update().
carController
CarController Game.Car.carController protected
Definition at line 17 of file Car.cs.
Referenced by Game.PlayerCar.FixedUpdate(), and Game.CopCar.Update().
lastChunk
Chunk Game.Car.lastChunk protected
Definition at line 18 of file Car.cs.
Referenced by Game.Car.ChangeChunkIfNeeded().
DestroyedEvent
EventHandler Game.Car.DestroyedEvent
Definition at line 19 of file Car.cs.
Referenced by Game.GameController.NewGame(), Game.Car.OnCollisionEnter(), and Game.PlayerCar.Update().
health
float Game.Car.health = 10f private
Definition at line 22 of file Car.cs.
Referenced by Game.Car.Awake(), and Game.Car.OnCollisionEnter().
effects
Dictionary<EffectType, EffectScript> Game.Car.effects = new Dictionary<EffectType, EffectScript>() protected
Definition at line 27 of file Car.cs.
Referenced by Game.PlayerCar.ApplyImmunity(), Game.PlayerCar.ApplyTurbo(), Game.Car.Awake(), Game.PlayerCar.CancelImmunity(), Game.PlayerCar.CancelTurbo(), Game.Car.Init(), Game.Car.OnCollisionEnter(), and Game.PlayerCar.Update().
Property Documentation
Health
float Game.Car.Health get protected set
Definition at line 29 of file Car.cs.
 { get => health; protected set => health = value; }
Referenced by Game.Car.OnCollisionEnter().
MAX_HEALTH
float Game.Car.MAX_HEALTH get private set
Definition at line 31 of file Car.cs.
 { get; private set; }
Referenced by Game.Car.Awake(), Game.Car.Init(), and Game.Car.OnCollisionEnter().
Alive
bool Game.Car.Alive get
Definition at line 33 of file Car.cs.
Referenced by Game.PlayerCar.FixedUpdate(), Game.Car.Update(), and Game.CopCar.Update().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Game/CarScripts/Car.cs