Thesis: Utility.CoroutineRunner Class Reference
Utility.CoroutineRunner Class Reference
Singleton class to run the coroutines so they are easier to track
Static Public Member Functions
static Coroutine RunCoroutine (IEnumerator coroutine)
A helper method to start coroutines
static void StopAllCoroutinesGlobal ()
As the name implies stop every coroutine
Properties
static CoroutineRunner Instance [get]
Singleton instance getter
Static Private Attributes
static CoroutineRunner _instance
Detailed Description
Singleton class to run the coroutines so they are easier to track
Definition at line 9 of file CoroutineRunner .cs.
Member Function Documentation
RunCoroutine()
static Coroutine Utility.CoroutineRunner.RunCoroutine (IEnumerator coroutine) inline static
A helper method to start coroutines
Parameters
coroutine The coroutine to start
Returns
The startted coroutine
Definition at line 37 of file CoroutineRunner .cs.
         {
             return Instance.StartCoroutine(coroutine);
         }
References Utility.CoroutineRunner.Instance.
Referenced by MainPage.FriendHandler.AcceptFriendRequest(), Game.UI.ShopItem.Buy(), Game.UI.GameUI.BuyImmunity(), Game.UI.GameUI.BuyTurbo(), User.UserController.CheckLoggedIn(), User.LoggedInChecker.CheckLoggedInPeriodically(), MainPage.TaskDisplayHandler.CompleteTask(), MainPage.FriendHandler.DeleteFriend(), MainPage.TaskOpenPanelController.DeleteTask(), Game.UI.GameUI.DoubleCoins(), MainPage.FriendWindowHandler.LoadFriends(), Game.UI.LeaderboardWindow.LoadScores(), MainPage.TaskHistoryWindowHandler.LoadTaskHistories(), MainPage.MainWindowController.LoadTasks(), User.UserController.LoggedIn(), MainPage.ProfileHandler.LoggedOut(), User.UserController.Registered(), MainPage.TaskOpenPanelController.Save(), Game.UI.GameUI.SaveGameResult(), MainPage.FriendWindowHandler.SendFriendRequest(), User.UserController.SendLogin(), MainPage.ProfileHandler.SendLogout(), User.UserController.SendRegister(), Game.World.Chunk.SpawnWorldObjects(), MainPage.TaskDisplayHandler.TaskCompleted(), and Game.UI.ShopWindow.UpdateShop().
StopAllCoroutinesGlobal()
static void Utility.CoroutineRunner.StopAllCoroutinesGlobal () inline static
As the name implies stop every coroutine
Definition at line 45 of file CoroutineRunner .cs.
         {
             Instance.StopAllCoroutines(); // Directly stop coroutines without recursion
         }
References Utility.CoroutineRunner.Instance.
Member Data Documentation
_instance
CoroutineRunner Utility.CoroutineRunner._instance static private
Definition at line 12 of file CoroutineRunner .cs.
Property Documentation
Instance
CoroutineRunner Utility.CoroutineRunner.Instance static get
Singleton instance getter
Definition at line 17 of file CoroutineRunner .cs.
         {
             get
             {
                 if (_instance == null)
                 {
                     // Create a new GameObject to host the CoroutineRunner if it doesn't exist
                     GameObject obj = new GameObject("CoroutineRunner");
                     _instance = obj.AddComponent<CoroutineRunner>();
                     DontDestroyOnLoad(obj); // Make sure it persists across scenes
                 }
                 return _instance;
             }
         }
Referenced by Utility.CoroutineRunner.RunCoroutine(), and Utility.CoroutineRunner.StopAllCoroutinesGlobal().
The documentation for this class was generated from the following file:
Assets/Scripts/Client/Utility/CoroutineRunner .cs